// Generated by CoffeeScript 2.7.0
var Element, Group, lineEl, shapeGroup;

Element = class Element {
  constructor(config) {
    this.type = config.type || "line";
    this.prop = Object.assign({
      elements: []
    }, config.prop);
    if (this.prop.parentGroup) {
      this.joinGroup(this.prop.parentGroup);
    }
  }

  joinGroup(group) {
    this.prop.parentGroup = group;
    if (group.prop.elements.indexOf(this) === -1) {
      return group.prop.elements.push(this);
    }
  }

};

Group = class Group extends Element {
  constructor(config) {
    super(config);
    this.type = "group";
  }

};

shapeGroup = new Group({
  prop: {
    elements: []
  }
});

lineEl = new Element({
  type: "line",
  prop: {
    parentGroup: shapeGroup
  }
});

console.log("ShapeGroup elements length:", shapeGroup.prop.elements.length);
