// Generated by CoffeeScript 2.7.0
var BucketTool;

import data from "../svgEditor_data.js";

import findRegions from "../tools/findRegions/main.js";

import PureFill from "../svgEditor_pureFill.js";

import FillGroup from "../svgEditor_fillGroup.js";

import pointInRegions from "../tools/pointInRegions.js";

import tools from "../../tools.js";

import splitBezier from "../tools/splitBezier/main.js";

export default BucketTool = class BucketTool {
  constructor() {
    this.regionSaves = {};
    this.presentRegions = [];
    this.allRegions = [];
    this.gapTolerance = 0;
    this.debugShowVirtualLines = true;
  }

  findRegions(elements, site) {
    var elementsStr;
    elementsStr = {
      elements: elements,
      site: site
    };
    if (0) { //@regionSaves[elementsStr]
      return this.regionSaves[elementsStr];
    } else {
      this.allRegions = this.presentRegions = this.regionSaves[elementsStr] = findRegions(elements, {gapTolerance: this.gapTolerance, debugShowVirtualLines: this.debugShowVirtualLines});
      if (site) {
        this.presentRegions = this.regionSaves[elementsStr] = pointInRegions(site, this.presentRegions);
      }
      //配置预览 - 适配新的区域对象格式
      if (this.presentRegions.length > 0) {
        return data.preFulls = [this.presentRegions[0]].map((regionObj) => {
          var ref;
          return new PureFill({
            prop: {
              elements: regionObj.elements,
              childRegions: (ref = regionObj.children) != null ? ref.map(function(child) {
                return child.elements;
              }) : void 0,
              fill: "url(#preFill)"
            }
          });
        });
      } else {
        return data.preFulls = [];
      }
    }
  }

  fill(element, fillColor, regions, onlyFirst = true) {
    fillColor = fillColor || data.colorTool.bgColor;
    regions = regions ? findRegions(regions, {gapTolerance: this.gapTolerance, debugShowVirtualLines: this.debugShowVirtualLines}) : this.presentRegions;
    if (element) {
      if (element.type === "pureFill") {
        return element.prop.fill = fillColor;
      }
    } else {
      //console.log "所有区域",JSON.stringify lodash.cloneDeep(@allRegions)
      //console.log "可填充区域",JSON.stringify lodash.cloneDeep(@presentRegions)

      //console.log "可填充区域长度",regions.length
      return regions.forEach((regionObj, index) => {
        var child, childRegions, i, isConsistent, len, pg, pureFill, ref, ref1;
        if (onlyFirst) {
          if (index > 0) { // 只填充第一个区域（面积最小的）
            return;
          }
        }
        //console.log "填充区域对象:", regionObj
        //console.log "区域children属性:", regionObj.children
        //console.log "children长度:", regionObj.children?.length || 0
        childRegions = regionObj.children ? regionObj.children.map((child) => {
          return child.elements || [];
        }) : [];
        //console.log "处理后的childRegions:", childRegions
        pg = ((ref = regionObj.elements[0]) != null ? ref.prop.parentGroup : void 0) || null;
        
        // 严格校验：确保所有外边界线条和子区域线条的逻辑编组是一致的
        isConsistent = regionObj.elements.every((el) => {
          return (el.prop.parentGroup || null) === pg;
        });
        if (isConsistent && regionObj.children) {
          ref1 = regionObj.children;
          for (i = 0, len = ref1.length; i < len; i++) {
            child = ref1[i];
            if (!child.elements.every((el) => {
              return (el.prop.parentGroup || null) === pg;
            })) {
              isConsistent = false;
              break;
            }
          }
        }
        if (!isConsistent) {
          console.warn("警告：构成闭合区域的线条属于不同的逻辑编组，拒绝为其创建填充区！");
          return;
        }
        //创建纯填充 - 使用区域对象的elements属性
        data.elPaper.elements.unshift(pureFill = new PureFill({
          prop: {
            elements: regionObj.elements,
            childRegions: childRegions,
            fill: fillColor,
            parentGroup: pg
          }
        }));
        //创建填充组 - 使用区域对象的elements属性
        //填充组交给切割函数，这里不再创建填充组，保留这个备注
        /* fillGroup = new FillGroup
                 prop:
                   elements:regionObj.elements
                   childRegions:childRegions
                   pureFill:pureFill
                   fill:fillColor
                   parentGroup:pg
               data.elPaper.elements.unshift fillGroup */
        //console.log "填充后的填充组",fillGroup
        return pureFill;
      });
    }
  }

  addListener(dom) {
    var domSite;
    domSite = null;
    if (1) { //not @bucketPointerdown
      dom.addEventListener("pointerdown", this.bucketPointerdown = (e) => {
        var closedPureFill, x0, x1, y0, y1;
        domSite = dom.getBoundingClientRect();
        if (data.getPresentTool().name !== "bucket") {
          return;
        }
        x0 = x1 = data.getLocalX(e.clientX, domSite);
        y0 = y1 = data.getLocalY(e.clientY, domSite);
        closedPureFill = data.elPaper.getClosedPureFill({
          x: x1,
          y: y1
        });
        if (!this.bucketPointerUp) {
          return document.addEventListener("pointerup", this.bucketPointerUp = (e) => {
            var fill, fillSite, lines, x3, y3;
            x3 = data.getLocalX(e.clientX, domSite);
            y3 = data.getLocalY(e.clientY, domSite);
            if (closedPureFill && closedPureFill.prop.parentGroup === data.presentGroup) {
              this.fill(closedPureFill);
            } else {
              lines = data.elPaper.getLines().filter((el) => {
                return el.prop.parentGroup === data.presentGroup;
              });
              fillSite = {
                x: x3,
                y: y3
              };
              if (data.presentGroup) {
                fillSite = data.presentGroup.globalToLocal(fillSite);
              }
              this.findRegions(lines, fillSite);
              fill = this.fill();
              data.preFulls = [];
            }
            // 填充完成后执行一次画布切割（与光标选择/绘图操作一致）
            splitBezier.splitPaper();
            m.redraw();
            data.record("油漆桶填充");
            return this.bucketPointerUp = document.removeEventListener("pointerup", this.bucketPointerUp);
          });
        }
      });
    }
    if (1) { //not @bucketPointermove2
      return dom.addEventListener("pointermove", this.bucketPointermove2 = (e) => {
        var lines, previewSite, x, y;
        if (data.getPresentTool().name !== "bucket") {
          return;
        }
        // 查找可填充区域
        domSite = dom.getBoundingClientRect();
        x = data.getLocalX(e.clientX, domSite);
        y = data.getLocalY(e.clientY, domSite);
        //触发查找可填充区域
        lines = data.elPaper.getLines().filter((el) => {
          return el.prop.parentGroup === data.presentGroup;
        });
        previewSite = {x, y};
        if (data.presentGroup) {
          previewSite = data.presentGroup.globalToLocal(previewSite);
        }
        this.findRegions(lines, previewSite);
        return m.redraw();
      });
    }
  }

  addPathListener(dom, element) {
    return dom.addEventListener("click", () => {
      if (data.getPresentTool().name !== "bucket") {
        return;
      }
      if (element.type !== "pureFill") {
        return;
      }
      if ((element.prop.parentGroup || null) !== (data.presentGroup || null)) {
        return;
      }
      this.fill(element);
      return m.redraw();
    });
  }

};
