// Generated by CoffeeScript 2.7.0
import data from "../svgEditor_data.js";

export default (class {
  constructor() {}

  addListener(dom) {
    var domSite;
    domSite = dom.getBoundingClientRect();
    return dom.addEventListener("pointerdown", this.rectToolPointerdown = function(e) {
      var x0, x1, y0, y1;
      if (data.getPresentTool().name !== "ellipse") {
        return;
      }
      x0 = x1 = data.getLocalX(e.clientX, domSite);
      y0 = y1 = data.getLocalY(e.clientY, domSite);
      if (!this.rectToolPointermove) {
        dom.addEventListener("pointermove", this.rectToolPointermove = function(e) {
          var x2, y2;
          x2 = data.getLocalX(e.clientX, domSite);
          y2 = data.getLocalY(e.clientY, domSite);
          x1 = x2;
          y1 = y2;
          return m.redraw();
        });
      }
      if (!this.rectToolPointerup) {
        return dom.addEventListener("pointerup", this.rectToolPointerup = function(e) {
          this.rectToolPointermove = dom.removeEventListener("pointermove", this.rectToolPointermove);
          return this.rectToolPointerup = dom.removeEventListener("pointerup", this.rectToolPointerup);
        });
      }
    });
  }

});
