// Generated by CoffeeScript 2.7.0
var MoveTool, getDisSq;

import data from "../svgEditor_data.js";

import Element from "../svgEditor_element.js";

import Paper from "../svgEditor_paper.js";

import splitBezier from "../tools/splitBezier/main.js";

getDisSq = function(site1, site2) {
  return (site1.x - site2.x) ** 2 + (site1.y - site2.y) ** 2;
};

export default MoveTool = class MoveTool {
  constructor() {
    this.pointSnapR = Mob ? 20 : 15;
    this.endpointR = Mob ? 20 : 15;
    this.lastClickTime = 0;
    this.lastClickId = null;
  }

  abort() {
    if (this.pathPointermove) {
      document.removeEventListener("pointermove", this.pathPointermove);
      this.pathPointermove = null;
    }
    if (this.pathPointerup) {
      document.removeEventListener("pointerup", this.pathPointerup);
      this.pathPointerup = null;
    }
    if (this.cursorPointermove) {
      document.removeEventListener("pointermove", this.cursorPointermove);
      this.cursorPointermove = null;
    }
    if (this.cursorPointerup) {
      document.removeEventListener("pointerup", this.cursorPointerup);
      this.cursorPointerup = null;
    }
    if (this.cursorChoiseBoxPointermove) {
      document.removeEventListener("pointermove", this.cursorChoiseBoxPointermove);
      this.cursorChoiseBoxPointermove = null;
    }
    if (this.cursorChoiseBoxPointerup) {
      document.removeEventListener("pointerup", this.cursorChoiseBoxPointerup);
      this.cursorChoiseBoxPointerup = null;
    }
    data.cBox.active = false;
    data.cBox.reset();
    data.state.isDrag = false;
    data.state.isClosingLine = false;
    data.state.isDragingLine = null;
    data.state.isDragingRegion = false;
    data.state.dragPoint = null;
    return m.redraw();
  }

  addPathListener(dom, element) {
    var domSite;
    domSite = null;
    //注意这个事件同时控制了填充组和纯填充，且它们是交替显示的
    if (1) {
      dom.addEventListener("pointerdown", (e) => {
        if (e.button !== 0) {
          return;
        }
        if (data.getPresentTool().name !== "bucket") {
          return;
        }
        return e.stopPropagation();
      });
      
      //填色逻辑

      //拖拽纯填充
      return dom.addEventListener("pointerdown", this.pathPointerdown = (e) => {
        var x0, x1, x2, y0, y1, y2;
        domSite = dom.getBoundingClientRect();
        if (e.button !== 0) {
          return;
        }
        if (data.getPresentTool().name !== "cursor") {
          return;
        }
        if (element.type !== "pureFill") {
          return;
        }
        e.stopPropagation();
        x0 = x1 = data.getLocalX(e.clientX, domSite);
        y0 = y1 = data.getLocalY(e.clientY, domSite);
        x2 = y2 = null;
        if (!this.pathPointermove) {
          document.addEventListener("pointermove", this.pathPointermove = (e) => {
            var deltaX, deltaY;
            if (data.activePointers > 1) {
              return;
            }
            e.stopPropagation();
            x2 = data.getLocalX(e.clientX, domSite);
            y2 = data.getLocalY(e.clientY, domSite);
            deltaX = x2 - x1;
            deltaY = y2 - y1;
            data.state.isDrag = Math.abs(x2 - x0) >= 5 / data.globalZoom || Math.abs(y2 - y0) >= 5 / data.globalZoom;
            if (data.state.isDrag && element.isChoised) {
              if (element.prop.fillGroups.length > 0) {
                console.log("激活状态", element.prop.fillGroups[0].getElementsActiveStatus());
                if (element.prop.fillGroups[0].getElementsActiveStatus()) {
                  element.prop.fillGroups.forEach((fillGroup) => {
                    return fillGroup.break();
                  });
                  element.translate({deltaX, deltaY});
                } else {
                  element.prop.fillGroups.forEach((fillGroup) => {
                    return fillGroup.translate({deltaX, deltaY});
                  });
                }
              } else {
                element.translate({deltaX, deltaY});
              }
            }
            m.redraw();
            x1 = x2;
            return y1 = y2;
          });
        }
        if (!this.pathPointercancel) {
          document.addEventListener("pointercancel", this.pathPointercancel = (e) => {
            return this.abort();
          });
        }
        if (!this.pathPointerup) {
          return document.addEventListener("pointerup", this.pathPointerup = (e) => {
            e.stopPropagation();
            if (data.state.isDrag) {
              data.state.isDrag = false;
            } else {
              element.isChoised = true;
            }
            
            //切割
            splitBezier.splitPaper();
            m.redraw();
            this.pathPointermove = document.removeEventListener("pointermove", this.pathPointermove);
            return this.pathPointerup = document.removeEventListener("pointerup", this.pathPointerup);
          });
        }
      });
    }
  }

  addListener(dom) {
    var domSite;
    domSite = null;
    if (1) { // not @cursorPointerdown
      dom.addEventListener("pointerdown", this.cursorPointerdown = (e) => {
        var c, closed, closedLine, closedPureFill, hitCandidates, hitMap, interactiveElement, interactiveRoots, j, len, preBreakFillGroups, ref, ref1, root, sameSitePointsEnd, sameSitePointsStart, selectedControlPointIndex, siteRelationLines, t0, t1, topmostRawHit, topmostRoot, x0, x1, x2, y0, y1, y2;
        domSite = dom.getBoundingClientRect();
        if (e.button !== 0) {
          return;
        }
        if (data.getPresentTool().name !== "cursor") {
          return;
        }
        x0 = x1 = data.getLocalX(e.clientX, domSite);
        y0 = y1 = data.getLocalY(e.clientY, domSite);
        x2 = y2 = null;
        t0 = t1 = Date.now();
        sameSitePointsStart = sameSitePointsEnd = null;
        closed = data.elPaper.getClosedSite({
          x: x1,
          y: y1
        });
        closedLine = data.elPaper.getClosedLine({
          x: x1,
          y: y1
        });
        closedPureFill = data.elPaper.getClosedPureFill({
          x: x1,
          y: y1
        });
        // ======================================================================
        // Z轴层级与编组冒泡 隔离判定区 (开始)
        // ======================================================================

        // 射线交互穿透防护（冒泡提升）
        interactiveElement = (element) => {
          // 新增越界保护：必须在当前隔离作用域之内
          if (data.presentGroup) {
            if (element !== data.presentGroup && !data.presentGroup.hasElementDeep(element)) {
              return null;
            }
          }
          if (!element.prop.parentGroup) {
            return element;
          }
          if (data.presentGroup && element.prop.parentGroup === data.presentGroup) {
            return element;
          }
          return interactiveElement(element.prop.parentGroup);
        };
        siteRelationLines = null;
        preBreakFillGroups = [];
        selectedControlPointIndex = null;
        hitCandidates = [];
        if (closedLine.line && closedLine.dis <= (10 / data.globalZoom) ** 2) {
          hitCandidates.push(closedLine.line);
        }
        data.elPaper.elements.forEach((el) => {
          var box;
          if (el.type === "pureFill") {
            if (data.presentGroup && !(el === data.presentGroup || data.presentGroup.hasElementDeep(el))) {
              return;
            }
            if (el.isPointInRegion(el.globalToLocal({
              x: x1,
              y: y1
            }))) {
              return hitCandidates.push(el);
            }
          } else if (el.type === "text") {
            if (data.presentGroup && !(el === data.presentGroup || data.presentGroup.hasElementDeep(el))) {
              return;
            }
            box = el.getBoundingBox();
            if (x1 >= box.minX && x1 <= box.maxX && y1 >= box.minY && y1 <= box.maxY) {
              return hitCandidates.push(el);
            }
          }
        });
        interactiveRoots = [];
        hitMap = new Map();
        for (j = 0, len = hitCandidates.length; j < len; j++) {
          c = hitCandidates[j];
          root = interactiveElement(c);
          if (root) {
            if (interactiveRoots.indexOf(root) === -1) {
              interactiveRoots.push(root);
              hitMap.set(root, c);
            } else if (c.type === "line") {
              hitMap.set(root, c);
            }
          }
        }
        interactiveRoots.sort((a, b) => {
          if (a.type === "group" && b.type !== "group") {
            return -1;
          }
          if (a.type !== "group" && b.type === "group") {
            return 1;
          }
          return data.elPaper.elements.indexOf(b) - data.elPaper.elements.indexOf(a);
        });
        topmostRoot = interactiveRoots[0];
        topmostRawHit = hitMap.get(topmostRoot);
        // 修正原有的 closedLine 和 closedPureFill，使其强制指向最上层的命中，避免因为独立分支判断导致的事件穿透
        if ((topmostRawHit != null ? topmostRawHit.type : void 0) === "line") {
          if (topmostRawHit !== closedLine.line) {
            closedLine = {
              line: topmostRawHit,
              dis: 0
            };
          }
          closedPureFill = null;
        } else if ((ref = topmostRawHit != null ? topmostRawHit.type : void 0) === "pureFill" || ref === "text") {
          closedPureFill = topmostRawHit;
          closedLine = {
            line: null,
            dis: 2e308
          };
        } else {
          closedPureFill = null;
        }
        
        // ======================================================================
        // Z轴层级与编组冒泡 隔离判定区 (结束)
        // ======================================================================
        preBreakFillGroups = [];
        selectedControlPointIndex = null;
        // 鼠标靠近线检测
        //如果不是拖动状态
        if (!data.state.isDragingLine) {
          if (closedLine.line && closedLine.dis <= (20 / data.globalZoom) ** 2) {
            //全部清除选定状态
            data.elPaper.elements.forEach((element) => {
              return element.isClosed = false;
            });
            closedLine.line.isClosed = true;
            data.state.isClosingLine = true;
          } else {
            if (closedLine.line) {
              closedLine.line.isClosed = false;
            }
            data.state.isClosingLine = false;
          }
        }
        
        // 记录是否按下了已选中的区域，用来提前阻断框选器
        if (closedPureFill && ((ref1 = interactiveElement(closedPureFill)) != null ? ref1.isChoised : void 0)) {
          data.state.isClosingRegion = true;
        } else {
          data.state.isClosingRegion = false;
        }
        m.redraw();
        if (!this.cursorPointermove) {
          document.addEventListener("pointermove", this.cursorPointermove = (e) => {
            var base, base1, base2, base3, closedSite, controlPoints, deltaX, deltaY, distance, i, k, minDistance, mousePoint, nearestIndex, p1Global, p2Global, pointDistance, preSnapSite, projectionPoint, projectionT, ref2, ref3, ref4, ref5, ref6, screenDeltaX, screenDeltaY, selectable, speed, t2;
            if (data.activePointers > 1) {
              return;
            }
            x2 = data.getLocalX(e.clientX, domSite);
            y2 = data.getLocalY(e.clientY, domSite);
            t2 = Date.now();
            deltaX = x2 - x1;
            deltaY = y2 - y1;
            screenDeltaX = deltaX * data.globalZoom;
            screenDeltaY = deltaY * data.globalZoom;
            speed = 100 * ((screenDeltaX ** 2 + screenDeltaY ** 2) / (t2 - t1));
            //closed = data.elPaper.getClosedSite {x:x2,y:y2}
            //closedLine = data.elPaper.getClosedLine {x:x2,y:y2}
            if (Math.abs(x2 - x0) * data.globalZoom >= 5 || Math.abs(y2 - y0) * data.globalZoom >= 5) {
              data.state.isDrag = true;
            }
            
            //如果是在拖线状态（靠近了线且点下）->正在拖动
            if (data.state.isDrag && data.state.isClosingLine) {
              if ((base = data.state).isDragingLine == null) {
                base.isDragingLine = true;
              }
              if (data.state.isDragingLine) {
                selectable = interactiveElement(closedLine.line);
                
                // 如果选定了线条或组等顶级可交互元素 -> 进行平移
                if (selectable && selectable.isChoised && selectable.isActive) {
                  // 平移所有被选中的元素
                  data.elPaper.elements.forEach((element) => {
                    var endClosedSite, globalE, globalS, localDeltaX, localDeltaY, localP1, localP2, startClosedSite, targetGlobalE, targetGlobalS;
                    if (element.type === "line" && element.isChoised) {
                      globalS = element.localToGlobal(element.s());
                      globalE = element.localToGlobal(element.e());
                      targetGlobalS = {
                        x: globalS.x + deltaX,
                        y: globalS.y + deltaY
                      };
                      targetGlobalE = {
                        x: globalE.x + deltaX,
                        y: globalE.y + deltaY
                      };
                      if (speed < 5) {
                        //贴靠坐标计算（传入预期到达的全局坐标）
                        startClosedSite = data.elPaper.getClosedSite(targetGlobalS, [element]);
                        endClosedSite = data.elPaper.getClosedSite(targetGlobalE, [element]);
                        //如果起点靠近某点，平移 修正全局偏移量
                        if (startClosedSite.dis <= (10 / data.globalZoom) ** 2) {
                          deltaX = startClosedSite.site.x - globalS.x;
                          deltaY = startClosedSite.site.y - globalS.y;
                        //如果终点靠近某点，修正全局偏移量
                        } else if (endClosedSite.dis <= (10 / data.globalZoom) ** 2) {
                          deltaX = endClosedSite.site.x - globalE.x;
                          deltaY = endClosedSite.site.y - globalE.y;
                        }
                      }
                      // 将全局增量转换为该元素的局部增量
                      localP1 = element.globalToLocal({
                        x: 0,
                        y: 0
                      });
                      localP2 = element.globalToLocal({
                        x: deltaX,
                        y: deltaY
                      });
                      localDeltaX = localP2.x - localP1.x;
                      localDeltaY = localP2.y - localP1.y;
                      element.translate({
                        deltaX: localDeltaX,
                        deltaY: localDeltaY
                      });
                      //平移线将删除填充组
                      element.prop.fillGroups.forEach((fillGroup) => {
                        return fillGroup.break();
                      });
                    }
                    if (element.type === "pureFill" && element.isChoised) {
                      localP1 = element.globalToLocal({
                        x: 0,
                        y: 0
                      });
                      localP2 = element.globalToLocal({
                        x: deltaX,
                        y: deltaY
                      });
                      element.translate({
                        deltaX: localP2.x - localP1.x,
                        deltaY: localP2.y - localP1.y
                      });
                    }
                    if (element.type === "group" && element.isChoised) {
                      localP1 = element.globalToLocal({
                        x: 0,
                        y: 0
                      });
                      localP2 = element.globalToLocal({
                        x: deltaX,
                        y: deltaY
                      });
                      return element.translate({
                        deltaX: localP2.x - localP1.x,
                        deltaY: localP2.y - localP1.y
                      });
                    }
                  });
                
                // 没有选定，并且当前线是可以被直接交互的（即不属于处于隔离状态外的群组） -> 扭曲线
                } else if (selectable === closedLine.line) {
                  p1Global = closedLine.line.localToGlobal(closedLine.line.s());
                  p2Global = closedLine.line.localToGlobal(closedLine.line.e());
                  if (getDisSq(p1Global, {
                    x: x2,
                    y: y2
                  }) <= (this.endpointR / data.globalZoom) ** 2) {
                    if ((base1 = data.state).dragPoint == null) {
                      base1.dragPoint = "dragP1";
                    }
                  } else if (getDisSq(p2Global, {
                    x: x2,
                    y: y2
                  }) <= (this.endpointR / data.globalZoom) ** 2) {
                    if ((base2 = data.state).dragPoint == null) {
                      base2.dragPoint = "dragP2";
                    }
                  } else {
                    if ((base3 = data.state).dragPoint == null) {
                      base3.dragPoint = "dragMid";
                    }
                  }
                  //拖拽端点
                  closedSite = data.elPaper.getClosedSite({
                    x: x2,
                    y: y2
                  }, [closedLine.line]);
                  switch (data.state.dragPoint) {
                    case "dragP1":
                      if (sameSitePointsStart == null) {
                        sameSitePointsStart = data.elPaper.findSameSitePoints(closedLine.line.s());
                      }
                      //排除当前线上的点
                      if (closedLine.line) {
                        if (siteRelationLines == null) {
                          siteRelationLines = data.elPaper.findSameSiteLines(closedLine.line.s());
                        }
                      }
                      preSnapSite = data.elPaper.getClosedSite({
                        x: x2,
                        y: y2
                      }, siteRelationLines, null);
                      if (sameSitePointsStart != null) {
                        sameSitePointsStart.forEach((point) => {
                          if (preSnapSite.dis <= (this.pointSnapR / data.globalZoom) ** 2) { //吸附到端点
                            point.x = preSnapSite.site.x;
                            return point.y = preSnapSite.site.y;
                          } else {
                            // 直接设置为鼠标位置，而不是累加增量
                            point.x = x2;
                            return point.y = y2;
                          }
                        });
                      }
                      break;
                    case "dragP2":
                      if (sameSitePointsEnd == null) {
                        sameSitePointsEnd = data.elPaper.findSameSitePoints(closedLine.line.e());
                      }
                      if (closedLine.line) {
                        if (siteRelationLines == null) {
                          siteRelationLines = data.elPaper.findSameSiteLines(closedLine.line.e());
                        }
                      }
                      preSnapSite = data.elPaper.getClosedSite({
                        x: x2,
                        y: y2
                      }, siteRelationLines, null);
                      if (sameSitePointsEnd != null) {
                        sameSitePointsEnd.forEach((point) => {
                          if (preSnapSite.dis <= (this.pointSnapR / data.globalZoom) ** 2) { //吸附到端点
                            point.x = preSnapSite.site.x;
                            return point.y = preSnapSite.site.y;
                          } else {
                            // 直接设置为鼠标位置，而不是累加增量
                            point.x = x2;
                            return point.y = y2;
                          }
                        });
                      }
                      break;
                    case "dragMid":
                      if (closedLine.line.getControlPoints().length < 1) {
                        closedLine.line.addControlPoint({
                          x: x2,
                          y: y2
                        });
                      }
                      if (closedLine.line.getControlPoints().length === 1) {
                        closedLine.line.setControlPoint(1, {
                          x: (((ref2 = closedLine.line.getControlPoint(1)) != null ? ref2.x : void 0) || 0) + deltaX,
                          y: (((ref3 = closedLine.line.getControlPoint(1)) != null ? ref3.y : void 0) || 0) + deltaY
                        });
                      }
                      if (closedLine.line.getControlPoints().length === 2) {
                        // 初始化选中的控制点索引
                        if (selectedControlPointIndex == null) {
                          // 使用投影点距离来确定最近的控制点
                          mousePoint = {
                            x: x2,
                            y: y2
                          };
                          
                          // 获取曲线上的投影点参数t
                          projectionT = closedLine.line.getProjectionT(mousePoint);
                          
                          // 获取投影点坐标
                          projectionPoint = closedLine.line.getBezierPoint(projectionT);
                          
                          // 计算投影点到各控制点的距离，选择最近的控制点进行平移
                          controlPoints = closedLine.line.getControlPoints();
                          
                          // 计算距离的辅助函数
                          pointDistance = function(p1, p2) {
                            return Math.pow(p1.x - p2.x, 2) + Math.pow(p1.y - p2.y, 2);
                          };
                          
                          // 找到最近的控制点
                          nearestIndex = 0;
                          minDistance = pointDistance(projectionPoint, controlPoints[0]);
                          for (i = k = 1, ref4 = controlPoints.length; (1 <= ref4 ? k < ref4 : k > ref4); i = 1 <= ref4 ? ++k : --k) {
                            distance = pointDistance(projectionPoint, controlPoints[i]);
                            if (distance < minDistance) {
                              minDistance = distance;
                              nearestIndex = i;
                            }
                          }
                          
                          // 保存选中的控制点索引
                          selectedControlPointIndex = nearestIndex;
                        }
                        
                        // 使用已选中的控制点索引进行平移
                        closedLine.line.setControlPoint(selectedControlPointIndex + 1, { // 控制点索引需要+1，因为getControlPoints()返回的是去掉端点的数组
                          x: closedLine.line.getControlPoint(selectedControlPointIndex + 1).x + deltaX,
                          y: closedLine.line.getControlPoint(selectedControlPointIndex + 1).y + deltaY
                        });
                      }
                  }
                  //更新填充组及向上冒泡更新父级包围盒
                  //closedLine.line.update() # 因为重复了，所以注释掉（下方的 getFillGroups 已经处理了填充组更新）
                  if ((ref5 = closedLine.line.prop.parentGroup) != null) {
                    ref5.update();
                  }
                  data.elPaper.getFillGroups().forEach((fillGroup) => {
                    return fillGroup.update();
                  });
                }
              }
            } else if (data.state.isDrag && closedPureFill && ((ref6 = interactiveElement(closedPureFill)) != null ? ref6.isChoised : void 0)) { //平移填充组改为->平移已被选中的填充组
              data.state.isDragingRegion = true;
              data.elPaper.translateChoisedElements(deltaX, deltaY, preBreakFillGroups);
            }
            x1 = x2;
            y1 = y2;
            t1 = t2;
            return m.redraw();
          });
        }
        if (!this.cursorPointercancel) {
          document.addEventListener("pointercancel", this.cursorPointercancel = (e) => {
            return this.abort();
          });
        }
        if (!this.cursorPointerup) {
          return document.addEventListener("pointerup", this.cursorPointerup = (e) => {
            var isDoubleClick, isDragEnd, now, selectable, x3, y3;
            siteRelationLines = null;
            selectedControlPointIndex = null;
            x3 = data.getLocalX(e.clientX, domSite);
            y3 = data.getLocalY(e.clientY, domSite);
            data.state.dragPoint = null;
            isDragEnd = data.state.isDragingLine || data.state.isDragingRegion;
            data.state.isDrag = false;
            data.state.isDragingRegion = false;
            if (data.state.isDragingLine) {
              data.state.isDragingLine = null;
            } else if (!isDragEnd) {
              now = Date.now();
              selectable = topmostRoot;
              isDoubleClick = false;
              if (selectable && selectable.type === "group") {
                if (now - (this.lastClickTime || 0) < 250 && this.lastClickId === selectable.id) {
                  isDoubleClick = true;
                  data.presentGroup = selectable;
                  data.elPaper.elements.forEach((el) => {
                    return el.isChoised = false;
                  });
                  m.redraw();
                }
              }
              this.lastClickTime = now;
              this.lastClickId = selectable != null ? selectable.id : void 0;
              if (!isDoubleClick) {
                if (!data.RightMenu.data.show) {
                  data.elPaper.elements.forEach((element) => {
                    element.isChoised = false;
                    return element.isClosed = false;
                  });
                }
                if (closedLine.dis <= (10 / data.globalZoom) ** 2) {
                  selectable = interactiveElement(closedLine.line);
                  // 核心豁免逻辑：
                  // 1. 正常线条 (isActive) 允许直接选中。
                  // 2. 如果点击了隐藏线 (!isActive)，本不该选中。但如果该隐藏线属于一个组 (selectable.type is "group")，
                  //    则允许通过这根隐藏线把整个“组”给揪出来选中。
                  // 注：在隔离编辑模式下，隐藏线本身不会冒泡到组，因此它的 type 不是 group，依然无法被单独选中，逻辑严密无死角。
                  if (selectable && (closedLine.line.isActive || selectable.type === "group")) {
                    selectable.isChoised = true;
                  }
                } else {
                  if (closedPureFill) {
                    selectable = interactiveElement(closedPureFill);
                    if (selectable) {
                      selectable.isChoised = true;
                    }
                  }
                }
              }
              data.state.dragPoint = null;
              sameSitePointsStart = sameSitePointsEnd = null;
            }
            if (preBreakFillGroups.length > 0) {
              preBreakFillGroups.forEach((fillGroup) => {
                return fillGroup.break();
              });
            }
            splitBezier.splitPaper();
            data.record("移动或变形");
            x0 = x2;
            y0 = y2;
            m.redraw();
            this.cursorPointermove = document.removeEventListener("pointermove", this.cursorPointermove);
            return this.cursorPointerup = document.removeEventListener("pointerup", this.cursorPointerup);
          });
        }
      });
    }
    //框选器
    if (1) {
      return dom.addEventListener("pointerdown", this.cursorChoiseBoxPointerdown = (e) => {
        var x0, x1, x2, y0, y1, y2;
        domSite = dom.getBoundingClientRect();
        if (e.button !== 0) {
          return;
        }
        if (data.getPresentTool().name !== "cursor") {
          return;
        }
        if (data.state.isDragingLine || data.state.isClosingLine || data.state.isDragingRegion || data.state.isClosingRegion) {
          return;
        }
        x0 = x1 = data.getLocalX(e.clientX, domSite);
        y0 = y1 = data.getLocalY(e.clientY, domSite);
        x2 = y2 = null;
        if (this.cursorChoiseBoxPointermove) {
          document.removeEventListener("pointermove", this.cursorChoiseBoxPointermove);
        }
        document.addEventListener("pointermove", this.cursorChoiseBoxPointermove = (e) => {
          var v;
          if (data.activePointers > 1) {
            return;
          }
          if (data.state.isDragingLine || data.state.isClosingLine || data.state.isDragingRegion || data.state.isClosingRegion) {
            return;
          }
          data.cBox.active = true;
          x2 = data.getLocalX(e.clientX, domSite);
          y2 = data.getLocalY(e.clientY, domSite);
          data.cBox.x = x0;
          data.cBox.y = y0;
          data.cBox.w = x2 - x0;
          data.cBox.h = y2 - y0;
          v = (y2 - y0) / Math.abs(y2 - y0);
          if (Number.isNaN(v)) {
            v = 1;
          }
          if (JSON.stringify(data.pressKeys) === JSON.stringify(["Shift"])) {
            data.cBox.h = Math.abs(data.cBox.w) * v;
          }
          data.cBox.rx = data.cBox.w / 2;
          data.cBox.ry = data.cBox.h / 2;
          m.redraw();
          x1 = x2;
          return y1 = y2;
        });
        if (this.cursorChoiseBoxPointercancel) {
          document.removeEventListener("pointercancel", this.cursorChoiseBoxPointercancel);
        }
        document.addEventListener("pointercancel", this.cursorChoiseBoxPointercancel = (e) => {
          return this.abort();
        });
        if (this.cursorChoiseBoxPointerup) {
          document.removeEventListener("pointerup", this.cursorChoiseBoxPointerup);
        }
        return document.addEventListener("pointerup", this.cursorChoiseBoxPointerup = (e) => {
          var getBoxInLocal, interactiveElement;
          // 框选逻辑：检查哪些曲线在框选区域内
          if (Math.abs(data.cBox.w) > 5 / data.globalZoom || Math.abs(data.cBox.h) > 5 / data.globalZoom) { // 只有当框选区域足够大时才执行选择
            
            // 射线交互穿透防护（冒泡提升）
            interactiveElement = (element) => {
              if (data.presentGroup) {
                if (element !== data.presentGroup && !data.presentGroup.hasElementDeep(element)) {
                  return null;
                }
              }
              if (!element.prop.parentGroup) {
                return element;
              }
              if (data.presentGroup && element.prop.parentGroup === data.presentGroup) {
                return element;
              }
              return interactiveElement(element.prop.parentGroup);
            };
            
            // 框选前如果没有按Shift，需要清空之前的选择状态
            if (JSON.stringify(data.pressKeys) !== JSON.stringify(["Shift"])) {
              data.elPaper.elements.forEach((element) => {
                return element.isChoised = false;
              });
            }
            getBoxInLocal = function(element, cBox) {
              var matrix, maxX, maxY, minX, minY, p1, p2, p3, p4;
              matrix = element.getGlobalMatrix().inverse();
              p1 = element.globalToLocal({
                x: cBox.x,
                y: cBox.y
              }, matrix);
              p2 = element.globalToLocal({
                x: cBox.x + cBox.w,
                y: cBox.y
              }, matrix);
              p3 = element.globalToLocal({
                x: cBox.x,
                y: cBox.y + cBox.h
              }, matrix);
              p4 = element.globalToLocal({
                x: cBox.x + cBox.w,
                y: cBox.y + cBox.h
              }, matrix);
              minX = Math.min(p1.x, p2.x, p3.x, p4.x);
              maxX = Math.max(p1.x, p2.x, p3.x, p4.x);
              minY = Math.min(p1.y, p2.y, p3.y, p4.y);
              maxY = Math.max(p1.y, p2.y, p3.y, p4.y);
              return {
                x: minX,
                y: minY,
                w: maxX - minX,
                h: maxY - minY
              };
            };
            // 遍历所有元素，检查是否在框选区域内
            data.elPaper.elements.forEach((element) => {
              var localBox, selectable;
              if (element.type === "line") {
                localBox = getBoxInLocal(element, data.cBox);
                if (element.isIntersectBox(localBox)) {
                  selectable = interactiveElement(element);
                  if (selectable) {
                    selectable.isChoised = true;
                  }
                }
              }
              if (element.type === "fillGroup") {
                localBox = getBoxInLocal(element, data.cBox);
                if (element.isIntersectBox(localBox)) {
                  selectable = interactiveElement(element.prop.pureFill);
                  if (selectable) {
                    selectable.isChoised = true;
                  }
                }
              }
              if (element.type === "text") {
                localBox = getBoxInLocal(element, data.cBox);
                if (element.isIntersectBox(localBox)) {
                  selectable = interactiveElement(element);
                  if (selectable) {
                    return selectable.isChoised = true;
                  }
                }
              }
            });
            m.redraw(); // 重绘界面以显示选中状态
          }
          if (!this.cursorChoiseBoxPointerDownClick) {
            document.addEventListener("pointerdown", this.cursorChoiseBoxPointerDownClick = (e) => {
              if (e.button !== 0) {
                return;
              }
              data.cBox.x = 0;
              data.cBox.y = 0;
              data.cBox.w = 0;
              data.cBox.h = 0;
              data.cBox.rx = 0;
              data.cBox.ry = 0;
              data.cBox.active = false;
              m.redraw();
              return this.cursorChoiseBoxPointerDownClick = document.removeEventListener("pointerdown", this.cursorChoiseBoxPointerDownClick);
            });
          }
          this.cursorChoiseBoxPointermove = document.removeEventListener("pointermove", this.cursorChoiseBoxPointermove);
          return this.cursorChoiseBoxPointerup = document.removeEventListener("pointerup", this.cursorChoiseBoxPointerup);
        });
      });
    }
  }

};
