// Generated by CoffeeScript 2.7.0
var DripTool;

import data from "../svgEditor_data.js";

export default DripTool = class DripTool {
  constructor() {}

  addListener(dom) {}

  // 依靠 presentTool 劫持，无需画布监听
  triggerDrip() {
    var eyeDropper;
    if (window.EyeDropper) {
      eyeDropper = new window.EyeDropper();
      return eyeDropper.open().then((result) => {
        var color;
        color = result.sRGBHex;
        data.colorTool.setRecentUseColor(color);
        // 吸色完成，自动切回上一个选中的画笔工具
        data.presentTool = data._lastPresentTool || 0;
        return m.redraw();
      }).catch((err) => {
        console.log("吸色被取消:", err);
        data.presentTool = data._lastPresentTool || 0;
        return m.redraw();
      });
    }
  }

};
