// Generated by CoffeeScript 2.7.0
import data from "../svgEditor_data.js";

export default (class {
  constructor() {
    var centerMode;
    this.ellipseToolPointerdown = this.ellipseToolPointermove = this.ellipseToolPointerup = null;
    centerMode = false;
  }

  addListener(dom) {
    var domSite;
    domSite = null;
    return dom.addEventListener("pointerdown", this.ellipseToolPointerdown = (e) => {
      var closedSite, x0, x1, y0, y1;
      domSite = dom.getBoundingClientRect();
      if (data.getPresentTool().name !== "ellipse") {
        return;
      }
      if (e.button !== 0) {
        return;
      }
      x0 = x1 = data.getLocalX(e.clientX, domSite);
      y0 = y1 = data.getLocalY(e.clientY, domSite);
      closedSite = data.elPaper.getClosedSite({
        x: x1,
        y: y1
      });
      if (!this.ellipseToolPointermove) {
        document.addEventListener("pointermove", this.ellipseToolPointermove = function(e) {
          var v, x2, y2;
          if (data.activePointers > 1) {
            return;
          }
          x2 = data.getLocalX(e.clientX, domSite);
          y2 = data.getLocalY(e.clientY, domSite);
          data.cBox.active = true;
          data.cBox.x = x0;
          data.cBox.y = y0;
          if (closedSite.site && closedSite.dis <= 20 ** 2) {
            data.cBox.x = closedSite.site.x;
            data.cBox.y = closedSite.site.y;
          }
          data.cBox.w = x2 - x0;
          data.cBox.h = y2 - y0;
          v = (y2 - y0) / Math.abs(y2 - y0);
          if (Number.isNaN(v)) {
            v = 1;
          }
          if (JSON.stringify(data.pressKeys) === JSON.stringify(["Shift"])) {
            data.cBox.h = Math.abs(data.cBox.w) * v;
          }
          data.cBox.rx = data.cBox.w / 2;
          data.cBox.ry = data.cBox.h / 2;
          if (this.centerMode) {
            data.cBox.x += data.cBox.rx;
            data.cBox.y += data.cBox.ry;
            data.cBox.x -= x2 - x0;
            data.cBox.y -= y2 - y0;
          }
          data.cBox.isEllipse = true;
          data.cBox.stroke = data.colorTool.fgColor;
          data.cBox.strokeWidth = data.colorTool.strokeWidth;
          data.cBox.fill = "none";
          m.redraw();
          x1 = x2;
          return y1 = y2;
        });
      }
      if (!this.ellipseToolPointerup) {
        return document.addEventListener("pointerup", this.ellipseToolPointerup = (e) => {
          // 使用与svgEditor_topBar.coffee相同的方式创建和添加元素
          data.cBox.createElements().forEach((el) => {
            return data.elPaper.add(el);
          });
          // 重置选框
          data.cBox.reset();
          m.redraw();
          data.record("椭圆工具");
          this.ellipseToolPointermove = document.removeEventListener("pointermove", this.ellipseToolPointermove);
          return this.ellipseToolPointerup = document.removeEventListener("pointerup", this.ellipseToolPointerup);
        });
      }
    });
  }

});
