// Generated by CoffeeScript 2.7.0
var EraserTool;

import data from "../svgEditor_data.js";

import tools from "../../tools.js";

import splitBezier from "../tools/splitBezier/main.js";

export default EraserTool = class EraserTool {
  constructor() {}

  addListener(dom) {
    var domSite, eraseAt, hasDeleted, isErasing;
    domSite = dom.getBoundingClientRect();
    isErasing = false;
    hasDeleted = false;
    eraseAt = (x, y) => {
      var closedLine, el, hitCandidates, i, len, rootsToDelete;
      closedLine = data.elPaper.getClosedLine({x, y});
      hitCandidates = [];
      // 碰撞判定距离对齐 cursor
      if (closedLine.line && closedLine.dis <= (10 / data.globalZoom) ** 2) {
        hitCandidates.push(closedLine.line);
      }
      data.elPaper.elements.forEach((el) => {
        var box;
        if (el.type === "pureFill") {
          // isPointInRegion 判定
          if (el.isPointInRegion(el.globalToLocal({x, y}))) {
            return hitCandidates.push(el);
          }
        } else if (el.type === "text") {
          box = el.getBoundingBox();
          if (box && x >= box.minX && x <= box.maxX && y >= box.minY && y <= box.maxY) {
            return hitCandidates.push(el);
          }
        }
      });
      // 过滤限制：只能编辑当前组的非组元素，不能删除组
      rootsToDelete = [];
      for (i = 0, len = hitCandidates.length; i < len; i++) {
        el = hitCandidates[i];
        // 1. 必须是当前活跃组的直系子元素（其 parentGroup 必须等于 data.presentGroup）
        // 2. 图元类型不能是 group（不能删除组）
        if (el.prop.parentGroup === data.presentGroup && el.type !== "group") {
          if (rootsToDelete.indexOf(el) === -1) {
            rootsToDelete.push(el);
          }
        }
      }
      // 批量执行删除操作
      if (rootsToDelete.length > 0) {
        rootsToDelete.forEach((el) => {
          // 使用与右键菜单及 Backspace/Delete 完全一致的物理删除逻辑
          return data.elPaper.removeAndClear(el);
        });
        hasDeleted = true;
        return m.redraw();
      }
    };
    return dom.addEventListener("pointerdown", this.eraserToolPointerdown = (e) => {
      var x1, y1;
      if (data.getPresentTool().name !== "eraser") {
        return;
      }
      e.stopPropagation();
      e.preventDefault();
      isErasing = true;
      hasDeleted = false;
      x1 = data.getLocalX(e.clientX, domSite);
      y1 = data.getLocalY(e.clientY, domSite);
      eraseAt(x1, y1);
      if (!this.eraserToolPointermove) {
        dom.addEventListener("pointermove", this.eraserToolPointermove = (e2) => {
          var x2, y2;
          if (!isErasing) {
            return;
          }
          x2 = data.getLocalX(e2.clientX, domSite);
          y2 = data.getLocalY(e2.clientY, domSite);
          return eraseAt(x2, y2);
        });
      }
      if (!this.eraserToolPointerup) {
        return dom.addEventListener("pointerup", this.eraserToolPointerup = (e3) => {
          isErasing = false;
          this.eraserToolPointermove = dom.removeEventListener("pointermove", this.eraserToolPointermove);
          this.eraserToolPointerup = dom.removeEventListener("pointerup", this.eraserToolPointerup);
          if (hasDeleted) {
            splitBezier.splitPaper();
            data.record("橡皮擦擦除");
            return m.redraw();
          }
        });
      }
    });
  }

};
