// Generated by CoffeeScript 2.7.0
var inkBottleTool;

import data from "../svgEditor_data.js";

import PureFill from "../svgEditor_pureFill.js";

import FillGroup from "../svgEditor_fillGroup.js";

import pointInRegions from "../tools/pointInRegions.js";

import Element from "../svgEditor_element.js";

export default inkBottleTool = class inkBottleTool {
  constructor() {}

  fill(element) {
    var childRegions, newFillGroup, newLines;
    if (element.type === "pureFill") {
      if (element.prop.fillGroups.length <= 0) {
        newLines = element.prop.elements.map((el) => {
          var findEl, newEl, pointsStr1;
          //搜索是否图中已经有线
          pointsStr1 = el.prop.points.map((point) => {
            return `${point.x},${point.y}`;
          });
          findEl = data.elPaper.getLines().find((line) => {
            var pointsStr2;
            if (line.prop.parentGroup !== element.prop.parentGroup) {
              return false;
            }
            pointsStr2 = line.prop.points.map((point) => {
              return `${point.x},${point.y}`;
            });
            return JSON.stringify(pointsStr1) === JSON.stringify(pointsStr2);
          });
          if (findEl) {
            return findEl;
          } else {
            newEl = new Element({
              prop: {
                parentGroup: element.prop.parentGroup,
                points: JSON.parse(JSON.stringify(el.prop.points))
              },
              isActive: false
            });
            data.elPaper.add(newEl);
            return newEl;
          }
        });
        // 复制子区域元素
        childRegions = element.prop.childRegions.map((childRegion) => {
          return childRegion.map((el) => {
            var findEl, newEl, pointsStr1;
            //搜索是否图中已经有线
            pointsStr1 = el.prop.points.map((point) => {
              return `${point.x},${point.y}`;
            });
            findEl = data.elPaper.getLines().find((line) => {
              var pointsStr2;
              if (line.prop.parentGroup !== element.prop.parentGroup) {
                return false;
              }
              pointsStr2 = line.prop.points.map((point) => {
                return `${point.x},${point.y}`;
              });
              return JSON.stringify(pointsStr1) === JSON.stringify(pointsStr2);
            });
            if (findEl) {
              return findEl;
            } else {
              newEl = new Element({
                prop: {
                  parentGroup: element.prop.parentGroup,
                  points: JSON.parse(JSON.stringify(el.prop.points))
                },
                isActive: false
              });
              data.elPaper.add(newEl);
              return newEl;
            }
          });
        });
        newFillGroup = new FillGroup({
          prop: {
            pureFill: element,
            elements: newLines,
            childRegions: childRegions,
            parentGroup: element.prop.parentGroup
          }
        });
        return data.elPaper.elements.unshift(newFillGroup);
      } else {
        return element.prop.fillGroups.forEach((fillGroup) => {
          return this.fill(fillGroup);
        });
      }
    } else if (element.type === "fillGroup") {
      element.prop.elements.forEach((ele) => {
        return this.fill(ele);
      });
      return element.prop.childRegions.forEach((region) => {
        return region.forEach((ele) => {
          return this.fill(ele);
        });
      });
    } else if (element.type === "line") {
      element.isActive = true;
      return element.prop.stroke = data.colorTool.fgColor;
    }
  }

  addListener(dom) {
    var domSite;
    domSite = null;
    if (1) { //not @inkBottlePointerdown
      return dom.addEventListener("pointerdown", this.inkBottlePointerdown = (e) => {
        var closedLine, closedPureFill, x0, x1, y0, y1;
        domSite = dom.getBoundingClientRect();
        if (data.getPresentTool().name !== "inkBottle") {
          return;
        }
        x0 = x1 = data.getLocalX(e.clientX, domSite);
        y0 = y1 = data.getLocalY(e.clientY, domSite);
        closedPureFill = data.elPaper.getClosedPureFill({
          x: x1,
          y: y1
        });
        closedLine = data.elPaper.getClosedLine({
          x: x1,
          y: y1
        });
        if (!this.inkBottlePointerUp) {
          return document.addEventListener("pointerup", this.inkBottlePointerUp = (e) => {
            var p1, p2, tolerance, x3, y3;
            x3 = data.getLocalX(e.clientX, domSite);
            y3 = data.getLocalY(e.clientY, domSite);
            // 将全局 20 像素容差转换为局部空间容差
            tolerance = 20 / data.globalZoom;
            if (data.presentGroup) {
              p1 = data.presentGroup.globalToLocal({
                x: 0,
                y: 0
              });
              p2 = data.presentGroup.globalToLocal({
                x: tolerance,
                y: 0
              });
              tolerance = Math.sqrt((p2.x - p1.x) ** 2 + (p2.y - p1.y) ** 2);
            }
            if (closedLine.line && closedLine.dis <= tolerance ** 2 && closedLine.line.prop.parentGroup === data.presentGroup) {
              this.fill(closedLine.line);
            } else {
              if (closedPureFill && closedPureFill.prop.parentGroup === data.presentGroup) {
                this.fill(closedPureFill);
              }
              data.preFulls = [];
            }
            m.redraw();
            data.record("墨水瓶描边");
            return this.inkBottlePointerUp = document.removeEventListener("pointerup", this.inkBottlePointerUp);
          });
        }
      });
    }
  }

  addPathListener(dom, element) {
    return dom.addEventListener("click", () => {
      if (data.getPresentTool().name !== "inkBottle") {
        return;
      }
      if (element.prop.parentGroup !== data.presentGroup) {
        return;
      }
      if (element.type !== "pureFill" && element.type !== "line") {
        return;
      }
      this.fill(element);
      return m.redraw();
    });
  }

};
