// Generated by CoffeeScript 2.7.0
var LineTool;

import data from "../svgEditor_data.js";

import Element from "../svgEditor_element.js";

import Paper from "../svgEditor_paper.js";

import splitBezier from "../tools/splitBezier/main.js";

export default LineTool = class LineTool {
  consturctor() {
    this.drawPointerdown = null;
    this.drawPointermove = null;
    return this.drawPointerup = null;
  }

  addListener(dom) {
    //画笔
    if (1) { //not @drawPointerdown
      return dom.addEventListener("pointerdown", this.drawPointerdown = (e) => {
        var closed, domSite, newLine, startSite, t0, t1, x1, y1;
        domSite = dom.getBoundingClientRect();
        if (e.button !== 0) {
          return;
        }
        if (data.getPresentTool().name !== "line") {
          return;
        }
        x1 = data.getLocalX(e.clientX, domSite);
        y1 = data.getLocalY(e.clientY, domSite);
        t0 = t1 = Date.now();
        closed = data.elPaper.getClosedSite({
          x: x1,
          y: y1
        });
        if (closed.dis <= data.cursorTool.pointSnapR ** 2) {
          startSite = closed.site;
        } else {
          startSite = {
            x: x1,
            y: y1
          };
        }
        data.state.isDrawingLine = true;
        newLine = new Element({
          type: "line",
          prop: {
            parentGroup: data.presentGroup,
            points: [{...startSite}, {...startSite}]
          }
        });
        data.elPaper.add(newLine);
        if (!this.drawPointermove) {
          document.addEventListener("pointermove", this.drawPointermove = (e) => {
            var angle, deltaX, deltaY, distance, dx, dy, endSite, segment, segmentIndex, speed, t2, x2, y2;
            if (data.activePointers > 1) {
              return;
            }
            x2 = data.getLocalX(e.clientX, domSite);
            y2 = data.getLocalY(e.clientY, domSite);
            deltaX = x2 - x1;
            deltaY = y2 - y1;
            t2 = Date.now();
            speed = 100 * ((deltaX ** 2 + deltaY ** 2) / (t2 - t1));
            closed = data.elPaper.getClosedSite({
              x: x2,
              y: y2
            }, [newLine], null, speed);
            if (closed.site && (closed.dis <= data.cursorTool.pointSnapR ** 2)) {
              endSite = closed.site;
            } else {
              endSite = {
                x: x2,
                y: y2
              };
              if (JSON.stringify(data.pressKeys) === JSON.stringify(["Shift"])) {
                // 计算相对于起点的偏移
                dx = x2 - x1;
                dy = y2 - y1;
                
                // 计算角度（弧度）
                angle = Math.atan2(dy, dx);
                
                // 将角度转换为 0-2π 范围
                if (angle < 0) {
                  angle += 2 * Math.PI;
                }
                
                // 将圆周8等分，每份45度（π/4 弧度）
                segment = Math.PI / 4;
                
                // 确定当前处于哪个段
                segmentIndex = Math.round(angle / segment);
                
                // 标准化 segmentIndex 到 0-7 范围
                segmentIndex = segmentIndex % 8;
                
                    // 根据段索引确定方向
                switch (segmentIndex) {
                  // 右
                  case 0:
                    endSite = {
                      x: x2,
                      y: y1
                    };
                    break;
                  // 右下
                  case 1:
                    distance = (Math.abs(dx) + Math.abs(dy)) / 2;
                    endSite = {
                      x: x1 + distance,
                      y: y1 + distance
                    };
                    break;
                  // 下
                  case 2:
                    endSite = {
                      x: x1,
                      y: y2
                    };
                    break;
                  // 左下
                  case 3:
                    distance = (Math.abs(dx) + Math.abs(dy)) / 2;
                    endSite = {
                      x: x1 - distance,
                      y: y1 + distance
                    };
                    break;
                  // 左
                  case 4:
                    endSite = {
                      x: x2,
                      y: y1
                    };
                    break;
                  // 左上
                  case 5:
                    distance = (Math.abs(dx) + Math.abs(dy)) / 2;
                    endSite = {
                      x: x1 - distance,
                      y: y1 - distance
                    };
                    break;
                  // 上
                  case 6:
                    endSite = {
                      x: x1,
                      y: y2
                    };
                    break;
                  // 右上
                  case 7:
                    distance = (Math.abs(dx) + Math.abs(dy)) / 2;
                    endSite = {
                      x: x1 + distance,
                      y: y1 - distance
                    };
                }
              }
            }
            newLine.setE(endSite);
            return m.redraw();
          });
        }
        if (!this.drawPointerup) {
          return document.addEventListener("pointerup", this.drawPointerup = (e) => {
            if (newLine.getStartEndDisSquare() < 5 ** 2) {
              data.elPaper.remove(newLine);
            }
            splitBezier.splitPaper();
            data.state.isDrawingLine = false;
            data.record("线条工具");
            this.drawPointermove = document.removeEventListener("pointermove", this.drawPointermove);
            this.drawPointerup = document.removeEventListener("pointerup", this.drawPointerup);
            return m.redraw();
          });
        }
      });
    }
  }

};
