// Generated by CoffeeScript 2.7.0
import data from "../svgEditor_data.js";

export default (class {
  constructor() {
    this.rectToolPointerdown = this.rectToolPointermove = this.rectToolPointerup = null;
    this.centerMode = false;
  }

  abort() {
    if (this.rectToolPointermove) {
      document.removeEventListener("pointermove", this.rectToolPointermove);
      this.rectToolPointermove = null;
    }
    if (this.rectToolPointerup) {
      document.removeEventListener("pointerup", this.rectToolPointerup);
      this.rectToolPointerup = null;
    }
    if (this.rectToolPointercancel) {
      document.removeEventListener("pointercancel", this.rectToolPointercancel);
      this.rectToolPointercancel = null;
    }
    data.cBox.reset();
    return m.redraw();
  }

  addListener(dom) {
    var domSite;
    domSite = null;
    return dom.addEventListener("pointerdown", this.rectToolPointerdown = (e) => {
      var closedSite, x0, x1, y0, y1;
      domSite = dom.getBoundingClientRect();
      if (data.getPresentTool().name !== "rect") {
        return;
      }
      if (e.button !== 0) {
        return;
      }
      x0 = x1 = data.getLocalX(e.clientX, domSite);
      y0 = y1 = data.getLocalY(e.clientY, domSite);
      closedSite = data.elPaper.getClosedSite({
        x: x1,
        y: y1
      });
      if (!this.rectToolPointermove) {
        document.addEventListener("pointermove", this.rectToolPointermove = function(e) {
          var v, x2, y2;
          if (data.activePointers > 1) {
            return;
          }
          x2 = data.getLocalX(e.clientX, domSite);
          y2 = data.getLocalY(e.clientY, domSite);
          data.cBox.active = true;
          data.cBox.x = x0;
          data.cBox.y = y0;
          if (closedSite.site && closedSite.dis <= 20 ** 2) {
            data.cBox.x = closedSite.site.x;
            data.cBox.y = closedSite.site.y;
          }
          data.cBox.w = x2 - x0;
          data.cBox.h = y2 - y0;
          v = (y2 - y0) / Math.abs(y2 - y0);
          if (Number.isNaN(v)) {
            v = 1;
          }
          if (JSON.stringify(data.pressKeys) === JSON.stringify(["Shift"])) {
            data.cBox.h = Math.abs(data.cBox.w) * v;
          }
          data.cBox.rx = 0; // 矩形框不设置圆角
          data.cBox.ry = 0;
          data.cBox.isEllipse = false;
          data.cBox.stroke = data.colorTool.fgColor;
          data.cBox.strokeWidth = data.colorTool.strokeWidth;
          data.cBox.fill = "none";
          m.redraw();
          x1 = x2;
          return y1 = y2;
        });
      }
      if (!this.rectToolPointerup) {
        document.addEventListener("pointercancel", this.rectToolPointercancel = (e) => {
          return this.abort();
        });
        return document.addEventListener("pointerup", this.rectToolPointerup = (e) => {
          // 使用与svgEditor_topBar.coffee相同的方式创建和添加元素
          data.cBox.createElements().forEach((el) => {
            return data.elPaper.add(el);
          });
          // 重置选框
          data.cBox.reset();
          m.redraw();
          data.record("矩形工具");
          document.removeEventListener("pointermove", this.rectToolPointermove);
          document.removeEventListener("pointerup", this.rectToolPointerup);
          document.removeEventListener("pointercancel", this.rectToolPointercancel);
          return this.rectToolPointermove = this.rectToolPointerup = this.rectToolPointercancel = null;
        });
      }
    });
  }

});
