// Generated by CoffeeScript 2.7.0
export default function(x, y, sx, sy, ex, ey) {
  var p, t, v, w;
  v = {
    x: ex - sx,
    y: ey - sy
  };
  w = {
    x: x - sx,
    y: y - sy
  };
  t = ((v.x * w.x) + (v.y * w.y)) / (v.x ** 2 + v.y ** 2);
  p = t <= 0 ? {
    x: sx,
    y: sy
  } : t >= 1 ? {
    x: ex,
    y: ey
  } : {
    x: sx + t * v.x,
    y: sy + t * v.y
  };
  return (x - p.x) ** 2 + (y - p.y) ** 2;
};
