// Generated by CoffeeScript 2.7.0
var State, StateMachine,
  hasProp = {}.hasOwnProperty;

State = class {
  constructor(state) {
    var key, value;
    this.nexts = [];
    this.condition = function() {
      return true;
    };
    this.actions = [];
    for (key in state) {
      if (!hasProp.call(state, key)) continue;
      value = state[key];
      this[key] = value;
    }
  }

  addNext(state) {
    if (state instanceof State) {
      return this.nexts.push(state);
    } else {
      throw new Error("state不是State类的实例");
    }
  }

  addNexts(states) {
    return states.forEach((state) => {
      return this.addNext(state);
    });
  }

};

StateMachine = class {
  constructor(states) {
    var fn;
    this.presentState = null;
    this.states = {};
    this.methods = {};
    this.context = {};
    fn = (states, dealString) => {
      var index, results, state;
      if (!states) {
        return;
      }
      results = [];
      for (index in states) {
        if (!hasProp.call(states, index)) continue;
        state = states[index];
        results.push(((state) => {
          var ref;
          console.log(state);
          if (((ref = this.states[state.name]) != null ? ref.name : void 0) === state.name) {
            return;
          }
          if (state.nexts) {
            fn(state.nexts);
          }
          return this.states[state.name] = new State(state);
        })(state));
      }
      return results;
    };
    fn(states);
  }

  addState(state) {
    var action, i, len, newState, ref;
    newState = this.states[state.name] = new State(state);
    ref = newState.actions;
    for (i = 0, len = ref.length; i < len; i++) {
      action = ref[i];
      ((action) => {
        return this.methods[action.name] = action;
      })(action);
    }
    return newState;
  }

  addMethod(name, method) {
    return this.methods[name] = method;
  }

  async chState(stateName) {
    var action, i, len, nextState, ref, results;
    if (!this.presentState) {
      this.presentState = this.states[stateName];
      return;
    }
    console.log(this.presentState);
    nextState = this.presentState.nexts.find((nextState) => {
      return nextState.name === stateName;
    });
    if (nextState && nextState.condition()) {
      this.presentState = nextState;
    }
    ref = this.presentState.actions;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      action = ref[i];
      results.push((await (async(action) => {
        return (await action.do(this));
      })(action)));
    }
    return results;
  }

};

export default StateMachine;

export {
  StateMachine,
  State
};
