// Generated by CoffeeScript 2.7.0
export default (elements) => {
  var allPoints, count, element, i, j, key, len, len1, point, pointCounts, x;
  allPoints = [];
  for (i = 0, len = elements.length; i < len; i++) {
    element = elements[i];
    allPoints.push({
      x: element.s().x,
      y: element.s().y
    });
    allPoints.push({
      x: element.e().x,
      y: element.e().y
    });
  }
  
  // 统计每个点出现的次数
  pointCounts = new Map();
  for (j = 0, len1 = allPoints.length; j < len1; j++) {
    point = allPoints[j];
    key = `${point.x},${point.y}`;
    count = pointCounts.get(key) || 0;
    pointCounts.set(key, count + 1);
  }

  // 在封闭区域中，每个点应该出现偶数次（通常是2次）
  for (x of pointCounts) {
    [key, count] = x;
    if (count % 2 !== 0) {
      return false;
    }
  }
  return true;
};
