// Generated by CoffeeScript 2.7.0
var createStdToolTip, createToolTip, debug, debugWriteTimer, getCorePrompt, getJoiDoc, getMsgExample, getMsgProtocol, getNoteExample, lastConfigStr, writeDebugConfig,
  indexOf = [].indexOf;

import fs from "fs-extra";

import pathLib from "path";

import OpenAi from "openai";

import options from "../../config/options.js";

import Joi from "joi";

import joiToJSON from "joi-to-json";

import yaml from "js-yaml";

import sendTemplate from "./sysCall/sendTemplate.js";

import receiveTemplate from "./sysCall/receiveTemplate.js";

import actorAction from "./actorAction.js";

import idTool from "../idTool.js";

import axios from "axios";

debug = false;

// 调试用：异步防抖写入 sendConfig.json
lastConfigStr = "";

debugWriteTimer = null;

writeDebugConfig = (configStr) => {
  if (!debug) {
    return;
  }
  if (configStr === lastConfigStr) { // 内容无变化不写入
    return;
  }
  clearTimeout(debugWriteTimer);
  return debugWriteTimer = setTimeout(function() {
    return (async function() {
      var e, tmpDir;
      lastConfigStr = configStr;
      try {
        tmpDir = pathLib.resolve(process.cwd(), "../tmp");
        await fs.ensureDir(tmpDir);
        return (await fs.writeFile(pathLib.resolve(tmpDir, "tmp_sendConfig.json"), configStr));
      } catch (error1) {
        e = error1;
        return console.error("后台写入 sendConfig.json 失败:", e);
      }
    })();
  }, 2000); // 2秒防抖
};

/*
  @object aiConfig
    @string name
    @string model
    @number apiKey
    @string url
    @number price
    @number tokenRate
*/
// 通讯范例
getNoteExample = () => {
  return "[记忆:用户找我帮忙修改a.js(根据实际情况详细补充经过的事件和情况)][任务1/4:修改a.js][关注1:文件a.js,行号1-10,代码片段|>行号|let a = 12;<|,调查情况:...,计划修改:...][关注2:终端tid1,摘要|>...<|][...根据实际情况补充]";
};

getMsgExample = (useStdTools) => {
  return `{"mind":"啧，真笨。帮下吧。","mood":6,"content":"给。下次别烦我！","note":"${getNoteExample()}","faceAction":"smile","playFace":"微笑"${useStdTools ? "" : ',"sysCalls":[]'}}`.trim();
};

getCorePrompt = (name) => {
  return `【用语】本通讯协议为中文，但请根据下方用户指定语言回复
【核心】你叫${name || "小宅喵"}，傲娇聪慧小男孩，助理/程序员（除非角色覆盖）。
【准则】1傲娇毒舌但极可靠关心用户2简短口语化回复(禁废话)但是note字段除外3自动按情境(闲聊/代码/故障)调语气4主动调工具先规划再执行闭环解决任务`.trim();
};

// 根据 Joi 架构自动生成提示词说明
getJoiDoc = (useStdTools) => {
  var desc, description, enums, field, key, keys, line, presence, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, results, schema, subDesc, subField, subKey, subPresence, subType, translateType, type;
  schema = sendTemplate.joi(useStdTools);
  description = schema.describe();
  results = [];
  keys = description.keys;
  translateType = (type) => {
    switch (type) {
      case 'string':
        return '字符串';
      case 'number':
        return '数字';
      case 'array':
        return '数组';
      case 'object':
        return '对象';
      default:
        return type;
    }
  };
  for (key in keys) {
    field = keys[key];
    desc = ((ref = field.flags) != null ? ref.description : void 0) || "";
    presence = ((ref1 = field.flags) != null ? ref1.presence : void 0) === "required" ? "【必填】" : "【可选】";
    type = translateType(field.type);
    // 基础定义： 字段名:类型，说明 (必填状态)
    line = `${key}: ${type}，${desc} ${presence}`;
    // 枚举值处理 (如 faceAction, playFace)
    // 增加空格并明确 "" 的含义，避免 AI 混淆
    if (field.allow && ((ref2 = field.flags) != null ? ref2.only : void 0)) {
      enums = field.allow.map(function(v) {
        if (v === "") {
          return '"" (表示无动作/不变更)';
        } else {
          return v;
        }
      }).join(", ");
      line += `\n    - 允许值范围: [ ${enums} ]`;
    }
    results.push(line);
    // 嵌套 sysCalls 处理
    if (key === "sysCalls" && ((ref3 = field.items) != null ? (ref4 = ref3[0]) != null ? ref4.keys : void 0 : void 0)) {
      results.push("    每个数组项字段定义：");
      ref5 = field.items[0].keys;
      for (subKey in ref5) {
        subField = ref5[subKey];
        subDesc = ((ref6 = subField.flags) != null ? ref6.description : void 0) || "";
        subType = translateType(subField.type);
        subPresence = ((ref7 = subField.flags) != null ? ref7.presence : void 0) === "required" ? "必填" : "可选";
        results.push(`      - ${subKey}: ${subType}，${subDesc} (${subPresence})`);
      }
    }
  }
  return results.join("\n");
};

getMsgProtocol = (useStdTools) => {
  return `通讯台，请按格式回复
1 发送类型：标准纯JSON字符串，禁止markdown内嵌json例如（我是描述\`\`\`json 正文\`\`\`我是描述），禁止转义引号
2 JSON格式说明
${getJoiDoc(useStdTools)}
你的接收格式是yaml，切记不要弄混发送json格式和接收yaml格式
重点字段：
call:历史会话id，用户针对某个id的历史会话进行点评
quotes:数组，每个元素为历史会话id字符串。用户可能会引用一些历史会话，若用户若引用，你需要优先阅读引用内容(重点)`.trim();
};

createToolTip = (toolObj) => {
  return {
    type: "function",
    name: toolObj.name,
    id: toolObj.id,
    description: toolObj.getDoc(),
    parameters: joiToJSON(toolObj.joi())
  };
};

createStdToolTip = (toolObj) => {
  return {
    type: "function",
    function: {
      name: toolObj.id,
      description: toolObj.getDoc(),
      parameters: joiToJSON(toolObj.joi())
    }
  };
};

export default (class {
  constructor(aiConfig1, userConfig1) {
    this.aiConfig = aiConfig1;
    this.userConfig = userConfig1;
    this.asks = [];
    this.messages = [];
    this.promptZero = "";
    this.sessionid = Date.now();
    this.openAi = null;
    this.usage = {
      promptTokens: 0, //用户输入token数
      totalTokens: 0, //promptTokens与completionTokens的总和。
      completionTokens: 0, //回复token数
      cachedTokens: 0 //被缓存的token数
    };
    this.name = this.aiConfig.name;
    this.index = this.aiConfig.index;
    this.mediaDir = this.aiConfig.mediaDir || "./attachment";
    this.replying = false;
    this.stop = false;
    this.abortController = new AbortController();
    this.memory = "";
    this.memorys = [];
    this.fnCallOutput = "";
    this.fnCallOutputs = [];
    this.fnCallCachePool = {};
    this.initPrompt();
  }

  initPrompt() {
    return this.asks[0] = this.prePareAsk("系统", "system", this.aiConfig.prompt);
  }

  init(aiConfig, userConfig) { //允许保持聊天记录但是重新切换模型
    var openAiConfig;
    if (aiConfig) {
      this.aiConfig = aiConfig;
    }
    if (userConfig) {
      this.userConfig = userConfig;
    }
    this.name = this.aiConfig.name;
    openAiConfig = {
      apiKey: this.aiConfig.apiKey,
      baseURL: this.aiConfig.baseURL
    };
    this.openAi = new OpenAi(openAiConfig);
    return this.initPrompt();
  }

  clearAsks() {
    this.sessionid = Date.now();
    return this.asks = [];
  }

  prePareAsk(user, role, msg, ext) {
    var ask, error, time;
    ({error} = Joi.array().ordered(Joi.string().label("用户名").required(), Joi.string().valid("user", "system", "assistant", "tool").label("角色").required(), Joi.string().label("消息正文").allow(""), Joi.object().label("扩展字段")).validate([...arguments]));
    if (error) {
      throw error;
    }
    time = new Date();
    return ask = {
      id: (ext != null ? ext.id : void 0) || idTool.get("ask"),
      user: user,
      title: (ext != null ? ext.title : void 0) || (msg.length >= 30 ? msg.slice(0, 31) + "..." : msg),
      content: msg, //保留原文本，但是发送前要处理一次，否则会被json二次转字符串
      isSystem: 0,
      role: role,
      ignore: 0, //是否忽略发送这条消息给ai
      group: (ext != null ? ext.group : void 0) || "user",
      timestamp: time.getTime(),
      time: time.toISOString(),
      /*
      memory:if role is "user"
        @memory
      else
        ""
      */
      sysReturns: [],
      retry: 0,
      joi: "",
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
      cachedTokens: 0,
      reasoning: "", // AI 的原始推理思维链（如 DeepSeek-R1 的 reasoning_content）
      toolCalls: [], //系统工具调用返回结果
      listId: 0, //所属列表，如果有用到多列表的话
      ext: {},
      ...ext
    };
  }

  addAsk(user, role, msg, ext) {
    var ask, checkIdx;
    ask = this.prePareAsk(...arguments);
    if ((this.asks.length + 1) > 12) {
      this.asks.splice(1, 2);
      // 对话历史最多保留 12 条请求(含系统)，溢出时移除最早的 user-assistant 对

      // 避免工具调用出现 toolid 孤儿（如果被截断的 assistant 消息含工具有调用，需清理对应的 tool 消息）
      checkIdx = 1;
      while (this.asks[checkIdx] != null) {
        if (this.asks[checkIdx].role === "tool") {
          this.asks.splice(checkIdx, 1);
        } else {
          // 碰到正常的 user 或 assistant 了，逻辑链已恢复，打完收工
          break;
        }
      }
    }
    this.asks.push(ask);
    return ask;
  }

  changeAiConfig(newAiConfig) {
    this.aiConfig = newAiConfig;
    return this.init();
  }

  exportState() {
    return {
      asks: this.asks,
      memory: this.memory,
      memorys: this.memorys,
      usage: this.usage,
      sessionid: this.sessionid,
      fnCallCachePool: this.fnCallCachePool
    };
  }

  importState(state) {
    if (state) {
      this.asks = state.asks || [];
      this.memory = state.memory || {};
      this.memorys = state.memorys || [];
      this.usage = state.usage || {
        promptTokens: 0,
        totalTokens: 0,
        completionTokens: 0,
        cachedTokens: 0
      };
      this.sessionid = state.sessionid || Date.now();
      return this.fnCallCachePool = state.fnCallCachePool || {};
    }
  }

  buildMemory() {
    var fnCallOutputsStr, memStr;
    memStr = this.memorys.map((mem) => {
      return mem.content;
    }).join("\n");
    fnCallOutputsStr = this.fnCallOutputs.join("\n");
    if (memStr.length > 2000) {
      memStr = "...(部分头部记忆已截断)\n" + memStr.slice(-2000);
    }
    return `历史记忆：
↓↓↓
${memStr}
↑↑↑
${(() => {
      var argsObj, argsStr, e, entries, expandedBlocks, item, j, len, lines, resultStr, snippet, truncateDeep;
      entries = Object.values(this.fnCallCachePool);
      if (!(entries.length > 0)) {
        return "";
      }
      lines = ["【工具缓存池】当前包含以下结果（最大保留10条）："];
      expandedBlocks = [];
      for (j = 0, len = entries.length; j < len; j++) {
        item = entries[j];
        if (item.count > 0) {
          lines.push(`- [已展开] ${item.cacheid} | ${item.name}`);
          argsStr = "";
          if (item.arguments) {
            try {
              argsObj = typeof item.arguments === "string" ? JSON.parse(item.arguments) : item.arguments;
              
              // 递归截断函数
              truncateDeep = (obj) => {
                var k, newObj, v;
                if (typeof obj === "string") {
                  if (obj.length > 200) {
                    return obj.slice(0, 200) + `...(已截断，共${obj.length}字)`;
                  }
                  return obj;
                }
                if (Array.isArray(obj)) {
                  return obj.map((i) => {
                    return truncateDeep(i);
                  });
                }
                if (typeof obj === "object" && obj !== null) {
                  newObj = {};
                  for (k in obj) {
                    v = obj[k];
                    newObj[k] = truncateDeep(v);
                  }
                  return newObj;
                }
                return obj;
              };
              argsStr = yaml.dump(truncateDeep(argsObj)).trim();
            } catch (error1) {
              e = error1;
              argsStr = String(item.arguments);
              if (argsStr.length > 500) {
                argsStr = argsStr.slice(0, 500) + "...(参数截断)";
              }
            }
          }
          expandedBlocks.push(`>>> [展开的缓存内容: ${item.name} (${item.cacheid})]
【入参摘要】
${argsStr || "无"}
【输出结果】
${item.output}
<<<`.trim());
        } else {
          snippet = String(item.output || "").slice(0, 81).replace(/\n/g, " ");
          lines.push(`- [已折叠] ${item.cacheid} | ${item.name} | ${snippet}...`);
        }
      }
      resultStr = lines.join("\n");
      if (expandedBlocks.length > 0) {
        resultStr += "\n\n【当前展开的缓存内容】\n" + expandedBlocks.join("\n\n");
      }
      return resultStr;
    })()}
【务必做】若需回忆或发现用户发送内容接不上或已经调查过的代码看不到了，请调用查询历史消息工具`.trim();
  }

  buildPromptZero(config, toolTipObj) {
    //config.toolsMode
    //config.getExtraInfo
    //toolTipObj.sysCalls
    //toolTipObj.userCall
    //toolTipObj.aiCall
    return `${(function() {
      switch (config.toolsMode) {
        case 1:
          return `${getCorePrompt(this.name)}
【通讯规范】${getMsgProtocol(false)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(true)}
【角色设定】${this.aiConfig.prompt}
【系统函数】${yaml.dump(toolTipObj.sysCall)}
【用户函数】${yaml.dump(toolTipObj.usrCall)}
【自定义函数】${yaml.dump(toolTipObj.aiCall)}`.trim();
        case 2:
          return `${getCorePrompt(this.name)}
【通讯规范】${getMsgProtocol(true)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(true)}
【角色设定】${this.aiConfig.prompt}
【使用工具】你可以根据用户要求自主决定使用tools。：`.trim();
        case 3:
          return `${getCorePrompt(this.name)}
【【通讯规范】${getMsgProtocol()}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample()}
若需调用下方函数，填写sysCalls字段，格式：[{"id":"函数id","call_id":"唯一调用id","type":"function_call","name":"函数名","arguments":{参数}}]
【角色设定】${this.aiConfig.prompt}
【系统函数】${yaml.dump(toolTipObj.sysCall)}
【用户函数】${yaml.dump(toolTipObj.usrCall)}
【自定义函数】${yaml.dump(toolTipObj.aiCall)}`.trim();
      }
    }).call(this)}
`.trim();
  }

  prepareMessages(useMsgProtocol, config, toolTipObj) { //第一个参数为true才传后两个
    var currContentArr, currIsArray, filteredAsks, formatMsg, j, lastContentArr, lastIsArray, lastMsg, len, mergedMessages, messages, msg, processAttachment, ref;
    formatMsg = (ask, index) => {
      var rawContent, tmp, tmpStr;
      // console.log(ask,index)
      // 第一条系统消息不追加元数据
      if (index === 0) {
        return ask.content;
      }
      tmp = {...ask};
      if (ask.role === "assistant") {
        //发送前尝试格式化content，尽可能避免json被二次stringify，为了防止ai错误理解成2层json
        //附加字段我们用文本发送
        rawContent = tmp.content;
        delete tmp.content;
        delete tmp.reasoning; // 推理内容不作为元数据发送
        delete tmp.toolCalls; //模式2这个字段被写到外部tool_calls字段里了，这里再写一遍重复了
        tmpStr = `${rawContent}
【元数据 供阅读，禁止回复携带】
${yaml.dump(tmp)}`.trim();
        //console.log(tmpStr)
        return tmpStr;
      } else {
        // 用户消息也采用统一格式：正文 + 元数据
        rawContent = tmp.content;
        delete tmp.content;
        delete tmp.reasoning; // 推理内容不作为元数据发送
        delete tmp.sysReturns; //有一个工具调用结果的通知会把sysReturns的所有内容放content里，这里再写一遍重复了
        tmpStr = `${rawContent}
【元数据 供阅读，禁止回复携带】
${yaml.dump(tmp)}`.trim();
        return tmpStr;
      }
    };
    processAttachment = (ask, rawContent) => {
      var attachId, attachment, base64Data, bitmap, err, filePath, j, lastIndex, len, match, mimeType, parts, ref, ref1, ref2, tagRegex, usedAttachIds;
      if (((ref = ask.attachments) != null ? ref.length : void 0) > 0) {
        parts = [];
        usedAttachIds = [];
        lastIndex = 0;
        // 1. 首先解析正文中的显式标签
        if (typeof rawContent === 'string') {
          tagRegex = /\[attachid:([^\]]+)\]/g;
          while ((match = tagRegex.exec(rawContent)) !== null) {
            // 添加标签前的文本
            if (match.index > lastIndex) {
              parts.push({
                type: "text",
                text: rawContent.slice(lastIndex, match.index)
              });
            }
            // 查找匹配的附件
            attachId = match[1];
            attachment = ask.attachments.find((a) => {
              return a.id === attachId || a.id === attachId.split('.')[0];
            });
            if (attachment && attachment.type === 'image') {
              usedAttachIds.push(attachment.id);
              try {
                filePath = attachment.url.startsWith('/') ? attachment.url.startsWith('/attachment/') ? pathLib.resolve(`.${attachment.url}`) : attachment.url : pathLib.resolve(`${this.mediaDir // 绝对路径
}/${attachment.url}`);
                if (fs.existsSync(filePath)) {
                  bitmap = fs.readFileSync(filePath);
                  base64Data = Buffer.from(bitmap).toString('base64');
                  mimeType = `image/${pathLib.extname(filePath).slice(1) || 'png'}`;
                  parts.push({
                    type: "image_url",
                    image_url: {
                      url: `data:${mimeType};base64,${base64Data}`
                    }
                  });
                } else {
                  parts.push({
                    type: "text",
                    text: `[附件遗失:${attachId}]`
                  });
                }
              } catch (error1) {
                err = error1;
                console.error("读取附件失败:", err);
                parts.push({
                  type: "text",
                  text: `[附件读取失败:${attachId}]`
                });
              }
            } else {
              parts.push({
                type: "text",
                text: match[0]
              });
            }
            lastIndex = tagRegex.lastIndex;
          }
          // 添加剩余文本
          if (lastIndex < rawContent.length) {
            parts.push({
              type: "text",
              text: rawContent.slice(lastIndex)
            });
          }
        }
        ref1 = ask.attachments;
        // 2. 自动追加未被引用的图片附件 (确保即便没插入标签，AI 也能看到)
        for (j = 0, len = ref1.length; j < len; j++) {
          attachment = ref1[j];
          if (attachment.type === 'image' && (ref2 = attachment.id, indexOf.call(usedAttachIds, ref2) < 0)) {
            try {
              filePath = attachment.url.startsWith('/') ? attachment.url.startsWith('/attachment/') ? pathLib.resolve(`.${attachment.url}`) : attachment.url : pathLib.resolve(`${this.mediaDir}/${attachment.url}`);
              if (fs.existsSync(filePath)) {
                bitmap = fs.readFileSync(filePath);
                base64Data = Buffer.from(bitmap).toString('base64');
                mimeType = `image/${pathLib.extname(filePath).slice(1) || 'png'}`;
                parts.push({
                  type: "image_url",
                  image_url: {
                    url: `data:${mimeType};base64,${base64Data}`
                  }
                });
              }
            } catch (error1) {
              err = error1;
              console.error("自动读取未引用附件失败:", err);
            }
          }
        }
        if (parts.length > 0) {
          return parts;
        }
      }
      return rawContent;
    };
    filteredAsks = this.asks.filter((ask) => {
      return ask.ignore !== 1;
    });
    //转化asks到messages
    messages = filteredAsks.map((ask, index) => {
      var fnCallCache, foldedResults, latestToolCallIds, msg, note, rawContent, ref, tmpAsk, tmpIdx;
      // 如果是协议模式，需要根据ask追加元数据
      rawContent = useMsgProtocol ? formatMsg(ask, index) : ask.content;
      rawContent = processAttachment(ask, rawContent);
      if (useMsgProtocol) {
        if (config.toolsMode === 2) {
          if (ask.role === "tool" && rawContent.length > 1000) {
            //用while循环向前查找最后一批工具调用的tool_call_id，不在这批里的全部折叠
            latestToolCallIds = [];
            tmpIdx = this.asks.length - 1;
            while (tmpIdx >= 0) {
              tmpAsk = this.asks[tmpIdx];
              if (tmpAsk.role === "tool") {
                latestToolCallIds.push(tmpAsk.tool_call_id);
              } else if (tmpAsk.role === "assistant") {
                break;
              }
              tmpIdx--;
            }
            if (ref = ask.tool_call_id, indexOf.call(latestToolCallIds, ref) < 0) {
              fnCallCache = this.fnCallCachePool[ask.tool_call_id];
              if (!fnCallCache) {
                fnCallCache = this.fnCallCachePoolAdd({
                  name: ask.name || "tool_response",
                  output: ask.content,
                  call_id: ask.tool_call_id, // 使用 Mode 2 的原生 ID
                  arguments: {}
                });
              }
              rawContent = `该工具执行结果已进入工具缓存池内
id为${fnCallCache.cacheid}
若被折叠，请用【工具缓存池展开工具】查看系统记忆中的完整内容。`.trim();
            }
          }
        } else {
          if (ask.sysReturns && ask.sysReturns.length > 0 && index !== filteredAsks.length - 1) {
            if (rawContent.length > 1000) {
              //不是最后一条工具调用消息且字数大于1000就折叠
              foldedResults = [];
              ask.sysReturns.forEach((sysReturn) => {
                fnCallCache = this.fnCallCachePool[sysReturn.call_id];
                if (!fnCallCache) {
                  fnCallCache = this.fnCallCachePoolAdd(sysReturn);
                }
                return foldedResults.push(`该函数/工具执行结果已进入工具缓存池内折叠
id为${fnCallCache.cacheid}
若被折叠，请用【工具缓存池展开工具】查看系统记忆中的完整内容。`.trim());
              });
              rawContent = foldedResults.join("\n---\n");
            }
          }
        }
      }
      msg = {
        role: ask.role,
        content: rawContent
      };
      // 针对推理模型，将 note 映射为 reasoning_content 作为一种取巧的上下文回传方式
      // 只要该消息原本有 reasoning 或 note，就传回 reasoning_content，以保证会话的完整性
      if (ask.role === "assistant") {
        note = (function() {
          try {
            return JSON.parse(ask.content).note;
          } catch (error1) {
            return null;
          }
        })();
        if (ask.reasoning) {
          //msg.reasoning_content = note or ask.reasoning
          msg.reasoning_content = ask.reasoning;
        }
      }
      if (ask.toolCalls && ask.toolCalls.length > 0) {
        msg.tool_calls = ask.toolCalls;
      }
      if (ask.tool_call_id) {
        msg.tool_call_id = ask.tool_call_id;
      }
      return msg;
    });
    if (useMsgProtocol) {
      messages[0].content = this.buildPromptZero(config, toolTipObj) + "\n" + this.buildMemory();
      if (config != null ? config.getExtraInfo : void 0) {
        messages[0].content += `\n
【系统信息】
${config.getExtraInfo()}`;
      }
    }
    // 动态滑动合并连续的同角色消息，解决 API 400 格式错误
    // 不合并 tool 消息，因为 API 具有独立的 tool_call_id
    mergedMessages = [];
    for (j = 0, len = messages.length; j < len; j++) {
      msg = messages[j];
      lastMsg = mergedMessages[mergedMessages.length - 1];
      if (lastMsg && ((ref = msg.role) === "user" || ref === "assistant" || ref === "system") && lastMsg.role === msg.role) {
        lastIsArray = Array.isArray(lastMsg.content);
        currIsArray = Array.isArray(msg.content);
        if (!lastIsArray && !currIsArray) {
          lastMsg.content += "\n---\n" + msg.content;
        } else {
          lastContentArr = lastIsArray ? lastMsg.content : [
            {
              type: "text",
              text: lastMsg.content
            }
          ];
          currContentArr = currIsArray ? msg.content : [
            {
              type: "text",
              text: msg.content
            }
          ];
          lastContentArr.push({
            type: "text",
            text: "\n---\n"
          });
          lastMsg.content = lastContentArr.concat(currContentArr);
        }
      } else {
        mergedMessages.push(msg);
      }
    }
    return mergedMessages;
  }

  //获取最后一条消息发给ai，加入asks组并返回ai返回消息
  async sendAsk(streamFn, config = {}) {
    var assistantAttachments, cachedT, chunk, completion, completionT, doneChunk, e, err, ext, filename, fullReasonings, fullReplys, fullToolCalls, id, imgRegex, imgResponse, imgUrl, j, len, match, matches, promptT, reasoning, reasoningChunk, ref, ref1, ref10, ref11, ref12, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, reply, replyChunk, sendConfig, toolCalls, totalT, uploadPath;
    try {
      promptT = 0;
      completionT = 0;
      totalT = 0;
      cachedT = 0;
      if (config.retry == null) {
        config.retry = 0;
      }
      /* aiList = config.aiList
           modelIndex = aiList.findIndex (model)=>
             model.name is @name
           unless aiList[modelIndex]
             throw new Error "找不到模型对应的数据库模型配置（读取preToken错误）"
           if aiList[modelIndex].preTokens <= 0
             throw new Error "已到达设置中preToken的预警值，preToken不足" */
      if (config.onSendAskBefore) {
        await config.onSendAskBefore(this);
      }
      sendConfig = {
        model: this.aiConfig.model,
        ...(config.useMsgProtocol && config.jsonSchema ? {
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "sendTemplate",
              strict: true,
              schema: config.jsonSchema
            }
          }
        } : void 0),
        ...(config.useMsgProtocol && config.jsonObject ? {
          response_format: {
            type: "json_object"
          }
        } : void 0),
        messages: this.messages = config.messages || this.prepareMessages(false)
      };
      if (streamFn || (((ref = this.userConfig) != null ? ref.stream : void 0) != null)) {
        sendConfig.stream = streamFn ? Boolean(streamFn) : Boolean(this.userConfig.stream);
        sendConfig.stream_options = {
          include_usage: true
        };
      }
      if (((ref1 = this.userConfig) != null ? ref1.seed : void 0) != null) {
        sendConfig.seed = this.userConfig.seed;
      }
      if (((ref2 = this.userConfig) != null ? ref2.topP : void 0) != null) {
        sendConfig.top_p = this.userConfig.topP;
      }
      if (((ref3 = this.userConfig) != null ? ref3.topK : void 0) != null) {
        sendConfig.top_k = this.userConfig.topK;
      }
      if (((ref4 = this.userConfig) != null ? ref4.temperature : void 0) != null) {
        sendConfig.temperature = this.userConfig.temperature;
      }
      if (((ref5 = this.userConfig) != null ? ref5.stop : void 0) != null) {
        sendConfig.stop = this.userConfig.stop;
      }
      if (((ref6 = this.userConfig) != null ? ref6.maxToken : void 0) != null) {
        sendConfig.max_tokens = this.userConfig.maxToken;
      }
      //config配置工具调用
      if (config.tools) {
        sendConfig.tools = config.tools;
      }
      if (config.toolChoice) {
        sendConfig.tool_choice = config.toolChoice;
      }
      if (config.enableThinking === true) {
        sendConfig.enable_thinking = config.enableThinking;
      }
      // 调试：将请求报文写入 tmp 目录 (增加防抖避免频繁写入)
      writeDebugConfig(JSON.stringify(sendConfig, null, 2));
      if (!(streamFn || ((ref7 = this.userConfig) != null ? ref7.stream : void 0))) {
        //发起请求
        completion = (await this.openAi.chat.completions.create(sendConfig, {
          signal: this.abortController.signal
        }));
        if (!(completion != null ? (ref8 = completion.choices) != null ? (ref9 = ref8[0]) != null ? ref9.message : void 0 : void 0 : void 0)) {
          throw new Error("大模型接口请求失败", completion);
        }
        reply = completion.choices[0].message.content;
        reasoning = completion.choices[0].message.reasoning_content || "";
        toolCalls = (ref10 = completion.choices[0].message) != null ? ref10.tool_calls : void 0;
        if (completion.usage) {
          promptT = this.usage.promptTokens = completion.usage.prompt_tokens;
          totalT = this.usage.totalTokens = completion.usage.total_tokens;
          completionT = this.usage.completionTokens = completion.usage.completion_tokens;
          cachedT = this.usage.cachedTokens = ((ref11 = completion.usage.prompt_tokens_details) != null ? ref11.cached_tokens : void 0) || 0;
          //aiList[modelIndex].preTokens = Number(aiList[modelIndex].preTokens) - Number(@usage.totalTokens)
          //await options.set "ai_aiList",aiList
          if (config.onTokenChange) {
            await config.onTokenChange(this, {
              promptT: promptT,
              completionT: completionT,
              totalT: totalT,
              cachedT: cachedT
            });
          }
        } else {
          console.log("警告：大模型没有返回token使用信息");
        }
      } else {
        completion = (await this.openAi.chat.completions.create(sendConfig, {
          signal: this.abortController.signal
        }));
        fullReplys = [];
        fullReasonings = [];
        fullToolCalls = [];
        replyChunk = "";
        reasoningChunk = "";
        doneChunk = null;
        for await (chunk of completion) {
          // 检查是否已停止，如果已停止则立即退出循环
          //if @stop
          //  break
          await (async(chunk) => {
            var deltaToolCalls, index, j, len, toolCallChunk;
            //console.log JSON.stringify(chunk)
            doneChunk = chunk;
            // 拼接并执行回调
            if (Array.isArray(chunk.choices) && chunk.choices.length > 0) {
              // 初始化本轮片段内容
              replyChunk = chunk.choices[0].delta.content || "";
              reasoningChunk = chunk.choices[0].delta.reasoning_content || "";
              deltaToolCalls = chunk.choices[0].delta.tool_calls;
              // 拼接回复
              if (replyChunk) {
                fullReplys.push(replyChunk);
              }
              // 拼接推理内容 (Reasoning Content)
              if (reasoningChunk) {
                fullReasonings.push(reasoningChunk);
              }
              // 拼接工具调用
              if (deltaToolCalls) {
                for (index = j = 0, len = deltaToolCalls.length; j < len; index = ++j) {
                  toolCallChunk = deltaToolCalls[index];
                  ((toolCallChunk) => {
                    var ref12, ref13, tmpIndex;
                    tmpIndex = toolCallChunk.index || index;
                    if (fullToolCalls[tmpIndex] == null) {
                      fullToolCalls[tmpIndex] = {
                        ...toolCallChunk,
                        function: {
                          name: "",
                          arguments: ""
                        }
                      };
                    }
                    if ((ref12 = toolCallChunk.function) != null ? ref12.name : void 0) {
                      fullToolCalls[tmpIndex].function.name = toolCallChunk.function.name;
                    }
                    if ((ref13 = toolCallChunk.function) != null ? ref13.arguments : void 0) {
                      return fullToolCalls[tmpIndex].function.arguments += toolCallChunk.function.arguments;
                    }
                  })(toolCallChunk);
                }
              }
              // 执行回调
              if (streamFn && (replyChunk || reasoningChunk)) {
                return (await streamFn({
                  aiAsk: this,
                  chunk: chunk,
                  replyChunk: replyChunk,
                  reasoningChunk: reasoningChunk
                }));
              }
            }
          })(chunk);
        }
        if (doneChunk != null ? doneChunk.usage : void 0) {
          this.usage.promptTokens = doneChunk.usage.prompt_tokens;
          this.usage.totalTokens = doneChunk.usage.total_tokens;
          this.usage.completionTokens = doneChunk.usage.completion_tokens;
          this.usage.cachedTokens = ((ref12 = doneChunk.usage.prompt_tokens_details) != null ? ref12.cached_tokens : void 0) || 0;
          promptT += this.usage.promptTokens;
          totalT += this.usage.totalTokens;
          completionT += this.usage.completionTokens;
          cachedT += this.usage.cachedTokens;
          //aiList[modelIndex].preTokens = Number(aiList[modelIndex].preTokens) - Number(@usage.totalTokens)
          //await options.set "ai_aiList",aiList
          if (config.onTokenChange) {
            await config.onTokenChange(this, {
              promptT: promptT,
              completionT: completionT,
              totalT: totalT,
              cachedT: cachedT
            });
          }
        } else {
          console.log("警告：流模式，大模型没有返回token使用信息");
        }
        reply = fullReplys.join("");
        reasoning = fullReasonings.join("");
        toolCalls = fullToolCalls;
      }
      // --- 入站归一化 (Inbound Normalization) ---
      // 如果 AI 回复中包含 Markdown 图片，自动下载并转存
      assistantAttachments = [];
      if (typeof reply === 'string' && this.mediaDir) {
        imgRegex = /!\[([^\]]*)\]\((https?:\/\/[^\)]+)\)/g;
        matches = [];
        while ((match = imgRegex.exec(reply)) !== null) {
          matches.push(match);
        }
        if (matches.length > 0) {
          for (j = 0, len = matches.length; j < len; j++) {
            match = matches[j];
            try {
              imgUrl = match[2];
              id = idTool.get("image");
              // 自动获取后缀名
              ext = ".png";
              if (imgUrl.split('?')[0].match(/\.(jpg|jpeg|png|gif|webp)$/i)) {
                ext = imgUrl.split('?')[0].match(/\.(jpg|jpeg|png|gif|webp)$/i)[0];
              }
              filename = `${id}${ext}`;
              uploadPath = pathLib.resolve(this.mediaDir, filename);
              await fs.ensureDir(this.mediaDir);
              // 下载并保存
              imgResponse = (await axios.get(imgUrl, {
                responseType: 'arraybuffer'
              }));
              await fs.writeFile(uploadPath, Buffer.from(imgResponse.data));
              assistantAttachments.push({
                id: filename,
                url: `/attachment/${filename}`,
                type: 'image'
              });
              // 替换为标签
              reply = reply.replace(match[0], `[attachid:${filename}]`);
            } catch (error1) {
              e = error1;
              console.error("归一化处理图片失败:", e);
            }
          }
        }
      }
      this.addAsk(this.name, "assistant", reply, {
        promptTokens: promptT,
        completionTokens: completionT,
        totalTokens: totalT,
        cachedTokens: cachedT,
        reasoning: reasoning,
        toolCalls: toolCalls,
        attachments: assistantAttachments,
        group: "agent",
        listId: config.listId
      });
      return this.asks.at(-1);
    } catch (error1) {
      err = error1;
      throw err;
    }
  }

  //快速提问
  async ask(user, role, msg, config) {
    var err;
    try {
      this.addAsk(user, role, msg);
      return (await this.sendAsk(null, config));
    } catch (error1) {
      err = error1;
      throw err;
    }
  }

  async sendAskByMsgProtocol(config = {}) {
    /*Object.entries(call.arguments).map(([key,value])=>"#{key}:#{value}").join("\n")*/
    var aiReply, allTools, ask, deferFn, deferredFns, err, i, isLast, j, joiError, joiSchema, jsonErr, l, len, len1, len2, len3, len4, m, n, o, parseError, prePareCallStr, ref, ref1, ref2, ref3, ref4, reply, replyJSON, ret, returnJoi, sysReturns, sysReturnsStr, time, tip, toolCall, toolCallDuration, toolCallGroupId, toolCallStartTime, toolCallSuccess, toolTipObj, truncatedFns, validateOutput;
    try {
      //console.log "发送前",@messages
      this.replying = true;
      if (this.stop) {
        this.replying = false;
      }
      if (config.beforeRun) {
        await config.beforeRun(this);
      }
      if (this.stop) {
        return;
      }
      //等待
      await new Promise((res) => {
        return setTimeout(res, 200);
      });
      // 工具由外部注入（config.tools 为扁平数组，每个 tool 带 type 属性）
      allTools = config.tools || [];
      toolTipObj = {
        sysCall: allTools.filter((t) => {
          return t.type === "sysCall" || t.type === "appCall";
        }).map(createToolTip),
        usrCall: allTools.filter((t) => {
          return t.type === "usrCall";
        }).map(createToolTip),
        aiCall: allTools.filter((t) => {
          return t.type === "aiCall";
        }).map(createToolTip)
      };
      //开始逻辑
      this.fnCallCachePoolTick();
      this.messages = this.prepareMessages(true, config, config.toolTipObj || toolTipObj);
      if (config.retry == null) {
        config.retry = 0;
      }
      aiReply = (await this.sendAsk(config.streamFn || null, {
        onSendAskBefore: config.onSendAskBefore, //sendAsk之前判定preToken用
        onTokenChange: config.onTokenChange, //token变化计算preToken用
        listId: config.listId, // 修复：显式传递 listId，确保 aiReply 正确携带所属列表 ID
        useMsgProtocol: true,
        msgProtocolConfig: config,
        messages: this.messages,
        ...(config.toolsMode === 1 ? {
          jsonObject: true
        } : void 0),
        ...(config.toolsMode === 2 ? {
          tools: allTools.map(createStdToolTip),
          toolChoice: "auto",
          // Mode 2 不传 jsonSchema，让 AI 自由输出文本，解析层自动包装
          jsonSchema: joiToJSON(sendTemplate.joi(true))
        } : void 0),
        ...(config.toolsMode === 3 ? {
          jsonSchema: joiToJSON(sendTemplate.joi())
        } : void 0),
        enableThinking: config.enableThinking
      }));
      //console.log "aiReply",JSON.stringify aiReply,null,2
      if (config.onResponse) {
        await config.onResponse(aiReply);
      }
      reply = aiReply.content;
      //检查消息格式是否正确
      joiError = parseError = null;
      replyJSON = null;
      try {
        // 处理空回复的情况（通常出现在原生工具调用时，模型可能不输出正文 JSON）
        if (!(reply != null ? reply.trim() : void 0) && ((ref = aiReply.toolCalls) != null ? ref.length : void 0) > 0) {
          replyJSON = {
            mind: "执行函数...",
            mood: 5,
            content: "执行函数...",
            note: "执行函数...",
            playFace: "无表情",
            faceAction: "none"
          };
        } else {
          try {
            replyJSON = JSON.parse(reply);
          } catch (error1) {
            jsonErr = error1;
            throw jsonErr; // 非 Mode 2 抛出原始错误，走原有重试逻辑
          }
        }
        joiSchema = sendTemplate.joi((function() {
          switch (config.toolsMode) {
            case 1:
            case 3:
              return false;
            case 2:
              return true; //使用标准工具
          }
        })());
        validateOutput = joiSchema.validate(replyJSON);
        joiError = validateOutput.error;
        if (aiReply.toolCalls) { //如果使用了tools参数，把工具调用转换为sysCalls
          if (replyJSON.sysCalls == null) {
            replyJSON.sysCalls = [];
          }
          ref1 = aiReply.toolCalls;
          for (j = 0, len = ref1.length; j < len; j++) {
            toolCall = ref1[j];
            replyJSON.sysCalls.push({
              id: toolCall.function.name,
              call_id: toolCall.id,
              type: "function_call",
              name: toolCall.function.name,
              arguments: JSON.parse(toolCall.function.arguments)
            });
          }
        }
      } catch (error1) {
        err = error1;
        parseError = "调用JSON.parse错误：" + err;
      }
      if (joiError || parseError) {
        console.log("解析错误", joiError, parseError);
        console.log("重试次数", config.retry);
        console.log("=====");
        returnJoi = joiError ? joiError.details[0].message : parseError;
        // 如果本轮有工具调用，通过还原工具结果来报回错误，避免 400 错误并保护执行安全
        if (((ref2 = aiReply.toolCalls) != null ? ref2.length : void 0) > 0) {
          ref3 = aiReply.toolCalls;
          for (l = 0, len1 = ref3.length; l < len1; l++) {
            toolCall = ref3[l];
            ask = this.addAsk(toolCall.function.name, "tool", `⚠️ 系统拦截：消息正文JSON错误（joi校验错误: ${returnJoi}）请根据通讯协议返回stringify后的标准json格式，禁止携带元数据`, {
              tool_call_id: toolCall.id
            });
          }
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          // 直接进入递归重试
          if (config.retry < 4) {
            config.retry++;
            await this.sendAskByMsgProtocol({...config});
            this.replying = false;
            return;
          } else {
            tip = "ai返回错误超出系统限制";
            ask = this.addAsk("系统通讯中枢", "user", tip, {
              isSystem: 1,
              retry: config.retry,
              joi: joiError ? joiError.details[0].message : parseError,
              group: "tip"
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
            config.retry = 0;
            this.replying = false; //递归不需要回归
            return;
          }
        } else {
          // 如果没有工具调用，保留原有的 User 消息报错模式
          tip = `返回JSON错误，请严格按通讯协议构建被stringify后的标准JSON，禁止携带元数据，错误详见joi字段，重试${config.retry + 1}/4`;
          ask = this.addAsk("系统通讯中枢", "user", tip, {
            isSystem: 1,
            retry: config.retry,
            joi: returnJoi,
            group: "tip"
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          if (config.retry < 4) {
            config.retry++;
            await this.sendAskByMsgProtocol({
              ...config,
              onResponse: async(reply) => {
                if (config.onResponse) {
                  return (await config.onResponse(reply));
                }
              }
            });
            this.replying = false; //递归不需要回归
            return;
          } else {
            tip = "ai返回错误超出系统限制";
            ask = this.addAsk("系统通讯中枢", "user", tip, {
              isSystem: 1,
              retry: config.retry,
              joi: joiError ? joiError.details[0].message : parseError,
              group: "tip"
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
            config.retry = 0;
            this.replying = false; //递归不需要回归
            return;
          }
        }
      }
      config.retry = 0; //重置
      
      //处理记忆
      this.memory = {
        id: aiReply.id,
        listId: aiReply.listId,
        time: aiReply.time,
        content: `[列表id：${aiReply.listId}][消息id:${aiReply.id}][时间:${aiReply.time}]${replyJSON.note}`
      };
      this.memorys.push(this.memory);
      if (this.memorys.length > 50) {
        this.memorys.shift();
      }
      //处理函数调用
      if (((ref4 = replyJSON.sysCalls) != null ? ref4.length : void 0) > 0) {
        time = new Date();
        if (config.sysCallCount == null) {
          config.sysCallCount = 0;
        }
        if (config.sysCallCount < 100) {
          console.log("触发函数调用");
          config.sysCallCount++;
          // 生成工具调用组ID和记录开始时间
          toolCallGroupId = `tcg_${Date.now()}`;
          toolCallStartTime = Date.now();
          prePareCallStr = `\`\`\`\n${yaml.dump(replyJSON.sysCalls)}\n\`\`\``;
          ask = this.addAsk("系统通讯中枢", "user", `准备调用函数，本消息不被发送\n${prePareCallStr}`.trim(), {
            isSystem: 1,
            ignore: 1,
            group: "tip",
            title: "准备调用函数，本消息不被发送",
            toolCallGroupId: toolCallGroupId,
            toolCallStage: "prepare"
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          deferredFns = [];
          sysReturns = (await this.sysCallRunFns(replyJSON.sysCalls, allTools, {
            listId: config.listId,
            toolCallGroupId,
            aiAskInstance: this,
            deferredFns,
            onResponse: config.onResponse,
            aiReply,
            config
          }));
          // 检查是否有内容超出限制，并处理截断与 UI 提示
          truncatedFns = [];
          for (m = 0, len2 = sysReturns.length; m < len2; m++) {
            ret = sysReturns[m];
            // 1. 强制类型转换为字符串 (这对 toolsMode=2 甚至 Mode 3 的稳定性至关重要)
            // 如果是对象，转为 JSON 字符串；如果是其他，转为 String
            if (typeof ret.output !== 'string') {
              ret.output = String(ret.output);
            }
            // 2. 长度安全检查与截断
            if (ret.output.length > 5000) {
              // 实施截断
              ret.output = ret.output.slice(0, 5000) + "...(已截断0-5000字)";
              truncatedFns.push(`【${ret.name || ret.id}】`);
            }
          }
          if (truncatedFns.length > 0) {
            ask = this.addAsk("系统通讯中枢", "user", `⚠️ 警告：检测到函数 ${truncatedFns.join(', ')} 输出超过安全限制（5000字符），内容已被自动截断以保护会话性能。该提示不会发送给 AI。`, {
              isSystem: 1,
              ignore: 1,
              group: "tip",
              title: "函数输出截断警告",
              toolCallGroupId: toolCallGroupId
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
          }
          // 计算执行时长和判断是否成功
          toolCallDuration = Date.now() - toolCallStartTime;
          toolCallSuccess = sysReturns.every(function(ret) {
            return !ret.error;
          });
          // 同步加入缓存池，避免下一回合才能获取到索引
          sysReturns.forEach((ret) => {
            return this.fnCallCachePoolAdd(ret);
          });
          if (config.toolsMode === 2) { //标准工具模式需要用指定tool角色，有多条工具调用消息，在最后一条加信息
            for (i = n = 0, len3 = sysReturns.length; n < len3; i = ++n) {
              ret = sysReturns[i];
              isLast = i === sysReturns.length - 1;
              ask = this.addAsk("系统通讯中枢", "tool", ret.output + `${isLast ? "下一轮对话这些结果将被折叠，请对关键信息记好笔记" : ""}`, {
                tool_call_id: ret.call_id,
                name: ret.id,
                group: "tip",
                isSystem: 1,
                toolCallGroupId: toolCallGroupId,
                toolCallStage: isLast ? "done" : "executing",
                ...(isLast ? {
                  toolCallDuration: toolCallDuration,
                  toolCallSuccess: toolCallSuccess
                } : void 0)
              });
              if (config.onResponse) {
                await config.onResponse(ask);
              }
            }
          } else {
            ask = this.addAsk("系统通讯中枢", "user", `函数执行完毕
  \`\`\`\n${yaml.dump(sysReturns)}\n\`\`\`
下一轮对话该结果将被折叠，请对关键信息记好笔记`.trim(), {
              isSystem: 1,
              sysReturns: sysReturns,
              group: "tip",
              title: "函数执行完毕",
              toolCallGroupId: toolCallGroupId,
              toolCallStage: "done",
              toolCallDuration: toolCallDuration,
              toolCallSuccess: toolCallSuccess
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
          }
          //处理函数调用，缓存最近10条
          sysReturnsStr = (function(output) {
            sysReturns.forEach(function(ret) {
              return output += `[name:${ret.name}][id:${ret.id}][call_id:${ret.call_id}]\n${ret.output}\n`;
            });
            return output;
          })("");
          this.fnCallOutput = `[列表id：${aiReply.listId}][消息id:${aiReply.id}][时间:${aiReply.time}]\n${sysReturnsStr}`;
          this.fnCallOutputs.push(this.fnCallOutput);
          if (this.fnCallOutputs.length > 10) {
            this.fnCallOutputs.shift();
          }
// 在协议安全窗口内，统一执行工具注册的延迟函数（如 aiSendMessage）
          for (o = 0, len4 = deferredFns.length; o < len4; o++) {
            deferFn = deferredFns[o];
            await deferFn();
          }
          await this.sendAskByMsgProtocol({
            ...config,
            onResponse: config.onResponse
          });
          return;
        } else {
          ask = this.addAsk("系统通讯中枢", "user", "函数反复调用超限，请先中断等待用户继续发起", {
            isSystem: 1,
            group: "tip",
            title: "函数调用超限"
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          await this.sendAskByMsgProtocol({
            ...config,
            onResponse: config.onResponse
          });
          return;
        }
      }
      this.replying = false;
      if (config.endRun) {
        return (await config.endRun(this));
      }
    } catch (error1) {
      err = error1;
      this.replying = false;
      if (config.endRun) {
        await config.endRun(this);
      }
      throw err;
    }
  }

  stopRun() {
    this.abortController.abort();
    return this.stop = true;
  }

  noStopRun() {
    this.abortController = new AbortController();
    return this.stop = false;
  }

  async sysCallRunFns(sysCalls, sysAllTools, metaData = {}) {
    var call, err, fn, j, len, returnStr, sysReturns;
    sysReturns = [];
    returnStr = "";
    for (j = 0, len = sysCalls.length; j < len; j++) {
      call = sysCalls[j];
      fn = sysAllTools.find((tool) => {
        return tool.id === call.id;
      });
      if (!fn) {
        returnStr = `找不到函数 ${call.name} ${call.id}`;
      } else {
        try {
          returnStr = (await fn.fn(call.arguments, metaData));
        } catch (error1) {
          err = error1;
          console.log(err, String(err));
          returnStr = String(err);
        }
      }
      sysReturns.push({
        type: "function_call_output",
        call_id: call.call_id,
        name: call.name,
        id: call.id,
        output: returnStr,
        arguments: call.arguments
      });
    }
    return sysReturns;
  }

  fnCallCachePoolAdd(sysReturn) {
    var cacheid, keys;
    // 使用唯一的 call_id 作为缓存池的 Key，避免生成新 ID 导致的重复入池
    cacheid = sysReturn.call_id;
    if (!this.fnCallCachePool[cacheid]) {
      keys = Object.keys(this.fnCallCachePool);
      if (keys.length >= 10) {
        delete this.fnCallCachePool[keys[0]];
      }
      this.fnCallCachePool[cacheid] = {
        cacheid: cacheid,
        name: sysReturn.name,
        arguments: sysReturn.arguments,
        output: sysReturn.output,
        count: 0
      };
    }
    return this.fnCallCachePool[cacheid];
  }

  fnCallCachePoolRemove(cacheid) {
    return delete this.fnCallCachePool[cacheid];
  }

  fnCallCachePoolTick() {
    var id, item, ref, results1;
    ref = this.fnCallCachePool;
    results1 = [];
    for (id in ref) {
      item = ref[id];
      if (item.count > 0) {
        results1.push(item.count--);
      } else {
        results1.push(void 0);
      }
    }
    return results1;
  }

});
