// Generated by CoffeeScript 2.7.0
export default function() {
  var aX, aY, bX, bY, cX, cY, denomX, denomY, discriminantX, discriminantY, extremeX, extremeY, i, j, len, len1, maxX, maxY, minX, minY, p0, p1, p2, p3, points, ref, ref1, sqrtDiscX, sqrtDiscY, t1, t1X, t1Y, t2X, t2Y, tX, tY;
  points = this.getPoints();
  if (points.length === 2) {
    // 直线的包围盒
    minX = Math.min(points[0].x, points[1].x);
    maxX = Math.max(points[0].x, points[1].x);
    minY = Math.min(points[0].y, points[1].y);
    maxY = Math.max(points[0].y, points[1].y);
    return {minX, maxX, minY, maxY};
  } else if (points.length === 3) {
    // 二次贝塞尔曲线的精确包围盒
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    
    // 初始边界为端点
    minX = Math.min(p0.x, p2.x);
    maxX = Math.max(p0.x, p2.x);
    minY = Math.min(p0.y, p2.y);
    maxY = Math.max(p0.y, p2.y);
    
    // 计算X方向的极值点
    // 二次贝塞尔曲线: B(t) = (1-t)²*P0 + 2*(1-t)*t*P1 + t²*P2
    // 导数: B'(t) = 2*(1-t)*(P1-P0) + 2*t*(P2-P1) = 2*((1-t)*P1 - (1-t)*P0 + t*P2 - t*P1)
    //             = 2*((P1-P0) + t*(P0-2*P1+P2))
    // 令B'(t) = 0: (P1-P0) + t*(P0-2*P1+P2) = 0
    // t = (P0-P1)/(P0-2*P1+P2)
    denomX = p0.x - 2 * p1.x + p2.x;
    if (Math.abs(denomX) > 1e-10) {
      tX = (p0.x - p1.x) / denomX;
      if (tX > 0 && tX < 1) {
        // 计算极值点的X坐标
        extremeX = (1 - tX) * (1 - tX) * p0.x + 2 * (1 - tX) * tX * p1.x + tX * tX * p2.x;
        minX = Math.min(minX, extremeX);
        maxX = Math.max(maxX, extremeX);
      }
    }
    denomY = p0.y - 2 * p1.y + p2.y;
    if (Math.abs(denomY) > 1e-10) {
      tY = (p0.y - p1.y) / denomY;
      if (tY > 0 && tY < 1) {
        // 计算极值点的Y坐标
        extremeY = (1 - tY) * (1 - tY) * p0.y + 2 * (1 - tY) * tY * p1.y + tY * tY * p2.y;
        minY = Math.min(minY, extremeY);
        maxY = Math.max(maxY, extremeY);
      }
    }
    return {minX, maxX, minY, maxY};
  } else if (points.length === 4) {
    // 三次贝塞尔曲线的精确包围盒
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    p3 = points[3];
    
    // 初始边界为端点
    minX = Math.min(p0.x, p3.x);
    maxX = Math.max(p0.x, p3.x);
    minY = Math.min(p0.y, p3.y);
    maxY = Math.max(p0.y, p3.y);
    
    // 计算X方向的极值点
    // 三次贝塞尔曲线: B(t) = (1-t)³*P0 + 3*(1-t)²*t*P1 + 3*(1-t)*t²*P2 + t³*P3
    // 导数: B'(t) = 3*(1-t)²*(P1-P0) + 6*(1-t)*t*(P2-P1) + 3*t²*(P3-P2)
    //             = 3*((1-t)²*(P1-P0) + 2*(1-t)*t*(P2-P1) + t²*(P3-P2))
    // 令B'(t) = 0，得到二次方程: at² + bt + c = 0
    // 其中: a = (P0-P1) + (P2-P1) + (P3-P2) = P0 - 3*P1 + 3*P2 - P3
    //      b = 2*(P0 - 2*P1 + P2)
    //      c = P1-P0
    aX = -p0.x + 3 * p1.x - 3 * p2.x + p3.x;
    bX = 2 * (p0.x - 2 * p1.x + p2.x);
    cX = p1.x - p0.x;
    
    // 求解二次方程
    discriminantX = bX * bX - 4 * aX * cX;
    if (Math.abs(aX) > 1e-10 && discriminantX >= 0) {
      sqrtDiscX = Math.sqrt(discriminantX);
      t1X = (-bX + sqrtDiscX) / (2 * aX);
      t2X = (-bX - sqrtDiscX) / (2 * aX);
      ref = [t1X, t2X];
      for (i = 0, len = ref.length; i < len; i++) {
        tX = ref[i];
        if (tX > 0 && tX < 1) {
          // 计算极值点的X坐标
          t1 = 1 - tX;
          extremeX = t1 * t1 * t1 * p0.x + 3 * t1 * t1 * tX * p1.x + 3 * t1 * tX * tX * p2.x + tX * tX * tX * p3.x;
          minX = Math.min(minX, extremeX);
          maxX = Math.max(maxX, extremeX);
        }
      }
    } else if (Math.abs(aX) <= 1e-10 && Math.abs(bX) > 1e-10) {
      // 线性情况
      tX = -cX / bX;
      if (tX > 0 && tX < 1) {
        t1 = 1 - tX;
        extremeX = t1 * t1 * t1 * p0.x + 3 * t1 * t1 * tX * p1.x + 3 * t1 * tX * tX * p2.x + tX * tX * tX * p3.x;
        minX = Math.min(minX, extremeX);
        maxX = Math.max(maxX, extremeX);
      }
    }
    
    // Y方向的极值点
    aY = -p0.y + 3 * p1.y - 3 * p2.y + p3.y;
    bY = 2 * (p0.y - 2 * p1.y + p2.y);
    cY = p1.y - p0.y;
    discriminantY = bY * bY - 4 * aY * cY;
    if (Math.abs(aY) > 1e-10 && discriminantY >= 0) {
      sqrtDiscY = Math.sqrt(discriminantY);
      t1Y = (-bY + sqrtDiscY) / (2 * aY);
      t2Y = (-bY - sqrtDiscY) / (2 * aY);
      ref1 = [t1Y, t2Y];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        tY = ref1[j];
        if (tY > 0 && tY < 1) {
          // 计算极值点的Y坐标
          t1 = 1 - tY;
          extremeY = t1 * t1 * t1 * p0.y + 3 * t1 * t1 * tY * p1.y + 3 * t1 * tY * tY * p2.y + tY * tY * tY * p3.y;
          minY = Math.min(minY, extremeY);
          maxY = Math.max(maxY, extremeY);
        }
      }
    } else if (Math.abs(aY) <= 1e-10 && Math.abs(bY) > 1e-10) {
      // 线性情况
      tY = -cY / bY;
      if (tY > 0 && tY < 1) {
        t1 = 1 - tY;
        extremeY = t1 * t1 * t1 * p0.y + 3 * t1 * t1 * tY * p1.y + 3 * t1 * tY * tY * p2.y + tY * tY * tY * p3.y;
        minY = Math.min(minY, extremeY);
        maxY = Math.max(maxY, extremeY);
      }
    }
    return {minX, maxX, minY, maxY};
  } else {
    // 其他情况，回退到控制点包围盒
    minX = Math.min.apply(Math, points.map(function(p) {
      return p.x;
    }));
    maxX = Math.max.apply(Math, points.map(function(p) {
      return p.x;
    }));
    minY = Math.min.apply(Math, points.map(function(p) {
      return p.y;
    }));
    maxY = Math.max.apply(Math, points.map(function(p) {
      return p.y;
    }));
    return {minX, maxX, minY, maxY};
  }
};
