// Generated by CoffeeScript 2.7.0
export default function(t) {
  var p0, p1, p2, p3, points, t1;
  points = this.getPoints();
  if (points.length === 2) {
    return {
      x: 0,
      y: 0
    };
  }
  if (points.length === 3) {
    // 二次贝塞尔曲线导数
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    return {
      x: 2 * ((1 - t) * (p1.x - p0.x) + t * (p2.x - p1.x)),
      y: 2 * ((1 - t) * (p1.y - p0.y) + t * (p2.y - p1.y))
    };
  } else if (points.length === 4) {
    // 三次贝塞尔曲线导数
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    p3 = points[3];
    t1 = 1 - t;
    return {
      x: 3 * (t1 * t1 * (p1.x - p0.x) + 2 * t1 * t * (p2.x - p1.x) + t * t * (p3.x - p2.x)),
      y: 3 * (t1 * t1 * (p1.y - p0.y) + 2 * t1 * t * (p2.y - p1.y) + t * t * (p3.y - p2.y))
    };
  }
  throw new Error("不正确的points长度");
};
