// Generated by CoffeeScript 2.7.0
export default function(t) {
  var p0, p1, p2, p3, points;
  points = this.getPoints();
  if (points.length === 3) {
    // 二次贝塞尔曲线二阶导数（常数）
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    return {
      x: 2 * (p2.x - 2 * p1.x + p0.x),
      y: 2 * (p2.y - 2 * p1.y + p0.y)
    };
  } else if (points.length === 4) {
    // 三次贝塞尔曲线二阶导数
    p0 = points[0];
    p1 = points[1];
    p2 = points[2];
    p3 = points[3];
    return {
      x: 6 * ((1 - t) * (p2.x - 2 * p1.x + p0.x) + t * (p3.x - 2 * p2.x + p1.x)),
      y: 6 * ((1 - t) * (p2.y - 2 * p1.y + p0.y) + t * (p3.y - 2 * p2.y + p1.y))
    };
  }
  return {
    x: 0,
    y: 0
  };
};
