// Generated by CoffeeScript 2.7.0
var getBezierPoint;

export default getBezierPoint = function(t) {
  var end, p0, p1, p2, p3, points, start, t1;
  points = this.getPoints();
  switch (points.length) {
    case 2:
      // 直线
      start = points[0];
      end = points[1];
      return {
        x: start.x + t * (end.x - start.x),
        y: start.y + t * (end.y - start.y)
      };
    case 3:
      // 二次贝塞尔曲线
      p0 = points[0];
      p1 = points[1];
      p2 = points[2];
      t1 = 1 - t;
      return {
        x: t1 * t1 * p0.x + 2 * t1 * t * p1.x + t * t * p2.x,
        y: t1 * t1 * p0.y + 2 * t1 * t * p1.y + t * t * p2.y
      };
    case 4:
      // 三次贝塞尔曲线
      p0 = points[0];
      p1 = points[1];
      p2 = points[2];
      p3 = points[3];
      t1 = 1 - t;
      return {
        x: t1 * t1 * t1 * p0.x + 3 * t1 * t1 * t * p1.x + 3 * t1 * t * t * p2.x + t * t * t * p3.x,
        y: t1 * t1 * t1 * p0.y + 3 * t1 * t1 * t * p1.y + 3 * t1 * t * t * p2.y + t * t * t * p3.y
      };
    default:
      console.log(points);
      throw new Error("异常的控制点个数");
  }
};
