// Generated by CoffeeScript 2.7.0
// 解三次方程 a*t^3 + b*t^2 + c*t + d = 0，返回所有实根
var solveCubic;

solveCubic = function(a, b, c, d) {
  var disc, mm, p, q, r, roots, sq, theta, u1;
  roots = [];
  // 退化为二次方程
  if (Math.abs(a) < 1e-10) {
    if (Math.abs(b) < 1e-10) {
      if (Math.abs(c) > 1e-10) {
        roots.push(-d / c);
      }
      return roots;
    }
    disc = c * c - 4 * b * d;
    if (disc >= 0) {
      sq = Math.sqrt(disc);
      roots.push((-c + sq) / (2 * b));
      roots.push((-c - sq) / (2 * b));
    }
    return roots;
  }
  // 归一化: t^3 + (b/a)t^2 + (c/a)t + (d/a) = 0
  b /= a;
  c /= a;
  d /= a;
  // 降阶替换 t = u - b/3  =>  u^3 + p*u + q = 0
  p = c - b * b / 3;
  q = 2 * b * b * b / 27 - b * c / 3 + d;
  disc = q * q / 4 + p * p * p / 27;
  if (Math.abs(disc) < 1e-10) {
    // 重根情况
    if (Math.abs(q) < 1e-10) {
      roots.push(-b / 3);
    } else {
      u1 = Math.cbrt(-q / 2);
      roots.push(2 * u1 - b / 3);
      roots.push(-u1 - b / 3);
    }
  } else if (disc > 0) {
    // 一个实根
    sq = Math.sqrt(disc);
    roots.push(Math.cbrt(-q / 2 + sq) + Math.cbrt(-q / 2 - sq) - b / 3);
  } else {
    // 三个实根（三角函数法）
    r = Math.sqrt(-p * p * p / 27);
    theta = Math.acos(Math.max(-1, Math.min(1, -q / (2 * r))));
    mm = 2 * Math.cbrt(r);
    roots.push(mm * Math.cos(theta / 3) - b / 3);
    roots.push(mm * Math.cos((theta + 2 * Math.PI) / 3) - b / 3);
    roots.push(mm * Math.cos((theta + 4 * Math.PI) / 3) - b / 3);
  }
  return roots;
};

export default function(otherElement, avoidPointInLine = false) {
  var A, B, C, P0, P1, P2, P3, a, ax, ay, b, bezierPoints, bx, by2, c, cubA, cubB, cubC, cubD, cubicRoots, cx, cy2, d, denom, discriminant, dx, dy, e, ele1, ele2, ex, existing, ey, f, i, intersectionPoints, intersections, isLineFirst, isUnique, j, k, l, len, len1, len2, len3, len4, linePoints, lx, ly, m, omt, point, points1, points2, px, py, ref, s, sampleLine, sampleLines, sqrt_disc, t, t1, t2, tmp, u, uniqueIntersections, x, x1, x2, x3, x4, y, y1, y2, y3, y4;
  intersections = [];
  
  // 获取两个元素的点数组
  points1 = this.getPoints();
  points2 = otherElement.getPoints();
  ele1 = this;
  ele2 = otherElement;
  if ((tmp = ele1.isPointInLine(ele2.s())) && !avoidPointInLine) {
    tmp.t1 = tmp.t;
    tmp.t2 = 0;
    delete tmp.t;
    intersections.push(tmp);
    console.log(1);
  } else if ((tmp = ele1.isPointInLine(ele2.e())) && !avoidPointInLine) {
    tmp.t1 = tmp.t;
    tmp.t2 = 0;
    delete tmp.t;
    intersections.push(tmp);
    console.log(2);
  } else if ((tmp = ele2.isPointInLine(ele1.s())) && !avoidPointInLine) {
    tmp.t2 = tmp.t;
    tmp.t1 = 0;
    delete tmp.t;
    intersections.push(tmp);
    console.log(3);
  } else if ((tmp = ele2.isPointInLine(ele1.e())) && !avoidPointInLine) {
    tmp.t2 = tmp.t;
    tmp.t1 = 0;
    delete tmp.t;
    intersections.push(tmp);
    console.log(4);
  
  // 直线与直线的交点
  } else if (points1.length === 2 && points2.length === 2) {
    
    //如果点在线上

    // 使用解析几何公式计算直线交点
    x1 = points1[0].x;
    y1 = points1[0].y;
    x2 = points1[1].x;
    y2 = points1[1].y;
    x3 = points2[0].x;
    y3 = points2[0].y;
    x4 = points2[1].x;
    y4 = points2[1].y;
    denom = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4);
    if (Math.abs(denom) > 1e-10) {
      t = ((x1 - x3) * (y3 - y4) - (y1 - y3) * (x3 - x4)) / denom;
      u = -((x1 - x2) * (y1 - y3) - (y1 - y2) * (x1 - x3)) / denom;
      if (t >= 0 && t <= 1 && u >= 0 && u <= 1) {
        intersections.push({
          x: x1 + t * (x2 - x1),
          y: y1 + t * (y2 - y1),
          t1: t, // 在第一条线上的参数
          t2: u // 在第二条线上的参数
        });
      }
    }
  
  // 直线与二次贝塞尔曲线的交点
  } else if ((points1.length === 2 && points2.length === 3) || (points1.length === 3 && points2.length === 2)) {
    [linePoints, bezierPoints] = points1.length === 2 ? [points1, points2] : [points2, points1];
    isLineFirst = points1.length === 2;
    
    // 参数化直线和贝塞尔曲线，求解二次方程
    dx = linePoints[1].x - linePoints[0].x;
    dy = linePoints[1].y - linePoints[0].y;
    a = bezierPoints[0].x - 2 * bezierPoints[1].x + bezierPoints[2].x;
    b = 2 * (bezierPoints[1].x - bezierPoints[0].x);
    c = bezierPoints[0].x - linePoints[0].x;
    d = bezierPoints[0].y - 2 * bezierPoints[1].y + bezierPoints[2].y;
    e = 2 * (bezierPoints[1].y - bezierPoints[0].y);
    f = bezierPoints[0].y - linePoints[0].y;
    
    // 求解 (a*t^2 + b*t + c) * dy - (d*t^2 + e*t + f) * dx = 0
    A = a * dy - d * dx;
    B = b * dy - e * dx;
    C = c * dy - f * dx;
    if (Math.abs(A) > 1e-10) {
      discriminant = B * B - 4 * A * C;
      if (discriminant >= 0) {
        sqrt_disc = Math.sqrt(discriminant);
        t1 = (-B + sqrt_disc) / (2 * A);
        t2 = (-B - sqrt_disc) / (2 * A);
        ref = [t1, t2];
        for (i = 0, len = ref.length; i < len; i++) {
          t = ref[i];
          if (t > 0 && t < 1) {
            x = bezierPoints[0].x * (1 - t) * (1 - t) + 2 * bezierPoints[1].x * (1 - t) * t + bezierPoints[2].x * t * t;
            y = bezierPoints[0].y * (1 - t) * (1 - t) + 2 * bezierPoints[1].y * (1 - t) * t + bezierPoints[2].y * t * t;
            
            // 检查点是否在直线段上
            if (dx !== 0) {
              s = (x - linePoints[0].x) / dx;
            } else {
              s = (y - linePoints[0].y) / dy;
            }
            if (s > 0 && s < 1) {
              if (isLineFirst) {
                intersections.push({
                  x: x,
                  y: y,
                  t1: s,
                  t2: t
                });
              } else {
                intersections.push({
                  x: x,
                  y: y,
                  t1: t,
                  t2: s
                });
              }
            }
          }
        }
      }
    }
  
  // 直线与三次贝塞尔曲线的交点（解析法）
  } else if ((points1.length === 2 && points2.length === 4) || (points1.length === 4 && points2.length === 2)) {
    [linePoints, bezierPoints] = points1.length === 2 ? [points1, points2] : [points2, points1];
    isLineFirst = points1.length === 2;
    // 直线方向向量
    lx = linePoints[1].x - linePoints[0].x;
    ly = linePoints[1].y - linePoints[0].y;
    // 三次贝塞尔展开为多项式: B(t) - L0 = at^3 + bt^2 + ct + d
    P0 = bezierPoints[0];
    P1 = bezierPoints[1];
    P2 = bezierPoints[2];
    P3 = bezierPoints[3];
    ax = -P0.x + 3 * P1.x - 3 * P2.x + P3.x;
    bx = 3 * P0.x - 6 * P1.x + 3 * P2.x;
    cx = -3 * P0.x + 3 * P1.x;
    ex = P0.x - linePoints[0].x;
    ay = -P0.y + 3 * P1.y - 3 * P2.y + P3.y;
    by2 = 3 * P0.y - 6 * P1.y + 3 * P2.y;
    cy2 = -3 * P0.y + 3 * P1.y;
    ey = P0.y - linePoints[0].y;
    // 代入直线方程: (B(t)-L0) × lineDir = 0  =>  A*t^3 + B*t^2 + C*t + D = 0
    cubA = ax * ly - ay * lx;
    cubB = bx * ly - by2 * lx;
    cubC = cx * ly - cy2 * lx;
    cubD = ex * ly - ey * lx;
    cubicRoots = solveCubic(cubA, cubB, cubC, cubD);
    for (j = 0, len1 = cubicRoots.length; j < len1; j++) {
      t = cubicRoots[j];
      if (t > 0 && t < 1) {
        // 计算贝塞尔曲线上的精确坐标
        omt = 1 - t;
        px = P0.x * omt * omt * omt + 3 * P1.x * omt * omt * t + 3 * P2.x * omt * t * t + P3.x * t * t * t;
        py = P0.y * omt * omt * omt + 3 * P1.y * omt * omt * t + 3 * P2.y * omt * t * t + P3.y * t * t * t;
        // 计算直线参数 s（选绝对值更大的分量避免除以接近零的数）
        if (Math.abs(lx) >= Math.abs(ly)) {
          s = (px - linePoints[0].x) / lx;
        } else {
          s = (py - linePoints[0].y) / ly;
        }
        if (s > 0 && s < 1) {
          if (isLineFirst) {
            intersections.push({
              x: px,
              y: py,
              t1: s,
              t2: t
            });
          } else {
            intersections.push({
              x: px,
              y: py,
              t1: t,
              t2: s
            });
          }
        }
      }
    }
  
  // 贝塞尔曲线与贝塞尔曲线的交点
  } else if (points1.length > 2 && points2.length > 2) {
    sampleLines = otherElement.getSmartSampleLines(2);
    for (k = 0, len2 = sampleLines.length; k < len2; k++) {
      sampleLine = sampleLines[k];
      intersectionPoints = this.getIntersectionPoints(sampleLine, true);
      intersectionPoints.forEach(function(point) {
        return point.t2 = sampleLine._tmp.sourceT;
      });
      intersections = intersections.concat(intersectionPoints);
    }
  }
  
  // 去重处理
  uniqueIntersections = [];
  for (l = 0, len3 = intersections.length; l < len3; l++) {
    point = intersections[l];
    isUnique = true;
    for (m = 0, len4 = uniqueIntersections.length; m < len4; m++) {
      existing = uniqueIntersections[m];
      if (Math.abs(point.x - existing.x) < 1e-6 && Math.abs(point.y - existing.y) < 1e-6) {
        isUnique = false;
        break;
      }
    }
    if (isUnique) {
      uniqueIntersections.push(point);
    }
  }
  return uniqueIntersections;
};
