// Generated by CoffeeScript 2.7.0
export default function(targetPoint) {
  var bestDistance, bestT, currentPoint, d2f, deltaT, derivative, df, distance, dotProduct, dx, dy, finalPoint, i, initialPoints, initialT, iteration, j, len, lengthSquared, maxIterations, newT, p0, p1, points, px, py, ref, secondDerivative, t;
  points = this.getPoints();
  if (points.length === 2) {
    // 直线情况 - 使用解析解
    p0 = points[0];
    p1 = points[1];
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;
    px = targetPoint.x - p0.x;
    py = targetPoint.y - p0.y;
    dotProduct = px * dx + py * dy;
    lengthSquared = dx * dx + dy * dy;
    if (lengthSquared < 1e-10) {
      return 0;
    }
    t = dotProduct / lengthSquared;
    return Math.max(0, Math.min(1, t));
  } else if (points.length === 3 || points.length === 4) {
    // 贝塞尔曲线情况 - 使用数值优化
    bestT = 0;
    bestDistance = 2e308;
    
    // 多个初始点避免局部最优
    initialPoints = points.length === 3 ? [0, 0.25, 0.5, 0.75, 1] : [0, 0.2, 0.4, 0.6, 0.8, 1];
    maxIterations = points.length === 3 ? 10 : 15;
    for (i = 0, len = initialPoints.length; i < len; i++) {
      initialT = initialPoints[i];
      t = initialT;

      // 牛顿-拉夫逊法迭代求解最小距离点
      for (iteration = j = 0, ref = maxIterations; (0 <= ref ? j < ref : j > ref); iteration = 0 <= ref ? ++j : --j) {
        // 计算当前点B(t)
        currentPoint = this.getBezierPoint(t);
        
        // 计算一阶导数B'(t)
        derivative = this.getBezierDerivative(t);
        
        // 计算二阶导数B''(t)
        secondDerivative = this.getBezier2Derivative(t);
        
        // 计算距离函数的导数
        dx = currentPoint.x - targetPoint.x;
        dy = currentPoint.y - targetPoint.y;
        
        // f'(t) = 2 * (B(t) - P) · B'(t)
        df = 2 * (dx * derivative.x + dy * derivative.y);
        
        // f''(t) = 2 * (B'(t) · B'(t) + (B(t) - P) · B''(t))
        d2f = 2 * (derivative.x * derivative.x + derivative.y * derivative.y + dx * secondDerivative.x + dy * secondDerivative.y);
        if (Math.abs(d2f) < 1e-10) {
          break;
        }
        
        // 牛顿-拉夫逊更新
        deltaT = df / d2f;
        newT = Math.max(0, Math.min(1, t - deltaT));
        
        // 检查收敛
        if (Math.abs(newT - t) < 1e-8) {
          t = newT;
          break;
        }
        t = newT;
      }
      
      // 计算最终距离
      finalPoint = this.getBezierPoint(t);
      distance = Math.sqrt((finalPoint.x - targetPoint.x) ** 2 + (finalPoint.y - targetPoint.y) ** 2);
      if (distance < bestDistance) {
        bestDistance = distance;
        bestT = t;
      }
    }
    return bestT;
  }
  return 0;
};
