// Generated by CoffeeScript 2.7.0
export default function(element2) {
  var crossProduct, element1, element1SimpaleLines, element2SimpaleLines, i, j, k, len, len1, len2, line1, line2, lineIntersectsLine, siteEqual;
  // 判断两条线段是否相交的核心函数
  crossProduct = (v1, v2) => {
    return v1.x * v2.y - v1.y * v2.x;
  };
  lineIntersectsLine = (p1, p2, p3, p4) => {
    var d1, d2, d3, d4, intersection;
    d1 = crossProduct({
      x: p4.x - p3.x,
      y: p4.y - p3.y
    }, {
      x: p1.x - p3.x,
      y: p1.y - p3.y
    });
    d2 = crossProduct({
      x: p4.x - p3.x,
      y: p4.y - p3.y
    }, {
      x: p2.x - p3.x,
      y: p2.y - p3.y
    });
    d3 = crossProduct({
      x: p2.x - p1.x,
      y: p2.y - p1.y
    }, {
      x: p3.x - p1.x,
      y: p3.y - p1.y
    });
    d4 = crossProduct({
      x: p2.x - p1.x,
      y: p2.y - p1.y
    }, {
      x: p4.x - p1.x,
      y: p4.y - p1.y
    });
    intersection = ((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) && ((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0));
    return intersection;
  };
  siteEqual = function(site1, site2) {
    return site1.x === site2.x && site1.y === site2.y;
  };
  element1 = this;
  if (element1.getPoints().length === 2 && element2.getPoints().length === 2) {
    //点在线上且不是端点
    if (element2.isPointInLine(element1.s()) || element2.isPointInLine(element1.s()) || element1.isPointInLine(element2.s()) || element1.isPointInLine(element2.s()) || element2.isPointInLine(element1.e()) || element2.isPointInLine(element1.e()) || element1.isPointInLine(element2.e()) || element1.isPointInLine(element2.e())) {
      return true;
    }
    return lineIntersectsLine(element1.s(), element1.e(), element2.s(), element2.e());
  }
  if (element1.getPoints().length === 2 && element2.getPoints().length > 2) {
    element2SimpaleLines = element2.getSmartSampleLines(0.3);
    for (i = 0, len = element2SimpaleLines.length; i < len; i++) {
      line2 = element2SimpaleLines[i];
      if (element1.isIntersectLine(line2)) {
        return true;
      }
    }
  }
  if (element2.getPoints().length === 2 && element1.getPoints().length > 2) {
    return element2.isIntersectLine(element1);
  }
  if (element1.getPoints().length > 2 && element2.getPoints().length > 2) {
    element1SimpaleLines = element1.getSmartSampleLines(0.3);
    element2SimpaleLines = element2.getSmartSampleLines(0.3);
    for (j = 0, len1 = element1SimpaleLines.length; j < len1; j++) {
      line1 = element1SimpaleLines[j];
      for (k = 0, len2 = element2SimpaleLines.length; k < len2; k++) {
        line2 = element2SimpaleLines[k];
        if (line1.isIntersectLine(line2)) {
          return true;
        }
      }
    }
  }
  return false;
};
