// Generated by CoffeeScript 2.7.0
import svgElement from "../svgEditor_element.js";

import tools from "../../tools.js";

export default function(t = 0.5) {
  var leftElement, p01, p012, p0123, p12, p123, p23, points, rightElement, splitPoint;
  if ((Math.abs(t - 0) <= 1e-10) || (Math.abs(t - 1) <= 1e-10)) {
    return [];
  }
  if (t <= 0 || t >= 1) {
    return [];
  }
  points = this.getPoints();
  leftElement = new svgElement({
    type: this.type,
    id: tools.uuid(),
    prop: {
      fill: this.prop.fill,
      stroke: this.prop.stroke,
      strokeWidth: this.prop.strokeWidth,
      strokeLinecap: this.prop.strokeLinecap,
      parentGroup: this.prop.parentGroup,
      points: []
    },
    isChoised: this.isChoised,
    isActive: this.isActive
  });
  rightElement = new svgElement({
    type: this.type,
    id: tools.uuid(),
    prop: {
      fill: this.prop.fill,
      stroke: this.prop.stroke,
      strokeWidth: this.prop.strokeWidth,
      strokeLinecap: this.prop.strokeLinecap,
      parentGroup: this.prop.parentGroup,
      points: []
    },
    isChoised: this.isChoised,
    isActive: this.isActive
  });
  if (points.length === 2) {
    // 直线分割
    splitPoint = {
      x: points[0].x + t * (points[1].x - points[0].x),
      y: points[0].y + t * (points[1].y - points[0].y)
    };
    leftElement.prop.points = [
      {
        x: points[0].x,
        y: points[0].y
      },
      {
        x: splitPoint.x,
        y: splitPoint.y
      }
    ];
    rightElement.prop.points = [
      {
        x: splitPoint.x,
        y: splitPoint.y
      },
      {
        x: points[1].x,
        y: points[1].y
      }
    ];
    return [leftElement, rightElement];
  } else if (points.length === 3) {
    // 二次贝塞尔分割 - 德卡斯特里奥算法
    p01 = {
      x: points[0].x + t * (points[1].x - points[0].x),
      y: points[0].y + t * (points[1].y - points[0].y)
    };
    p12 = {
      x: points[1].x + t * (points[2].x - points[1].x),
      y: points[1].y + t * (points[2].y - points[1].y)
    };
    p012 = {
      x: p01.x + t * (p12.x - p01.x),
      y: p01.y + t * (p12.y - p01.y)
    };
    leftElement.prop.points = [
      {
        x: points[0].x,
        y: points[0].y
      },
      {
        x: p01.x,
        y: p01.y
      },
      {
        x: p012.x,
        y: p012.y
      }
    ];
    rightElement.prop.points = [
      {
        x: p012.x,
        y: p012.y
      },
      {
        x: p12.x,
        y: p12.y
      },
      {
        x: points[2].x,
        y: points[2].y
      }
    ];
    return [leftElement, rightElement];
  } else if (points.length === 4) {
    // 三次贝塞尔分割 - 德卡斯特里奥算法
    p01 = {
      x: points[0].x + t * (points[1].x - points[0].x),
      y: points[0].y + t * (points[1].y - points[0].y)
    };
    p12 = {
      x: points[1].x + t * (points[2].x - points[1].x),
      y: points[1].y + t * (points[2].y - points[1].y)
    };
    p23 = {
      x: points[2].x + t * (points[3].x - points[2].x),
      y: points[2].y + t * (points[3].y - points[2].y)
    };
    p012 = {
      x: p01.x + t * (p12.x - p01.x),
      y: p01.y + t * (p12.y - p01.y)
    };
    p123 = {
      x: p12.x + t * (p23.x - p12.x),
      y: p12.y + t * (p23.y - p12.y)
    };
    p0123 = {
      x: p012.x + t * (p123.x - p012.x),
      y: p012.y + t * (p123.y - p012.y)
    };
    leftElement.prop.points = [
      {
        x: points[0].x,
        y: points[0].y
      },
      {
        x: p01.x,
        y: p01.y
      },
      {
        x: p012.x,
        y: p012.y
      },
      {
        x: p0123.x,
        y: p0123.y
      }
    ];
    rightElement.prop.points = [
      {
        x: p0123.x,
        y: p0123.y
      },
      {
        x: p123.x,
        y: p123.y
      },
      {
        x: p23.x,
        y: p23.y
      },
      {
        x: points[3].x,
        y: points[3].y
      }
    ];
    return [leftElement, rightElement];
  }
  
  // 不支持的点数量
  throw new Error("不支持的控制点数量: " + points.length);
};
