// Generated by CoffeeScript 2.7.0
var UiText;

import data from "./svgEditor_data.js";

export default UiText = class UiText {
  constructor() {
    this.active = false;
    this.x = 0;
    this.y = 0;
    this.w = 200;
    this.h = 50;
    this.text = "";
    this.mode = "svg"; // 'svg' 或 'markdown'
    this.fontSize = 24;
    this.fontFamily = "Arial";
    this.color = "#000000";
    this.targetElement = null;
  }

  reset() {
    var ref;
    this.active = false;
    this.x = 0;
    this.y = 0;
    this.w = 200;
    this.h = 50;
    this.text = "";
    this.mode = "svg";
    this.fontSize = 24;
    this.color = ((ref = data.colorTool) != null ? ref.fgColor : void 0) || "#000000";
    return this.targetElement = null;
  }

};
