// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import Setting from "./svgEditor_setting.js";

import tools from "../tools.js";

import ColorWindow from "./svgEditor_colorWindow.js";

export default function() {
  var Box, Tip, getCurrentRingIndex, getCurrentRingToolsCount, getRingCount, getToolInCurrentRingIndex, getToolsCountUpToCurrentRing;
  ({Box, Tip} = tools);
  getRingCount = (toolsLength) => {
    if (toolsLength <= 0) {
      return 0;
    }
    return Math.ceil((-3 + Math.sqrt(9 + 4 * toolsLength)) / 2);
  };
  getCurrentRingIndex = (toolIndex) => {
    var cumulativeTools, ringIndex;
    if (toolIndex < 0) {
      return 0;
    }
    // 计算累计工具数直到刚好超过当前工具索引
    ringIndex = 0;
    cumulativeTools = 0;
    while (cumulativeTools <= toolIndex) {
      cumulativeTools += 4 + 2 * ringIndex;
      ringIndex++;
    }
    // 返回调整后的环索引
    return ringIndex - 1;
  };
  getCurrentRingToolsCount = (currentRingIndex) => {
    return 4 + 2 * currentRingIndex;
  };
  getToolsCountUpToCurrentRing = (currentRingIndex) => {
    var i, j, ref, sum;
    sum = 0;
    for (i = j = 0, ref = currentRingIndex; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
      sum += getCurrentRingToolsCount(i);
    }
    return sum;
  };
  getToolInCurrentRingIndex = (toolIndex) => {
    if (toolIndex <= 3) {
      return toolIndex;
    } else {
      return toolIndex - getToolsCountUpToCurrentRing(getCurrentRingIndex(toolIndex) - 1);
    }
  };
  return {
    view: function() {
      var barR, ref, ringCount, unitLength;
      ringCount = getRingCount(data.tools.length);
      unitLength = 7;
      barR = unitLength + unitLength * ringCount;
      return m("", {
        style: {
          position: "absolute",
          bottom: 0,
          left: 0,
          width: `${barR * 2}rem`,
          height: `${barR * 2}rem`,
          transform: "translate(-50%, 50%)",
          borderRadius: "50%",
          background: "#eee",
          boxShadow: "0 0 1rem rgba(0,0,0,0.2)",
          clipPath: "circle(52% at 50% 50%)"
        }
      }, [
        m("",
        {
          style: {
            width: "100%",
            height: "100%",
            position: "relative",
            display: "flex",
            justifyContent: "center",
            alignItems: "center"
          }
        },
        [
          (function() {
            var results = [];
            for (var j = 1, ref = ringCount + 1; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--){ results.push(j); }
            return results;
          }).apply(this).map((i) => {
            return m("",
          {
              style: {
                width: `${i * unitLength * 2}rem`,
                height: `${i * unitLength * 2}rem`,
                borderRadius: "50%",
                position: "absolute",
                border: "0.1rem solid #ccc"
              }
            },
          []);
          }),
          //中心调色盘
          m("",
          {
            style: {
              width: `${unitLength * 2}rem`,
              height: `${unitLength * 2}rem`,
              borderRadius: "50%",
              background: data.colorTool.bgColor,
              zIndex: 10,
              overflow: "hidden",
              cursor: "pointer"
            },
            onclick: () => {
              data.colorTool.presentColor = "full";
              return Notice.launch({
                content: ColorWindow,
                tip: "颜色选择"
              });
            }
          },
          [
            m("",
            {
              style: {
                width: "100%",
                height: "100%",
                background: data.colorTool.fgColor,
                transformOrigion: "center center",
                transform: "rotate(-25deg) translate(0,50%)",
                cursor: "pointer"
              },
              onclick: (e) => {
                e.stopPropagation();
                data.colorTool.presentColor = "stroke";
                return Notice.launch({
                  content: ColorWindow,
                  tip: "颜色选择"
                });
              }
            })
          ]),
          data.tools.map((tool,
          index) => {
            var angle,
          perAngle,
          r,
          toolInCurrentRingIndex,
          x,
          y;
            perAngle = (Math.PI / 2) / getCurrentRingToolsCount(getCurrentRingIndex(index));
            r = unitLength / 2 + 2 * (unitLength / 2) * (getCurrentRingIndex(index) + 1);
            toolInCurrentRingIndex = getToolInCurrentRingIndex(index);
            angle = perAngle * toolInCurrentRingIndex + (perAngle / 2);
            x = r * Math.cos(angle);
            y = r * Math.sin(angle);
            return m(Box,
          {
              color: data.getPresentTool().name === tool.name ? "main" : void 0,
              isBtn: true,
              style: {
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                position: "absolute",
                transformOrigion: "center center",
                transform: `translate(${x}rem,-${y}rem)`,
                zIndex: data.getPresentTool().name === tool.name ? 1 : void 0,
                width: "4rem",
                height: "4rem",
                padding: 0,
                margin: 0
              },
              onclick: () => {
                if (tool.name === "setting") {
                  return Notice.launch({
                    tip: "设置",
                    content: Setting
                  });
                } else {
                  data.presentTool = index;
                  return Tip.launch(tool.title,
          100);
                }
              }
            },
          [tool.icon ? m("span",
          m.trust(tool.icon)) : m("span",
          tool.title)]);
          })
        ])
      ]);
    }
  };
};
