// Generated by CoffeeScript 2.7.0
var ElPaper,
  indexOf = [].indexOf;

import Element from "./svgEditor_paper.js";

import pointToBezierDisSquare from "./tools/pointToBezierDisSquare.js";

import pointToLineDisSquare from "./tools/pointToLineDisSquare.js";

import data from "./svgEditor_data.js";

import Group from "./svgEditor_group.js";

import SvgSerializer from "./svgEditor_serialize.js";

import tools from "../tools.js";

export default ElPaper = class ElPaper {
  constructor() {
    this.elements = [];
    this.vertices = {};
  }

  getList() {
    return this.elements;
  }

  getLines() {
    return this.elements.filter(function(element) {
      return element.type === "line";
    });
  }

  getFillGroups() {
    return this.elements.filter(function(element) {
      return element.type === "fillGroup";
    });
  }

  getPureFill() {
    return this.elements.filter(function(element) {
      return element.type === "pureFill";
    });
  }

  getChoisedElements() {
    return this.elements.filter((element) => {
      return element.isChoised;
    });
  }

  add(element) {
    if (!(element instanceof Element.constructor)) {
      console.log("错误元素");
      throw new Error("错误元素");
    }
    return this.elements.push(element);
  }

  remove(element) {
    var gIndex, ref, rmIndex;
    rmIndex = this.elements.indexOf(element);
    if (rmIndex !== -1) {
      this.elements.splice(rmIndex, 1);
    }
    if ((ref = element.prop) != null ? ref.parentGroup : void 0) {
      gIndex = element.prop.parentGroup.prop.elements.indexOf(element);
      if (gIndex !== -1) {
        return element.prop.parentGroup.prop.elements.splice(gIndex, 1);
      }
    }
  }

  removeAndClear(element) {
    var cloneElements, ref;
    if (element.type === "line") {
      element.getFillGroups().forEach((fillGroup) => {
        return fillGroup.break();
      });
      this.remove(element);
    }
    if (element.type === "fillGroup") {
      element.break();
      this.remove(element); //重复删除了，break已经带有删除
    }
    if (element.type === "pureFill") {
      element.getFillGroups().forEach((fillGroup) => {
        return fillGroup.break();
      });
      this.remove(element);
    }
    if (element.type === "group") {
      cloneElements = [...element.prop.elements];
      element.break();
      cloneElements.forEach((child) => {
        return this.removeAndClear(child);
      });
    }
    if ((ref = element.type) !== "line" && ref !== "fillGroup" && ref !== "pureFill" && ref !== "group") {
      return this.remove(element);
    }
  }

  removeChosiedElements() {
    return [...this.getChoisedElements()].forEach((el) => {
      if (el.isChoised) {
        return this.removeAndClear(el);
      }
    });
  }

  copyChoisedElements() {
    var choisedEls, snapshotList;
    choisedEls = this.getChoisedElements();
    if (choisedEls.length === 0) {
      return;
    }
    
    // 收集选中的元素及其子元素，交给序列化器
    // 注意: SvgSerializer 内部可能也会收集递归依赖，但为了确保，直接传最外层选中的元素给它即可。
    snapshotList = SvgSerializer.serializeElements(choisedEls);
    data.clipboardSnapshot = snapshotList;
    return choisedEls.forEach(function(el) {
      return el.isChoised = false;
    });
  }

  cutChoisedElements() {
    this.copyChoisedElements();
    return this.removeChosiedElements();
  }

  pasteChoisedElements() {
    var el, elements, j, len, results, topLevelElements;
    if (!data.clipboardSnapshot || data.clipboardSnapshot.length === 0) {
      return;
    }
    
      // 由 SvgSerializer 统一处理 UUID 重新分配、指针重组与顶层元素鉴定
    ({elements, topLevelElements} = SvgSerializer.deserializeElements(data.clipboardSnapshot, {
      assignNewIds: true,
      returnStruct: true
    }));
    
    // 取消当前选择
    this.getChoisedElements().forEach(function(el) {
      return el.isChoised = false;
    });
    
    // 顶级元素代理平移、高亮与进组
    topLevelElements.forEach(function(topEl) {
      if (typeof topEl.translate === "function") {
        topEl.translate({
          deltaX: 40,
          deltaY: 40
        });
      }
      topEl.isChoised = true;
      if (data.presentGroup) {
        return topEl.joinGroup(data.presentGroup);
      } else {
        return topEl.prop.parentGroup = null;
      }
    });
// 遵从系统原生规则：纯填充使用 unshift（沉入底层），线条/组/其他图元使用 push（置于顶层）
    results = [];
    for (j = 0, len = elements.length; j < len; j++) {
      el = elements[j];
      if (el.type === "pureFill") {
        results.push(this.elements.unshift(el));
      } else {
        results.push(this.elements.push(el));
      }
    }
    return results;
  }

  layerUpChoisedElements() {
    var group, i, idx, j, k, len, parentGroup, ref, ref1, ref2, ref3, results, selectedGroups, siblingGroups, targetGroup, targetIdx;
    selectedGroups = this.getChoisedElements().filter((el) => {
      return el.type === "group";
    });
    if (selectedGroups.length === 0) {
      return;
    }
    selectedGroups.sort((a, b) => {
      return this.elements.indexOf(b) - this.elements.indexOf(a);
    });
    results = [];
    for (j = 0, len = selectedGroups.length; j < len; j++) {
      group = selectedGroups[j];
      parentGroup = (ref = group.prop) != null ? ref.parentGroup : void 0;
      siblingGroups = this.elements.filter((el) => {
        var ref1;
        return el.type === "group" && ((ref1 = el.prop) != null ? ref1.parentGroup : void 0) === parentGroup;
      });
      idx = siblingGroups.indexOf(group);
      targetGroup = null;
      if (idx < siblingGroups.length - 1) {
        for (i = k = ref1 = idx + 1, ref2 = siblingGroups.length; (ref1 <= ref2 ? k < ref2 : k > ref2); i = ref1 <= ref2 ? ++k : --k) {
          if (ref3 = siblingGroups[i], indexOf.call(selectedGroups, ref3) < 0) {
            targetGroup = siblingGroups[i];
            break;
          }
        }
      }
      if (targetGroup) {
        this.elements.splice(this.elements.indexOf(group), 1);
        targetIdx = this.elements.indexOf(targetGroup);
        results.push(this.elements.splice(targetIdx + 1, 0, group));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }

  layerDownChoisedElements() {
    var group, i, idx, j, k, len, parentGroup, ref, ref1, ref2, results, selectedGroups, siblingGroups, targetGroup, targetIdx;
    selectedGroups = this.getChoisedElements().filter((el) => {
      return el.type === "group";
    });
    if (selectedGroups.length === 0) {
      return;
    }
    selectedGroups.sort((a, b) => {
      return this.elements.indexOf(a) - this.elements.indexOf(b);
    });
    results = [];
    for (j = 0, len = selectedGroups.length; j < len; j++) {
      group = selectedGroups[j];
      parentGroup = (ref = group.prop) != null ? ref.parentGroup : void 0;
      siblingGroups = this.elements.filter((el) => {
        var ref1;
        return el.type === "group" && ((ref1 = el.prop) != null ? ref1.parentGroup : void 0) === parentGroup;
      });
      idx = siblingGroups.indexOf(group);
      targetGroup = null;
      if (idx > 0) {
        for (i = k = ref1 = idx - 1; k >= 0; i = k += -1) {
          if (ref2 = siblingGroups[i], indexOf.call(selectedGroups, ref2) < 0) {
            targetGroup = siblingGroups[i];
            break;
          }
        }
      }
      if (targetGroup) {
        this.elements.splice(this.elements.indexOf(group), 1);
        targetIdx = this.elements.indexOf(targetGroup);
        results.push(this.elements.splice(targetIdx, 0, group));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }

  becomeGroup(name = "") {
    var group, missingFillGroups, selected;
    selected = this.getChoisedElements();
    if (selected.length < 1) {
      return;
    }
    
    // 二次遍历：找出被遗落在外面的 fillGroup
    missingFillGroups = [];
    selected.forEach((el) => {
      var ref;
      if ((ref = el.prop) != null ? ref.fillGroups : void 0) {
        return el.prop.fillGroups.forEach((fg) => {
          if (selected.indexOf(fg) === -1 && missingFillGroups.indexOf(fg) === -1) {
            return missingFillGroups.push(fg);
          }
        });
      }
    });
    missingFillGroups.forEach((fg) => {
      return selected.push(fg);
    });
    group = new Group({
      prop: {
        name: name,
        elements: selected
      }
    });
    
    // 继承父组
    if (data.presentGroup) {
      group.joinGroup(data.presentGroup);
    }
    selected.forEach((el) => {
      el.joinGroup(group);
      return el.isChoised = false;
    });
    this.add(group);
    group.isChoised = true;
    
    // 更新自身的边界
    return group.update();
  }

  exitGroup() {
    var selectedGroups;
    // 全拆散
    selectedGroups = this.getChoisedElements().filter((el) => {
      return el.type === "group";
    });
    return selectedGroups.forEach((group) => {
      var recurseExit;
      recurseExit = (g) => {
        var missingFillGroups;
        // 先收集落在外面或者其他地方的 fillGroup
        missingFillGroups = [];
        g.prop.elements.forEach((child) => {
          var ref;
          if ((ref = child.prop) != null ? ref.fillGroups : void 0) {
            return child.prop.fillGroups.forEach((fg) => {
              if (g.prop.elements.indexOf(fg) === -1 && missingFillGroups.indexOf(fg) === -1) {
                return missingFillGroups.push(fg);
              }
            });
          }
        });
        
        // 让它们也退到跟 g 同级的环境
        missingFillGroups.forEach((fg) => {
          if (fg.prop.parentGroup) {
            fg.exitGroup(fg.prop.parentGroup);
          }
          if (g.prop.parentGroup) {
            return fg.joinGroup(g.prop.parentGroup);
          }
        });
        g.prop.elements.slice().forEach((child) => {
          child.exitGroup(g);
          if (child.type === "group") {
            return recurseExit(child);
          }
        });
        return this.remove(g);
      };
      return recurseExit(group);
    });
  }

  exitPresentGroup() {
    var selectedGroups;
    // 拆一层
    selectedGroups = this.getChoisedElements().filter((el) => {
      return el.type === "group";
    });
    return selectedGroups.forEach((group) => {
      var missingFillGroups;
      missingFillGroups = [];
      group.prop.elements.forEach((child) => {
        var ref;
        if ((ref = child.prop) != null ? ref.fillGroups : void 0) {
          return child.prop.fillGroups.forEach((fg) => {
            if (group.prop.elements.indexOf(fg) === -1 && missingFillGroups.indexOf(fg) === -1) {
              return missingFillGroups.push(fg);
            }
          });
        }
      });
      missingFillGroups.forEach((fg) => {
        if (fg.prop.parentGroup) {
          fg.exitGroup(fg.prop.parentGroup);
        }
        if (group.prop.parentGroup) {
          return fg.joinGroup(group.prop.parentGroup);
        }
      });
      group.prop.elements.slice().forEach((child) => {
        return child.exitGroup(group);
      });
      return this.remove(group);
    });
  }

  getVertices() {
    this.vertices = {};
    this.getLines().forEach((element) => {
      var e, s;
      s = {...element.s()};
      e = {...element.e()};
      [s, e].forEach((site) => {
        var siteStr;
        siteStr = JSON.stringify(site);
        if (!this.vertices[siteStr]) {
          this.vertices[siteStr] = {
            site: {
              x: site.x,
              y: site.y
            },
            elements: [],
            children: [],
            addElement: function(element) {
              if (this.elements.indexOf(element) === -1) {
                return this.elements.push(element);
              }
            },
            addChild: function(vertex, element) {
              if (!this.children.find((child) => {
                return child.linkVertex === vertex && child.element === element;
              })) {
                return this.children.push({
                  linkVertex: vertex,
                  element: element
                });
              }
            },
            removeChild: function(vertex, element) {
              var childIndex;
              //双向删除
              childIndex = this.children.findIndex((child) => {
                if (element) {
                  return child.linkVertex === vertex && child.element === element;
                } else {
                  return child.linkVertex === vertex;
                }
              });
              if (childIndex !== -1) {
                return this.children.splice(childIndex, 1);
              }
            },
            removeChildEachOther: function(vertex, element) {
              this.removeChild(vertex, element);
              return vertex.removeChild(this, element);
            }
          };
          return this.vertices[siteStr].addElement(element);
        } else {
          return this.vertices[siteStr].addElement(element);
        }
      });
      this.vertices[JSON.stringify(s)].addChild(this.vertices[JSON.stringify(e)], element);
      return this.vertices[JSON.stringify(e)].addChild(this.vertices[JSON.stringify(s)], element);
    });
    return this.vertices;
  }

  getAllPoints() {
    var points;
    points = [];
    this.getLines().forEach((element) => {
      return [element.s(), element.e()].forEach((site) => {
        return points.push(site);
      });
    });
    return points;
  }

  findSameSitePoints(site) {
    return this.getAllPoints().filter((point) => {
      return point.x === site.x && point.y === site.y;
    });
  }

  findSameSiteLines(site) {
    var lines;
    lines = [];
    this.getLines().forEach((element) => {
      if ((element.s().x === site.x && element.s().y === site.y) || (element.e().x === site.x && element.e().y === site.y)) {
        return lines.push(element);
      }
    });
    return lines;
  }

  getClosedLine(site) {
    var closestLine, element, j, len, minDistanceSq, ref;
    minDistanceSq = 2e308;
    closestLine = null;
    ref = this.getLines();
    for (j = 0, len = ref.length; j < len; j++) {
      element = ref[j];
      // 作用域防穿透
      if (data.presentGroup && !(element === data.presentGroup || data.presentGroup.hasElementDeep(element))) {
        continue;
      }
      ((element) => {
        var controlPoints, distanceSq, end, localSite, start;
        localSite = element.globalToLocal(site);
        start = element.s();
        end = element.e();
        controlPoints = element.getControlPoints();
        if (controlPoints.length === 0) {
          distanceSq = pointToLineDisSquare(localSite.x, localSite.y, start.x, start.y, end.x, end.y);
        } else {
          distanceSq = pointToBezierDisSquare(localSite.x, localSite.y, element.prop.points);
        }
        if (distanceSq < minDistanceSq) {
          minDistanceSq = distanceSq;
          return closestLine = element;
        }
      })(element);
    }
    return {
      line: closestLine,
      dis: minDistanceSq
    };
  }

  
    //site期待为全局坐标，如果是元素坐标，需要转成全局坐标
  getClosedSite(site, excludeLines, excludeSites, speed) {
    var closed, element, index;
    closed = {
      site: null,
      dis: 2e308,
      element: null
    };
    index = this.elements.length - 1;
    while (index >= 0) {
      element = this.elements[index];
      if (element.type !== "line") {
        index--;
        continue;
      }
      if (data.presentGroup && !(element === data.presentGroup || data.presentGroup.hasElementDeep(element))) {
        index--;
        continue;
      }
      ((element) => {
        var dis1, dis2, dis3, disEndpointLinePoint, globalPresentSite, inverseMatrix, localSite, presentDis, presentSite, projectPoint, projectT;
        localSite = element.globalToLocal(site);
        projectT = element.getProjectionT(localSite);
        projectPoint = element.getBezierPoint(projectT);
        projectPoint.t = projectT;
        dis1 = (localSite.x - element.s().x) ** 2 + (localSite.y - element.s().y) ** 2;
        dis2 = (localSite.x - element.e().x) ** 2 + (localSite.y - element.e().y) ** 2;
        dis3 = (localSite.x - projectPoint.x) ** 2 + (localSite.y - projectPoint.y) ** 2;
        if (excludeLines) {
          if ((speed && speed > 10) || !speed) {
            excludeLines.forEach((exLine) => {
              if (element === exLine) {
                dis1 = 2e308;
                dis2 = 2e308;
                return dis3 = 2e308;
              }
            });
          }
        }
        if (excludeSites) { //排除点
          inverseMatrix = element.getGlobalMatrix().inverse();
          // 因为 excludeSites 可能是全局传入的，需要做逆转换，或者在这里如果只作拓扑点比较，我们就先保持
          excludeSites.forEach((exSite) => {
            var exLocal;
            exLocal = element.globalToLocal(exSite, inverseMatrix);
            if ((element.s().x - exLocal.x) ** 2 + (element.s().y - exLocal.y) ** 2 <= 0) {
              dis1 = 2e308;
            }
            if ((element.e().x - exLocal.x) ** 2 + (element.e().y - exLocal.y) ** 2 <= 0) {
              dis2 = 2e308;
            }
            if ((projectPoint.x - exLocal.x) ** 2 + (projectPoint.y - exLocal.y) ** 2 <= 0) {
              return dis3 = 2e308;
            }
          });
        }
        if (dis1 < dis2) {
          presentDis = dis1;
          presentSite = element.s();
        } else {
          presentDis = dis2;
          presentSite = element.e();
        }
        disEndpointLinePoint = (presentSite.x - projectPoint.x) ** 2 + (presentSite.y - projectPoint.y) ** 2;
        if (disEndpointLinePoint > (data.cursorTool.pointSnapR / data.globalZoom) ** 2) {
          presentDis = dis3;
          presentSite = projectPoint;
        }
        globalPresentSite = element.localToGlobal(presentSite);
        if (closed.site == null) {
          closed.site = globalPresentSite;
        }
        if (presentDis < closed.dis) {
          closed.site = {...globalPresentSite};
          closed.dis = presentDis;
          return closed.element = element;
        }
      })(element);
      index--;
    }
    return closed;
  }

  getClosedFillGroup(site) {
    return this.elements.find((el) => {
      var localSite;
      if (el.type !== "fillGroup") {
        return false;
      }
      if (data.presentGroup && !(el === data.presentGroup || data.presentGroup.hasElementDeep(el))) {
        return false;
      }
      
      // 转化为局部坐标
      localSite = el.globalToLocal(site);
      return el.isPointInRegion(localSite);
    });
  }

  getClosedPureFill(site) {
    return this.elements.find((el) => {
      var localSite;
      if (el.type !== "pureFill") {
        return false;
      }
      if (data.presentGroup && !(el === data.presentGroup || data.presentGroup.hasElementDeep(el))) {
        return false;
      }
      localSite = el.globalToLocal(site);
      return el.isPointInRegion(localSite);
    });
  }

  translateChoisedElements(deltaX, deltaY, preBreakFillGroups) {
    var choisedElements;
    choisedElements = this.getChoisedElements();
    //特别备注，无需平移填充组，因为切割器会根据独立的纯填充自动重建填充组
    return choisedElements.forEach((el) => {
      var ref;
      if (el.type === "line") {
        el.translate({deltaX, deltaY});
        if (preBreakFillGroups) {
          return el.prop.fillGroups.forEach((fillGroup) => {
            return preBreakFillGroups.push(fillGroup);
          });
        }
      } else if (el.type === "pureFill") {
        el.translate({deltaX, deltaY});
        if (preBreakFillGroups && ((ref = el.prop.fillGroups) != null ? ref[0] : void 0)) {
          return preBreakFillGroups.push(el.prop.fillGroups[0]);
        }
      } else if (el.type === "group") {
        return el.translate({deltaX, deltaY});
      } else if (el.type === "text") {
        return el.translate({deltaX, deltaY});
      }
    });
  }

  importSvg(svgString, presentGroup) {
    var jsonData, match, snapshotList, struct;
    match = svgString.match(/<script type="application\/json" id="owo-meta">([\s\S]*?)<\/script>/);
    if (!match) {
      return false;
    }
    jsonData = match[1].trim();
    snapshotList = JSON.parse(jsonData);
    
    // 重新分配新 ID 导入，避免在同一个画布中多次导入导致 ID 冲突
    struct = SvgSerializer.deserializeElements(snapshotList, {
      assignNewIds: true,
      returnStruct: true
    });
    
    // 绑定顶级图元至当前的隔离组中
    struct.topLevelElements.forEach(function(el) {
      el.prop.parentGroup = presentGroup;
      if (presentGroup) {
        return presentGroup.prop.elements.push(el);
      }
    });
    
    // 将所有的图元实例推入画布的全局元素列表中以供渲染
    struct.elements.forEach((el) => {
      return this.elements.push(el);
    });
    return true;
  }

  exportSvg() {
    var choisedElements, clone, firstRect, jsonString, metaScript, oldDebug, pureData, ref, ref1, serializer, svgElement, viewport;
    svgElement = document.getElementById("svg-paper");
    if (!svgElement) {
      return "";
    }
    
    // 临时备份所有的 isChoised 状态并在导出时置空，使控制点和高亮覆盖层不在 DOM 里生成
    choisedElements = this.getChoisedElements();
    choisedElements.forEach(function(el) {
      return el.isChoised = false;
    });
    
    // 临时关闭 debug 状态（以防生成调试文字）
    oldDebug = data.debug;
    data.debug = false;
    
    // 强制同步刷新画面 DOM（使上述状态立刻应用在真实 DOM 上）
    tools.m.redraw.sync();
    
    // 克隆干净的 DOM 节点
    clone = svgElement.cloneNode(true);
    
    // 恢复状态并触发下一次异步重绘
    choisedElements.forEach(function(el) {
      return el.isChoised = true;
    });
    data.debug = oldDebug;
    tools.m.redraw();
    
    // 1. 移除最外层包含背景色、尺寸的工作区样式
    clone.removeAttribute("style");
    // 强制将 SVG 画布大小规范为定海神针画板的物理尺寸
    clone.setAttribute("width", data.svgPaper.width);
    clone.setAttribute("height", data.svgPaper.height);
    clone.setAttribute("viewBox", `0 0 ${data.svgPaper.width} ${data.svgPaper.height}`);
    
    // 2. 获取并处理 viewport 场景容器
    viewport = clone.querySelector("#viewport");
    if (viewport) {
      // 移去 viewport 上的平移与缩放矩阵变换，使其回归原始的绝对物理坐标系
      viewport.removeAttribute("transform");
      viewport.removeAttribute("id");
      
      // 找到并剔除作为定海神针的透明底板 rect
      firstRect = viewport.querySelector("rect");
      if (firstRect && (((ref = firstRect.getAttribute("style")) != null ? ref.indexOf("transparent") : void 0) !== -1 || ((ref1 = firstRect.style) != null ? ref1.fill : void 0) === "transparent")) {
        firstRect.remove();
      }
    }
    
    // 3. 去除多余的辅助隐藏线，让导出的 SVG 干净纯粹
    clone.querySelectorAll("path").forEach(function(pathEl) {
      var ref2, ref3, styleStr;
      styleStr = pathEl.getAttribute("style") || "";
      if (styleStr.indexOf("#00000033") !== -1 || styleStr.indexOf("rgba(0, 0, 0, 0.2)") !== -1 || ((ref2 = pathEl.style) != null ? (ref3 = ref2.stroke) != null ? ref3.indexOf("rgba(0, 0, 0, 0.2)") : void 0 : void 0) !== -1) {
        return pathEl.remove();
      }
    });
    // 4. 生成连通图隐写 JSON 存档，并插入到克隆的 DOM 中
    pureData = SvgSerializer.serializeElements(this.elements);
    jsonString = JSON.stringify(pureData);
    
    // 创建 script 隐写节点
    metaScript = document.createElementNS("http://www.w3.org/2000/svg", "script");
    metaScript.setAttribute("type", "application/json");
    metaScript.setAttribute("id", "owo-meta");
    metaScript.textContent = jsonString;
    clone.appendChild(metaScript);
    
    // 5. 序列化为最终的 XML 字符串并返回
    serializer = new XMLSerializer();
    return serializer.serializeToString(clone);
  }

};
