// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import tools from "../tools.js";

import DebugWindow from "./svgEditor_debugWindow.js";

import svgParser from "./tools/svgEditor_svgParser.js";

import SvgSerializer from "./svgEditor_serialize.js";

export default function() {
  var Box, JsonTree, Notice, currentTabIndex, getColor, tabs;
  JsonTree = function() {
    var isExpanded;
    isExpanded = false;
    return {
      view: function({attrs}) {
        var color, d, keys;
        d = attrs.data;
        if (d === null || d === void 0) {
          return m("span", {
            style: {
              color: "#999"
            }
          }, String(d));
        }
        if (typeof d !== "object") {
          color = typeof d === "string" ? "#ce9178" : typeof d === "number" ? "#b5cea8" : "#569cd6";
          return m("span", {
            style: {color}
          }, typeof d === "string" ? `\"${d}\"` : String(d));
        }
        if (Array.isArray(d)) {
          return m("div", {
            style: {
              display: "inline-block",
              verticalAlign: "top"
            }
          }, [
            m("span",
            {
              style: {
                cursor: "pointer",
                userSelect: "none",
                color: "#d4d4d4"
              },
              onclick: function() {
                return isExpanded = !isExpanded;
              }
            },
            (isExpanded ? "▼" : "▶") + ` Array(${d.length})`),
            isExpanded ? m("div",
            {
              style: {
                paddingLeft: "15px",
                borderLeft: "1px dashed #555",
                marginLeft: "5px"
              }
            },
            d.map(function(item,
            index) {
              return m("div",
            {
                style: {
                  display: "flex"
                }
              },
            [
                m("span",
                {
                  style: {
                    color: "#9cdcfe",
                    marginRight: "5px",
                    flexShrink: 0
                  }
                },
                `${index}: `),
                m(JsonTree,
                {
                  data: item
                })
              ]);
            })) : void 0
          ]);
        }
        keys = Object.keys(d);
        return m("div", {
          style: {
            display: "inline-block",
            verticalAlign: "top"
          }
        }, [
          m("span",
          {
            style: {
              cursor: "pointer",
              userSelect: "none",
              color: "#d4d4d4"
            },
            onclick: function() {
              return isExpanded = !isExpanded;
            }
          },
          (isExpanded ? "▼" : "▶") + ` Object {${keys.length}}`),
          isExpanded ? m("div",
          {
            style: {
              paddingLeft: "15px",
              borderLeft: "1px dashed #555",
              marginLeft: "5px"
            }
          },
          keys.map(function(key) {
            return m("div",
          {
              style: {
                display: "flex"
              }
            },
          [
              m("span",
              {
                style: {
                  color: "#9cdcfe",
                  marginRight: "5px",
                  flexShrink: 0
                }
              },
              `${key}: `),
              m(JsonTree,
              {
                data: d[key]
              })
            ]);
          })) : void 0
        ]);
      }
    };
  };
  ({Box, getColor, Notice} = tools);
  tabs = [
    {
      title: "系统设置",
      name: "system"
    },
    {
      title: "工具属性",
      name: "toolProperty"
    }
  ];
  currentTabIndex = 0;
  return {
    view: function({attrs}) {
      var presentTool;
      return m("", [
        m("",
        {
          style: {
            display: "flex"
          }
        },
        [
          tabs.map((tab,
          index) => {
            return m(Box,
          {
              isBtn: true,
              style: {
                flex: 1,
                margin: 0,
                borderRadius: "unset",
                borderBottom: currentTabIndex === index ? `0.2rem solid ${getColor("main").back}` : "none",
                background: currentTabIndex === index ? "unset" : "#eee"
              },
              onclick: () => {
                return currentTabIndex = index;
              }
            },
          tab.title);
          })
        ]),
        tabs[currentTabIndex].name === "system" ? m("",
        [
          m(Box,
          [
            "切割画布",
            m(Box,
            {
              isSwitch: true,
              color: "main",
              onclick: () => {
                return data.switchSplitPaper();
              },
              value: data.splitPaper
            })
          ]),
          m(Box,
          [
            "调试模式",
            m(Box,
            {
              isSwitch: true,
              color: "main",
              onclick: () => {
                data.switchDebug();
                if (data.debug) {
                  return Notice.launch({
                    content: DebugWindow,
                    tip: "Elements 调试窗口"
                  });
                }
              },
              value: data.debug
            })
          ]),
          m(Box,
          {
            isBtn: true,
            onclick: function() {
              return Notice.launch({
                tip: "控制台",
                content: {
                  view: function() {
                    var ref;
                    return m("div",
          {
                      style: {
                        padding: "10px",
                        height: "400px",
                        overflowY: "auto",
                        fontFamily: "monospace",
                        background: "#222",
                        color: "#0f0",
                        fontSize: "12px"
                      }
                    },
          (ref = data.consoleLogs) != null ? ref.map((log) => {
                      var ref1;
                      return m("div",
          {
                        style: {
                          borderBottom: "1px solid #333",
                          padding: "4px 0",
                          display: "flex",
                          flexDirection: "row",
                          flexWrap: "wrap",
                          gap: "8px",
                          alignItems: "flex-start"
                        }
                      },
          [
                        m("span",
                        {
                          style: {
                            color: log.type === "error" ? "#ff5555" : log.type === "warn" ? "#ffff55" : "#55ff55",
                            flexShrink: 0
                          }
                        },
                        `[${log.type.toUpperCase()}]`),
                        (ref1 = log.args) != null ? ref1.map((arg) => {
                          return m(JsonTree,
                        {
                            data: arg
                          });
                        }) : void 0
                      ]);
                    }) : void 0);
                  }
                }
              });
            }
          },
          "打开系统控制台"),
          m(Box,
          {
            isBtn: true,
            onclick: function() {
              return Notice.launch({
                tip: "操作历史记录",
                content: {
                  view: function() {
                    return m("div",
          {
                      style: {
                        padding: "10px",
                        height: "400px",
                        overflowY: "auto",
                        fontFamily: "monospace",
                        background: "#222",
                        color: "#fff",
                        fontSize: "12px"
                      }
                    },
          [
                      m("div",
                      {
                        style: {
                          marginBottom: "10px",
                          color: "#888",
                          borderBottom: "1px solid #444",
                          paddingBottom: "5px"
                        }
                      },
                      `历史游标 (historyCursor): ${data.historyCursor} / 总数: ${data.historyDatas.length}`),
                      data.historyDatas.length === 0 ? m("div",
                      {
                        style: {
                          color: "#888"
                        }
                      },
                      "无操作历史记录") : data.historyDatas.map((step,
                      index) => {
                        var isCurrent;
                        isCurrent = index === data.historyCursor;
                        return m("div",
                      {
                          style: {
                            padding: "6px",
                            borderBottom: "1px solid #333",
                            background: (isCurrent ? "#007acc55" : "transparent"),
                            color: (isCurrent ? "#569cd6" : "#ccc"),
                            cursor: "pointer"
                          },
                          onclick: function() {
                            var newElements,
                      snapshot;
                            data.historyCursor = index;
                            snapshot = data.historyDatas[index].state;
                            newElements = SvgSerializer.deserializeElements(snapshot);
                            data.elPaper.elements.splice(0,
                      data.elPaper.elements.length,
                      ...newElements);
                            return m.redraw();
                          }
                        },
                      [
                          m("span",
                          {
                            style: {
                              color: (isCurrent ? "#569cd6" : "#888"),
                              marginRight: "10px"
                            }
                          },
                          `[步骤 ${index}]`),
                          m("span",
                          {
                            style: {
                              fontWeight: (isCurrent ? "bold" : "normal")
                            }
                          },
                          step.name),
                          isCurrent ? m("span",
                          {
                            style: {
                              color: "#569cd6",
                              marginLeft: "10px"
                            }
                          },
                          "◀ 当前游标") : void 0
                        ]);
                      })
                    ]);
                  }
                }
              });
            }
          },
          "打开历史记录面板"),
          m(Box,
          "当前：" + data.getPresentTool().title),
          m(Box,
          {
            isButton: true,
            onclick: () => {
              var a,
          blob,
          svgString,
          url;
              svgString = data.elPaper.exportSvg();
              if (svgString) {
                blob = new Blob([svgString],
          {
                  type: "image/svg+xml"
                });
                url = URL.createObjectURL(blob);
                a = document.createElement("a");
                a.href = url;
                a.download = "exported-svg-" + new Date().getTime() + ".svg";
                a.click();
                return URL.revokeObjectURL(url);
              }
            }
          },
          "导出SVG"),
          m(Box,
          {
            isButton: true,
            onclick: () => {
              var input;
              input = document.createElement("input");
              input.type = "file";
              input.accept = ".svg";
              input.onchange = (e) => {
                var file,
          reader;
                file = e.target.files[0];
                if (!file) {
                  return;
                }
                reader = new FileReader();
                reader.onload = (re) => {
                  var err,
          success,
          svgString;
                  svgString = re.target.result;
                  try {
                    // 优先尝试利用 owo-meta 导入拓扑存档
                    success = data.elPaper.importSvg(svgString,
          data.presentGroup);
                    if (success) {
                      data.record("导入 Owo 存档");
                    } else {
                      // 否则降级使用普通 SVG 语法解析器
                      svgParser.parse(svgString,
          data.presentGroup);
                    }
                    return m.redraw();
                  } catch (error) {
                    err = error;
                    return alert("解析 SVG 失败: " + err.message);
                  }
                };
                return reader.readAsText(file);
              };
              return input.click();
            }
          },
          "导入SVG")
        ]) : tabs[currentTabIndex].name === "toolProperty" ? (presentTool = data.getPresentTool(),
        m("",
        [
          (function() {
            var ref,
          ref1;
            switch (presentTool != null ? presentTool.name : void 0) {
              case "bucket":
                return m("",
          [
                  m(Box,
                  "当前：油漆桶工具 (Bucket)"),
                  m(Box,
                  [
                    "缝隙闭合容差 (px): ",
                    m(Box,
                    {
                      tagName: "input[type=number]",
                      style: {
                        width: "90px",
                        marginLeft: "10px",
                        padding: "4px 8px",
                        textAlign: "center",
                        borderRadius: "4px",
                        border: "1px solid #ccc"
                      },
                      ext: {
                        value: (ref = data.bucketTool) != null ? ref.gapTolerance : void 0,
                        oninput: (e) => {
                          var val;
                          val = parseInt(e.target.value) || 0;
                          data.bucketTool.gapTolerance = val;
                          return m.redraw();
                        }
                      }
                    })
                  ]),
                  m(Box,
                  [
                    "显示物理调试虚线",
                    m(Box,
                    {
                      isSwitch: true,
                      color: "main",
                      onclick: () => {
                        data.bucketTool.debugShowVirtualLines = !data.bucketTool.debugShowVirtualLines;
                        return m.redraw();
                      },
                      value: (ref1 = data.bucketTool) != null ? ref1.debugShowVirtualLines : void 0
                    })
                  ])
                ]);
              default:
                return m(Box,
          `当前工具【${(presentTool != null ? presentTool.title : void 0) || '移动工具'}】无需额外属性设置`);
            }
          }).call(this)
        ])) : void 0
      ]);
    }
  };
};
