// Generated by CoffeeScript 2.7.0
import Element from "./svgEditor_element.js";

import data from "./svgEditor_data.js";

import Rect from "./svgEditor_rect.js";

export default (class extends Rect {
  constructor(config) {
    super(config);
    this.type = "ellipse";
    this.bezierK = 0.5522847498307936; // 将 bezierK 作为类的内部变量
    this.config = {
      rx: 0,
      ry: 0,
      ...config
    };
  }

  
    // 椭圆的4个顶点
  getE1() { // 起始点 (M点)
    return {
      x: this.config.x,
      y: this.config.y + this.config.ry
    };
  }

  getE2() { // 第一条贝塞尔曲线的终点
    return {
      x: this.config.x + this.config.rx,
      y: this.config.y
    };
  }

  getE3() { // 第二条贝塞尔曲线的终点
    return {
      x: this.config.x + this.config.rx * 2,
      y: this.config.y + this.config.ry
    };
  }

  getE4() { // 第三条贝塞尔曲线的终点
    return {
      x: this.config.x + this.config.rx,
      y: this.config.y + this.config.ry * 2
    };
  }

  
    // 椭圆的8个控制点
  // 第一条贝塞尔曲线的控制点 (从E1到E2)
  getC1() {
    return {
      x: this.config.x,
      y: this.config.y + this.config.ry * (1 - this.bezierK)
    };
  }

  getC2() {
    return {
      x: this.config.x + this.config.rx * (1 - this.bezierK),
      y: this.config.y
    };
  }

  
    // 第二条贝塞尔曲线的控制点 (从E2到E3)
  getC3() {
    return {
      x: this.config.x + this.config.rx * (1 + this.bezierK),
      y: this.config.y
    };
  }

  getC4() {
    return {
      x: this.config.x + this.config.rx * 2,
      y: this.config.y + this.config.ry * (1 - this.bezierK)
    };
  }

  
    // 第三条贝塞尔曲线的控制点 (从E3到E4)
  getC5() {
    return {
      x: this.config.x + this.config.rx * 2,
      y: this.config.y + this.config.ry * (1 + this.bezierK)
    };
  }

  getC6() {
    return {
      x: this.config.x + this.config.rx * (1 + this.bezierK),
      y: this.config.y + this.config.ry * 2
    };
  }

  
    // 第四条贝塞尔曲线的控制点 (从E4到E1)
  getC7() {
    return {
      x: this.config.x + this.config.rx * (1 - this.bezierK),
      y: this.config.y + this.config.ry * 2
    };
  }

  getC8() {
    return {
      x: this.config.x,
      y: this.config.y + this.config.ry * (1 + this.bezierK)
    };
  }

  getElements() {
    var elements;
    elements = [
      // 第一条贝塞尔曲线: E1 -> C1 -> C2 -> E2
      [this.getE1(),
      this.getC1(),
      this.getC2(),
      this.getE2()],
      // 第二条贝塞尔曲线: E2 -> C3 -> C4 -> E3
      [this.getE2(),
      this.getC3(),
      this.getC4(),
      this.getE3()],
      // 第三条贝塞尔曲线: E3 -> C5 -> C6 -> E4
      [this.getE3(),
      this.getC5(),
      this.getC6(),
      this.getE4()],
      // 第四条贝塞尔曲线: E4 -> C7 -> C8 -> E1
      [this.getE4(),
      this.getC7(),
      this.getC8(),
      this.getE1()]
    ].map((points) => {
      return new Element({
        type: "line",
        prop: {
          points: points,
          parentGroup: data.presentGroup
        },
        isChoised: true
      });
    });
    return elements;
  }

});
