// Generated by CoffeeScript 2.7.0
var svgGroup;

import Element from "./svgEditor_element.js";

import data from "./svgEditor_data.js";

import getBoundingBox from "./elementMethod/getBoundingBox.js";

export default svgGroup = class svgGroup extends Element {
  constructor(config) {
    if (!config.prop.elements) {
      throw new Error("svgGroup类构造函数config.prop.elements不能为空");
    }
    super(config);
    this.type = "group";
    this.prop.elements = [];
    config.prop.elements.forEach((el) => {
      return this.addElement(el);
    });
    this.update();
  }

  addElement(element) {
    return element.joinGroup(this);
  }

  removeElement(element) {
    element.exitGroup();
    return this.update();
  }

  hasElement(element) {
    return element.prop.parentGroup === this;
  }

  hasElementDeep(element) {
    var cur;
    cur = element;
    while (cur) {
      if (cur.prop.parentGroup === this) {
        return true;
      }
      cur = cur.prop.parentGroup;
    }
    return false;
  }

  break() {
    var cloneElements;
    cloneElements = [...this.prop.elements];
    cloneElements.forEach((el) => {
      return this.removeElement(el);
    });
    cloneElements = null;
    return data.elPaper.remove(this);
  }

  translate({deltaX, deltaY}) {
    var cloneElements;
    cloneElements = [...this.prop.elements];
    cloneElements.forEach((el) => {
      var ref, ref1;
      if (el.type === "fillGroup") {
        return el.break();
      } else {
        el.translate({deltaX, deltaY});
        // 按照系统的多选逻辑，一经平移立即打碎所有关联的填充组
        if (((ref = el.prop.fillGroups) != null ? ref.length : void 0) > 0) {
          [...el.prop.fillGroups].forEach((fg) => {
            return fg.break();
          });
        }
        if (((ref1 = el.prop.fillGroupInners) != null ? ref1.length : void 0) > 0) {
          return [...el.prop.fillGroupInners].forEach((fg) => {
            return fg.break();
          });
        }
      }
    });
    return this.update();
  }

  update() {
    return this.getBoundingBox();
  }

  getBoundingBox() {
    var hasElements, maxX, maxY, minX, minY;
    minX = 2e308;
    minY = 2e308;
    maxX = -2e308;
    maxY = -2e308;
    hasElements = false;
    this.prop.elements.forEach((el) => {
      var box;
      box = null;
      if (el.type !== "fillGroup" && typeof el.getBoundingBox === "function") {
        box = el.getBoundingBox();
      } else if (el.type === "fillGroup") {
        box = null;
      }
      if (box) {
        minX = Math.min(minX, box.minX);
        minY = Math.min(minY, box.minY);
        maxX = Math.max(maxX, box.maxX);
        maxY = Math.max(maxY, box.maxY);
        return hasElements = true;
      }
    });
    if (hasElements) {
      this.prop.x = minX;
      this.prop.y = minY;
      this.prop.w = maxX - minX;
      this.prop.h = maxY - minY;
      return {
        minX: minX,
        minY: minY,
        maxX: maxX,
        maxY: maxY
      };
    } else {
      this.prop.x = 0;
      this.prop.y = 0;
      this.prop.w = 0;
      this.prop.h = 0;
      return {
        minX: 0,
        minY: 0,
        maxX: 0,
        maxY: 0
      };
    }
  }

  isIntersectBox(boxInfo) {
    return this.prop.elements.some((ele) => {
      if (ele.isIntersectBox) {
        return ele.isIntersectBox(boxInfo);
      } else {
        return false;
      }
    });
  }

};
