// Generated by CoffeeScript 2.7.0
var Element;

import paperOncreate from "./events/paperOncreate.js";

import pathOncreate from "./events/pathOncreate.js";

import data from "./svgEditor_data.js";

import PreFillSvg from "./svgEditor_preFillSvg.js";

import ChoisedSvg from "./svgEditor_choisedSvg.js";

import splitBezier from "./tools/splitBezier/main.js";

import tools from "../tools.js";

Element = function() {
  return {
    view: function({attrs}) {
      var c0, c1, controlPoints, element, isOutsideScope, ref, ref1;
      element = attrs.element;
      controlPoints = element.type === "line" ? element.getControlPoints() : [];
      isOutsideScope = false;
      if (data.presentGroup) {
        isOutsideScope = !(element === data.presentGroup || data.presentGroup.hasElementDeep(element) || (element.type === "group" && element.hasElementDeep(data.presentGroup)));
      }
      switch (element.type) {
        case "group":
          //组的边界框
          return m("g", {
            key: element.id,
            transform: element.prop.transform,
            style: {
              opacity: isOutsideScope ? 0.3 : 1,
              pointerEvents: isOutsideScope ? "none" : "auto"
            }
          }, [
            // 渲染组内元素
            data.elPaper.getList().filter((child) => {
              var ref;
              return ((ref = child.prop) != null ? ref.parentGroup : void 0) === element;
            }).sort((a,
            b) => {
              if (a.type === "group" && b.type !== "group") {
                return 1;
              }
              if (a.type !== "group" && b.type === "group") {
                return -1;
              }
              return 0;
            }).map((child) => {
              return m(Element,
            {
                key: child.id,
                element: child
              });
            }),
            //边界框矩形（移到元素后面，确保在最顶层渲染）
            element.isChoised ? m("rect",
            {
              x: element.prop.x,
              y: element.prop.y,
              width: element.prop.w,
              height: element.prop.h,
              style: {
                fill: "none",
                stroke: "#46c6fb",
                strokeWidth: 2 / data.globalZoom,
                strokeDasharray: `${5 / data.globalZoom},${5 / data.globalZoom}`,
                pointerEvents: "none"
              }
            }) : void 0
          ]);
        case "line":
        case "pureFill":
          return m("g", {
            key: element.id,
            transform: element.prop.transform,
            style: {
              opacity: isOutsideScope ? 0.3 : 1,
              pointerEvents: isOutsideScope ? "none" : "auto"
            }
          }, [
            //路径本体
            m("path",
            {
              oncreate: ({dom}) => {
                return pathOncreate(dom,
            element);
              },
              style: {
                //filter: if element.isChoised
                //  "drop-shadow(0 0 10px #ffdb66)"
                stroke: element.isClosed ? "#46c6fb" : element.isActive ? element.prop.stroke : "#00000033",
                //stroke:element.prop.stroke
                //stroke:element.prop.stroke
                "stroke-width": element.prop.strokeWidth,
                "stroke-linecap": element.prop.strokeLinecap,
                fill: element.prop.fill
              },
              
              // 添加fill-rule属性以支持挖空效果
              "fill-rule": element.type === "pureFill" && ((ref = element.prop.childRegions) != null ? ref.length : void 0) > 0 ? "evenodd" : "nonzero",
              d: (function() {
                switch (element.type) {
                  case "line":
                    return element.getSvgPath();
                  case "fillGroup":
                    return element.prop.pureFill.getSvgPath();
                  case "pureFill":
                    return element.getSvgPath();
                }
              })()
            }),
            data.debug && element.type === "line" ? [
              [element.s(),
              element.e()].map(function(site) {
                return m("text",
              {
                  x: site.x + 10,
                  y: site.y + 10,
                  style: {
                    stroke: "#fff",
                    fill: "#000",
                    fontWeight: "bold"
                  }
                },
              `(${site.x},${site.y})`);
              })
            ] : void 0,
            // 覆盖图案
            element.isChoised ? m("path",
            {
              style: {
                pointerEvents: "none",
                fill: element.type === "fillGroup" || element.type === "pureFill" ? "url(#choisedFill)" : "none",
                stroke: element.type === "line" ? "url(#choisedFill)" : "none",
                strokeWidth: element.prop.strokeWidth,
                strokeLinecap: element.prop.strokeLinecap
              },
              
              // 添加fill-rule属性以支持挖空效果
              "fill-rule": element.type === "pureFill" && ((ref1 = element.prop.childRegions) != null ? ref1.length : void 0) > 0 ? "evenodd" : "nonzero",
              d: (function() {
                switch (element.type) {
                  case "line":
                    return element.getSvgPath();
                  case "fillGroup":
                    return element.prop.pureFill.getSvgPath();
                  case "pureFill":
                    return element.getSvgPath();
                }
              })()
            }) : void 0,
            element.isClosed ? [ //端点
              m("circle",
              {
                cx: element.s().x,
                cy: element.s().y,
                r: data.cursorTool.endpointR / data.globalZoom,
                style: {
                  stroke: "#ffdb66",
                  strokeWidth: 2 / data.globalZoom,
                  fill: "none"
                }
              }),
              m("circle",
              {
                cx: element.e().x,
                cy: element.e().y,
                r: data.cursorTool.endpointR / data.globalZoom,
                style: {
                  stroke: "#ffdb66",
                  strokeWidth: 2 / data.globalZoom,
                  fill: "none"
                }
              })
            ] : void 0,
            element.isChoised && controlPoints.length > 0 ? [
              (c0 = controlPoints[0]) ? m("circle",
              {
                cx: c0.x,
                cy: c0.y,
                r: 5 / data.globalZoom,
                fill: "#ffdb66"
              }) : void 0,
              (c1 = controlPoints[1]) ? m("circle",
              {
                cx: c1.x,
                cy: c1.y,
                r: 5 / data.globalZoom,
                fill: "#ffdb66"
              }) : void 0
            ] : void 0
          ]);
        case "text":
          return m("g", {
            key: element.id,
            transform: element.prop.transform,
            style: {
              display: element.isActive === false ? "none" : "",
              opacity: isOutsideScope ? 0.3 : 1,
              pointerEvents: isOutsideScope ? "none" : "auto"
            }
          }, [
            element.prop.mode === "svg" ? m("text",
            {
              x: element.prop.x,
              y: element.prop.y + element.prop.fontSize * 0.8,
              style: {
                fontSize: `${element.prop.fontSize}px`,
                fontFamily: element.prop.fontFamily,
                fill: element.prop.color,
                userSelect: "none"
              }
            },
            element.prop.text.split("\n").map(function(line,
            index) {
              return m("tspan",
            {
                x: element.prop.x,
                dy: index === 0 ? 0 : element.prop.fontSize * 1.2,
                style: {
                  fontSize: `${element.prop.fontSize}px`,
                  fontFamily: element.prop.fontFamily,
                  fill: element.prop.color
                }
              },
            line);
            })) : m("foreignObject",
            {
              x: element.prop.x,
              y: element.prop.y,
              width: element.prop.w,
              height: element.prop.h,
              style: {
                overflow: "visible"
              }
            },
            [
              m("div.article",
              {
                xmlns: "http://www.w3.org/1999/xhtml",
                style: {
                  width: "100%",
                  height: "100%"
                }
              },
              m.trust(tools.format ? tools.format(element.prop.text,
              "markdown") : element.prop.text.replace(/\n/g,
              '<br/>')))
            ]),
            element.isChoised ? m("rect",
            {
              x: element.prop.x,
              y: element.prop.y,
              width: element.prop.w,
              height: element.prop.h,
              style: {
                fill: "none",
                stroke: "#46c6fb",
                strokeWidth: 2 / data.globalZoom,
                strokeDasharray: `${5 / data.globalZoom},${5 / data.globalZoom}`,
                pointerEvents: "none"
              }
            }) : void 0
          ]);
        default:
          return m("g", {
            key: element.id
          }, []);
      }
    }
  };
};

export default {
  view: function() {
    var Box, Tag, ref, ref1;
    ({Box, Tag} = tools);
    return m("", {
      style: {
        position: "absolute",
        top: 0,
        left: 0,
        touchAction: "none",
        "-webkit-touch-action": "none",
        height: "100%",
        width: "100%",
        display: "block",
        userSelect: "none",
        backgroundColor: "#e0e0e0", // 外围工作区背景改为灰色
        overflow: "hidden"
      }
    }, [
      // 纯视觉表现的白色画板底层
      m("div",
      {
        style: {
          backgroundColor: "#ffffff",
          width: `${data.svgPaper.width}px`,
          height: `${data.svgPaper.height}px`,
          transformOrigin: "0 0",
          transform: `translate(${data.offsetX}px, ${data.offsetY}px) scale(${data.globalZoom})`,
          position: "absolute",
          pointerEvents: "none"
        }
      }),
      
      // 铺满全屏，重新夺回事件处理权的 SVG
      m("svg",
      {
        id: "svg-paper",
        oncreate: paperOncreate,
        style: {
          position: "absolute",
          height: "100%",
          width: "100%",
          cursor: data.getPresentTool().cursor,
          userSelect: "none"
        }
      },
      [
        //斜线与滤镜等元素
        m(PreFillSvg),
        m(ChoisedSvg),
        // 主场景容器 (恢复独立缩放)
        m("g",
        {
          id: "viewport",
          transform: `translate(${data.offsetX}, ${data.offsetY}) scale(${data.globalZoom})`
        },
        [
          // 真实的画板尺寸定海神针 (默认透明)
          m("rect",
          {
            x: 0,
            y: 0,
            width: data.svgPaper.width,
            height: data.svgPaper.height,
            style: {
              fill: "transparent",
              pointerEvents: "none" // 确保不影响事件穿透
            }
          }),
          // 预览填充区域
          data.preFulls.map((fill) => {
            var ref;
            return m("g",
          [
              m("path",
              {
                style: {
                  fill: fill.prop.fill,
                  "fill-rule": ((ref = fill.prop.childRegions) != null ? ref.length : void 0) > 0 ? "evenodd" : "nonzero",
                  pointerEvents: "none"
                },
                d: fill.getSvgPath()
              })
            ]);
          }),
          // 画布内容
          m("g",
          [
            data.elPaper.getList().filter((element) => {
              var ref;
              return !((ref = element.prop) != null ? ref.parentGroup : void 0);
            }).sort((a,
            b) => {
              if (a.type === "group" && b.type !== "group") {
                return 1;
              }
              if (a.type !== "group" && b.type === "group") {
                return -1;
              }
              return 0;
            }).map((element) => {
              return m(Element,
            {
                key: element.id,
                element: element
              });
            })
          ]),
          // 输入框浮层
          ((ref = data.uiText) != null ? ref.active : void 0) ? m("foreignObject",
          {
            x: data.uiText.x,
            y: data.uiText.y,
            width: Math.max(data.uiText.w,
          250),
            height: Math.max(data.uiText.h,
          50) + 40,
            transform: (ref1 = data.uiText.targetElement) != null ? ref1.prop.transform : void 0,
            style: {
              overflow: "visible"
            }
          },
          [
            m("div",
            {
              xmlns: "http://www.w3.org/1999/xhtml",
              onpointerdown: function(e) {
                return e.stopPropagation();
              },
              style: {
                display: "flex",
                flexDirection: "column",
                width: "100%",
                height: "100%"
              }
            },
            [
              m("textarea",
              {
                oncreate: function({dom}) {
                  dom.focus();
                  dom.value = data.uiText.text;
                  dom._ro = new ResizeObserver(function(entries) {
                    var entry,
              i,
              len,
              results;
                    results = [];
                    for (i = 0, len = entries.length; i < len; i++) {
                      entry = entries[i];
                      if (data.uiText.w !== dom.offsetWidth || data.uiText.h !== dom.offsetHeight) {
                        data.uiText.w = dom.offsetWidth;
                        data.uiText.h = dom.offsetHeight;
                        results.push(m.redraw());
                      } else {
                        results.push(void 0);
                      }
                    }
                    return results;
                  });
                  return dom._ro.observe(dom);
                },
                onupdate: function({dom}) {
                  if (dom.value !== data.uiText.text) {
                    return dom.value = data.uiText.text;
                  }
                },
                onremove: function({dom}) {
                  var ref2;
                  return (ref2 = dom._ro) != null ? ref2.disconnect() : void 0;
                },
                oninput: function(e) {
                  return data.uiText.text = e.target.value;
                },
                value: data.uiText.text,
                style: {
                  width: `${Math.max(data.uiText.w,
              50)}px`,
                  height: `${Math.max(data.uiText.h,
              30)}px`,
                  background: "#ffffff",
                  border: "1px solid #d1d1d6",
                  borderRadius: "0px",
                  boxSizing: "border-box",
                  boxShadow: "inset 0 1px 3px rgba(0,0,0,0.06)",
                  outline: "none",
                  resize: "both",
                  fontSize: `${data.uiText.fontSize}px`,
                  fontFamily: data.uiText.fontFamily,
                  color: data.uiText.color,
                  padding: "8px",
                  margin: 0,
                  whiteSpace: "pre-wrap"
                }
              }),
              m("div",
              {
                style: {
                  display: "flex",
                  marginTop: "8px",
                  alignItems: "center",
                  width: "max-content"
                }
              },
              [
                m(Tag,
                {
                  color: "main",
                  styleExt: {
                    whiteSpace: "nowrap"
                  },
                  ext: {
                    onclick: function() {
                      data.textTool.saveText();
                      return m.redraw();
                    }
                  }
                },
                "确认"),
                m(Tag,
                {
                  color: "main",
                  styleExt: {
                    whiteSpace: "nowrap"
                  },
                  ext: {
                    onclick: function() {
                      data.textTool.abort();
                      return m.redraw();
                    }
                  }
                },
                "取消"),
                m("div",
                {
                  style: {
                    marginLeft: "auto",
                    fontSize: "0.8rem",
                    color: "#666",
                    marginRight: "0.4rem",
                    whiteSpace: "nowrap"
                  }
                },
                `当前模式: ${data.uiText.mode === 'svg' ? '纯SVG' : 'Markdown'}`),
                m(Tag,
                {
                  color: "main",
                  styleExt: {
                    whiteSpace: "nowrap"
                  },
                  ext: {
                    onclick: function() {
                      data.uiText.mode = data.uiText.mode === "svg" ? "markdown" : "svg";
                      return m.redraw();
                    }
                  }
                },
                data.uiText.mode === "svg" ? "切换为Markdown" : "切换为纯SVG")
              ])
            ])
          ]) : void 0,
          //框选器
          m("g",
          [
            m("path",
            {
              style: {
                fill: data.cBox.fill,
                stroke: data.cBox.stroke,
                strokeWidth: data.cBox.strokeWidth
              },
              //椭圆路径
              d: data.cBox.isEllipse ? `M${data.cBox.x} ${data.cBox.y + data.cBox.ry}
C${data.cBox.x} ${data.cBox.y + data.cBox.ry * (1 - data.cBox.bezierK)}, ${data.cBox.x + data.cBox.rx * (1 - data.cBox.bezierK)} ${data.cBox.y}, ${data.cBox.x + data.cBox.rx} ${data.cBox.y}
C${data.cBox.x + data.cBox.rx * (1 + data.cBox.bezierK)} ${data.cBox.y}, ${data.cBox.x + data.cBox.rx * 2} ${data.cBox.y + data.cBox.ry * (1 - data.cBox.bezierK)}, ${data.cBox.x + data.cBox.rx * 2} ${data.cBox.y + data.cBox.ry}
C${data.cBox.x + data.cBox.rx * 2} ${data.cBox.y + data.cBox.ry * (1 + data.cBox.bezierK)}, ${data.cBox.x + data.cBox.rx * (1 + data.cBox.bezierK)} ${data.cBox.y + data.cBox.ry * 2}, ${data.cBox.x + data.cBox.rx} ${data.cBox.y + data.cBox.ry * 2}
C${data.cBox.x + data.cBox.rx * (1 - data.cBox.bezierK)} ${data.cBox.y + data.cBox.ry * 2}, ${data.cBox.x} ${data.cBox.y + data.cBox.ry * (1 + data.cBox.bezierK)}, ${data.cBox.x} ${data.cBox.y + data.cBox.ry}
Z` : `M${data.cBox.getP1().x} ${data.cBox.getP1().y}
L${data.cBox.getP2().x} ${data.cBox.getP2().y}
L${data.cBox.getP3().x} ${data.cBox.getP3().y}
L${data.cBox.getP4().x} ${data.cBox.getP4().y}
Z`
            })
          ])
        ])
      ])
    ]);
  }
};
