// Generated by CoffeeScript 2.7.0
var FillGroup;

import data from "./svgEditor_data.js";

import Element from "./svgEditor_element.js";

import PureFill from "./svgEditor_pureFill.js";

import pointInRegions from "./tools/pointInRegions.js";

import validateRegionClosure from "./tools/validateRegionClosure.js";

export default FillGroup = class FillGroup extends Element {
  constructor(config) {
    var ref;
    if (!config.prop.elements) {
      throw new Error("FillGroup类构造函数config.prop.elements不能为空");
    }
    if (!config.prop.pureFill) {
      throw new Error("FillGroup类构造函数config.prop.pureFill不能为空");
    }
    config.type = "fillGroup";
    super(config);
    this.type = "fillGroup";
    this.prop.fill = (config != null ? (ref = config.prop) != null ? ref.fill : void 0 : void 0) || data.colorTool.bgColor;
    this.prop.stroke = "none";
    this.prop.elements = [];
    this.prop.childRegions = [];
    config.prop.elements.forEach((el) => {
      return this.addElement(el);
    });
    config.prop.childRegions.forEach((region) => {
      return this.addChildRegion(region);
    });
    
    // 为子区域元素建立引用关系
    this.addPureFill(config.prop.pureFill);
  }

  addElement(element) {
    if (element.prop.fillGroups.indexOf(this) === -1) {
      element.prop.fillGroups.push(this);
    } else {
      console.log("警告：元素已有填充组的引用");
    }
    if (this.prop.elements.indexOf(element) === -1) {
      return this.prop.elements.push(element);
    } else {
      return console.log("警告:填充组已有该元素");
    }
  }

  addChildRegion(region) {
    if (this.prop.childRegions.indexOf(region) === -1) {
      this.prop.childRegions.push(region);
    } else {
      console.log("警告：填充组的子区域里已经有该区域");
    }
    return region.forEach((el) => {
      if (el.prop.fillGroupInners.indexOf(this) === -1) {
        return el.prop.fillGroupInners.push(this);
      } else {
        return console.log("警告:区域的元素的子填充组已经有该组");
      }
    });
  }

  addPureFill(pureFill) {
    if (pureFill.prop.fillGroups.indexOf(this) === -1) {
      pureFill.prop.fillGroups.push(this);
    } else {
      console.log("警告：元素已有填充组的引用");
    }
    return this.prop.pureFill = pureFill;
  }

  update() {
    if (this.isClosureOrRemove()) {
      return this.prop.pureFill.recreateElements(this.prop.elements, this.prop.childRegions);
    }
  }

  translate({deltaX, deltaY}) {
    this.prop.elements.forEach((el) => {
      return el.translate({deltaX, deltaY});
    });
    
    // 同时平移子区域元素
    this.prop.childRegions.forEach((childRegion) => {
      return childRegion.forEach((el) => {
        return el.translate({deltaX, deltaY});
      });
    });
    return this.update();
  }

  break() {
    var cloneElements, ref;
    cloneElements = [...this.prop.elements];
    //防止删除元素索引错误
    cloneElements.forEach((el) => {
      return el.exitFillGroup(this);
    });
    cloneElements = null;
    
    // 同时处理子区域元素的退出
    this.prop.childRegions.forEach((childRegion) => {
      return childRegion.forEach((el) => {
        return el.exitFillGroupInner(this); // 子区域元素只退出内边线关系
      });
    });
    //纯填充退出填充组
    if ((ref = this.prop.pureFill) != null) {
      ref.exitFillGroup(this); //因为不是数组，防止同一个元素多次break报错
    }
    return data.elPaper.remove(this);
  }

  getElementsActiveStatus() {
    return this.prop.elements.every((ele) => {
      return ele.isActive === true || ele.prop.fillGroupInners.length > 0;
    });
  }

  isIntersectBox(boxInfo) {
    return this.prop.elements.some((ele) => {
      return ele.isIntersectBox(boxInfo);
    });
  }

  isPointInRegion(site, ignoreChildren = false) {
    var childRegions, pointInChildren, pointInElements;
    pointInElements = pointInRegions(site, [
      {
        elements: this.prop.elements,
        children: []
      }
    ]);
    childRegions = this.prop.childRegions.map((region) => {
      return {
        elements: region,
        children: []
      };
    });
    if (ignoreChildren) {
      return pointInElements.length > 0;
    } else {
      pointInChildren = pointInRegions(site, childRegions);
      return pointInElements.length > 0 && pointInChildren.length === 0;
    }
  }

  replaceElement(oldElement, newElements) {
    oldElement.exitFillGroup(this);
    return newElements.forEach((newElement) => {
      return newElement.joinFillGroup(this);
    });
  }

  isElementsClosure() {
    return validateRegionClosure(this.prop.elements);
  }

  isChildRegionsClosure() {
    if (this.prop.childRegions.length > 0) {
      return this.prop.childRegions.every((region) => {
        return validateRegionClosure(region);
      });
    } else {
      return true;
    }
  }

  isClosureOrRemove() {
    var ref;
    if (!(this.isElementsClosure() && this.isChildRegionsClosure())) {
      if ((ref = this.prop.pureFill) != null) {
        ref.remove();
      }
      this.break();
      console.log("填充组的边线或者内边线不闭合，解散且移除填充组");
      return false;
    } else {
      return true;
    }
  }

};
