// Generated by CoffeeScript 2.7.0
var data,
  indexOf = [].indexOf;

import Elpaper from "./svgEditor_elPaper.js";

import tools from "../tools.js";

import LineTool from "./class/lineTool.js";

import CursorTool from "./class/cursorTool.js";

import BucketTool from "./class/bucketTool.js";

import ellipseTool from "./class/ellipseTool.js";

import rectTool from "./class/rectTool.js";

import TextTool from "./class/textTool.js";

import InkBottleTool from "./class/inkBottleTool.js";

import EraserTool from "./class/eraserTool.js";

import DripTool from "./class/dripTool.js";

import UiText from "./svgEditor_uiText.js";

import splitBezier from "./tools/splitBezier/main.js";

import Rect from "./svgEditor_rect.js";

import Ellipse from "./svgEditor_ellipse.js";

import SvgSerializer from "./svgEditor_serialize.js";

import {
  settingIcon,
  lineIcon,
  cursorIcon,
  bucketIcon,
  inkBottleIcon,
  magicWandIcon,
  polygonIcon,
  lassoIcon,
  ellipseIcon,
  rectIcon,
  eraserIcon,
  penIcon,
  textIcon,
  dripIcon
} from "./icons/icons.js";

window.dumpHistory = function() {
  return data.dumpHistory();
};

export default data = {
  colorTool: {
    bgColor: "#ffdb66",
    fgColor: "#000000",
    strokeWidth: 5,
    presentColor: "full",
    recentUseColor: ["#ffdb66", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff"],
    setRecentUseColor: function(color) {
      if (indexOf.call(this.recentUseColor, color) >= 0) {
        this.recentUseColor = this.recentUseColor.filter((c) => {
          return c !== color;
        });
      }
      this.recentUseColor.unshift(color);
      if (this.recentUseColor.length > 6) {
        return this.recentUseColor.pop();
      }
    }
  },
  presentGroup: null,
  RightMenu: null,
  initRightMenu: function() {
    var Menu;
    ({Menu} = tools);
    return this.RightMenu != null ? this.RightMenu : this.RightMenu = Menu(true);
  },
  rightMenuTimer: null,
  hasContextMenu: function() {
    var ref, ref1, ref2;
    return (ref = tools.Notice) != null ? (ref1 = ref.data) != null ? (ref2 = ref1.dataArr) != null ? ref2.some(function(item) {
      return item.group === "svgContextMenu";
    }) : void 0 : void 0 : void 0;
  },
  lineTool: null,
  initLineTool: function() {
    return this.lineTool != null ? this.lineTool : this.lineTool = new LineTool();
  },
  cursorTool: null,
  initCursorTool: function() {
    return this.cursorTool != null ? this.cursorTool : this.cursorTool = new CursorTool();
  },
  bucketTool: null,
  initBucketTool: function() {
    return this.bucketTool != null ? this.bucketTool : this.bucketTool = new BucketTool();
  },
  inkBottleTool: null,
  initInkBottleTool: function() {
    return this.inkBottleTool != null ? this.inkBottleTool : this.inkBottleTool = new InkBottleTool();
  },
  ellipseTool: null,
  initEllipseTool: function() {
    return this.ellipseTool != null ? this.ellipseTool : this.ellipseTool = new ellipseTool();
  },
  rectTool: null,
  initRectTool: function() {
    return this.rectTool != null ? this.rectTool : this.rectTool = new rectTool();
  },
  textTool: null,
  initTextTool: function() {
    return this.textTool != null ? this.textTool : this.textTool = new TextTool();
  },
  eraserTool: null,
  initEraserTool: function() {
    return this.eraserTool != null ? this.eraserTool : this.eraserTool = new EraserTool();
  },
  dripTool: null,
  initDripTool: function() {
    return this.dripTool != null ? this.dripTool : this.dripTool = new DripTool();
  },
  uiText: null,
  initUiText: function() {
    return this.uiText != null ? this.uiText : this.uiText = new UiText();
  },
  rightMenuTop: 0,
  rightMenuLeft: 0,
  pressKeys: [],
  _presentTool: 0,
  cBox: {
    switchType: function() {
      this.isEllipse = !this.isEllipse;
      this.x = 0;
      this.y = 0;
      this.w = 0;
      this.h = 0;
      this.rx = 0;
      return this.ry = 0;
    },
    reset: function() {
      this.x = 0;
      this.y = 0;
      this.w = 0;
      this.h = 0;
      this.rx = 0;
      this.ry = 0;
      this.active = false;
      this.fill = "#eeeeee55";
      this.stroke = "#aaaaaa";
      this.strokeWidth = 1;
      return this.isEllipse = false;
    },
    createElements: function() {
      var ellipse, rect;
      if (!this.isEllipse) {
        rect = new Rect({
          x: this.x,
          y: this.y,
          w: this.w,
          h: this.h
        });
        return rect.getElements();
      } else {
        ellipse = new Ellipse({
          x: this.x,
          y: this.y,
          w: this.w,
          h: this.h,
          rx: this.rx,
          ry: this.ry
        });
        return ellipse.getElements();
      }
    },
    isEllipse: 0,
    active: false,
    x: 0,
    y: 0,
    w: 0,
    h: 0,
    rx: 0,
    ry: 0,
    bezierK: 0.5522847498307936,
    getP1: function() {
      return {
        x: this.x,
        y: this.y
      };
    },
    getP2: function() {
      return {
        x: this.x + this.w,
        y: this.y
      };
    },
    getP3: function() {
      return {
        x: this.x + this.w,
        y: this.y + this.h
      };
    },
    getP4: function() {
      return {
        x: this.x,
        y: this.y + this.h
      };
    },
    fill: "#eeeeee55",
    stroke: "#aaaaaa",
    strokeWidth: 1
  },
  tools: [
    {
      title: "移动工具(A)",
      name: "cursor",
      //cursor:"url('data:image/svg+xml;utf8,#{encodeURIComponent(cursorIcon)}') 0 0, auto"
      cursor: "default",
      icon: cursorIcon,
      hotKeys: ["A"]
    },
    {
      /* {
           title:"魔术棒"
           name:"magicWand"
           cursor:"url('data:image/svg+xml;utf8,#{encodeURIComponent(magicWandIcon)}') 0 0, auto"
           icon:magicWandIcon
         } */
      /* {
           title:"多边形套索"
           name:"polygon"
           cursor:"url('data:image/svg+xml;utf8,#{encodeURIComponent(polygonIcon)}') 0 0, auto"
           icon:polygonIcon
         } */
      /* {
           title:"套索工具(L)"
           name:"lasso"
           cursor:"url('data:image/svg+xml;utf8,#{encodeURIComponent(lassoIcon)}') 0 0, auto"
           icon:lassoIcon
           hotKeys:["L"]
         } */
      title: "直线工具(N)",
      name: "line",
      cursor: "crosshair",
      icon: lineIcon,
      hotKeys: ["N"]
    },
    {
      title: "椭圆工具(O)",
      name: "ellipse",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(ellipseIcon)}') 0 0, auto`,
      icon: ellipseIcon,
      hotKeys: ["O"]
    },
    {
      title: "矩形工具(R)",
      name: "rect",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(rectIcon)}') 0 0, auto`,
      icon: rectIcon,
      hotKeys: ["R"]
    },
    {
      title: "橡皮擦(E)",
      name: "eraser",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(eraserIcon)}') 0 0, auto`,
      icon: eraserIcon,
      hotKeys: ["E"]
    },
    {
      /* {
           title:"钢笔工具"
           name:"pen"
           cursor:"url('data:image/svg+xml;utf8,#{encodeURIComponent(penIcon)}') 0 0, auto"
           icon:penIcon
           hotKeys:["P"]
         } */
      title: "文本工具",
      name: "text",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(textIcon)}') 0 0, auto`,
      icon: textIcon,
      hotKeys: ["T"]
    },
    {
      title: "滴管工具",
      name: "drip",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(dripIcon)}') 0 0, auto`,
      icon: dripIcon,
      hotKeys: ["I"]
    },
    {
      title: "颜料桶(K)",
      name: "bucket",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(bucketIcon)}') 0 0, auto`,
      icon: bucketIcon,
      hotKeys: ["K"]
    },
    {
      title: "墨水瓶(S)",
      name: "inkBottle",
      cursor: `url('data:image/svg+xml;utf8,${encodeURIComponent(inkBottleIcon)}') 0 0, auto`,
      icon: inkBottleIcon,
      hotKeys: ["S"]
    },
    {
      title: "设置",
      name: "setting",
      cursor: "default",
      icon: settingIcon
    }
  ],
  svgPaper: {
    width: 1000,
    height: 1000
  },
  elPaper: new Elpaper(),
  clipboardSnapshot: null,
  
  // ==============================
  // PS 风格历史记录 (游标队列 + 纯补丁增量)
  // ==============================
  historyDatas: [],
  historyCursor: -1,
  lastSnapshot: [], // 内存中永远只保留唯一一份最新快照作为比对基准
  record: function(actionName = "未命名操作") {
    var forward, newSnapshot, reverse;
    if (this.historyDatas.length !== this.historyCursor + 1) {
      this.historyDatas.length = this.historyCursor + 1;
    }
    newSnapshot = SvgSerializer.serializeElements(this.elPaper.elements);
    forward = tools.jsonpatch.compare(this.lastSnapshot, newSnapshot);
    if (forward.length === 0) { // 物理状态无变化，极简防抖拦截
      return;
    }
    reverse = tools.jsonpatch.compare(newSnapshot, this.lastSnapshot);
    this.historyDatas.push({
      name: actionName,
      forward: forward,
      reverse: reverse
    });
    if (this.historyDatas.length > 50) {
      this.historyDatas.shift();
    } else {
      this.historyCursor++;
    }
    return this.lastSnapshot = newSnapshot;
  },
  dumpHistory: function() {
    var added, changes, currMap, currentState, el, elCount, i, id, j, k, l, len, len1, len2, logLines, modified, n, newIdx, newPg, newPts, oldIdx, oldPg, oldPts, prevMap, prevState, pts, ref, ref1, ref2, ref3, ref4, ref5, ref6, removed, res, step, tempSnapshot;
    logLines = [`\n===== 深度纯补丁推演录像 (共 ${this.historyDatas.length} 步) =====`];
    
    // 为不污染环境，用深拷贝创建演算用的影子画板
    tempSnapshot = JSON.parse(JSON.stringify(this.lastSnapshot));

    // 沿着 reverse 链条时光倒流到最早的一步
    for (i = j = ref = this.historyCursor; j >= 0; i = j += -1) {
      if (i > -1 && this.historyDatas[i]) {
        tools.jsonpatch.applyPatch(tempSnapshot, this.historyDatas[i].reverse);
      }
    }
    prevState = JSON.parse(JSON.stringify(tempSnapshot));
    ref1 = this.historyDatas;
    for (i = k = 0, len = ref1.length; k < len; i = ++k) {
      step = ref1[i];
      // 沿着 forward 链条顺流而下，推演出当前步的全量快照
      tools.jsonpatch.applyPatch(tempSnapshot, step.forward);
      currentState = JSON.parse(JSON.stringify(tempSnapshot));
      elCount = currentState.length;
      prevMap = {};
      for (l = 0, len1 = prevState.length; l < len1; l++) {
        el = prevState[l];
        prevMap[el.id] = el;
      }
      currMap = {};
      for (n = 0, len2 = currentState.length; n < len2; n++) {
        el = currentState[n];
        currMap[el.id] = el;
      }
      
      // 计算 Diff
      added = [];
      removed = [];
      modified = [];
      for (id in currMap) {
        el = currMap[id];
        if (!prevMap[id]) {
          pts = ((ref2 = el.prop) != null ? ref2.points : void 0) ? JSON.stringify(el.prop.points) : "";
          added.push(`      [+] 新增: ${el.type} (ID:${id}) 坐标: ${pts}`);
        } else {
          oldPts = JSON.stringify((ref3 = prevMap[id].prop) != null ? ref3.points : void 0);
          newPts = JSON.stringify((ref4 = el.prop) != null ? ref4.points : void 0);
          oldPg = (ref5 = prevMap[id].prop) != null ? ref5.parentGroup : void 0;
          newPg = (ref6 = el.prop) != null ? ref6.parentGroup : void 0;
          changes = [];
          if (oldPts !== newPts) {
            changes.push(`坐标从 ${oldPts} 变为 ${newPts}`);
          }
          if (oldPg !== newPg) {
            changes.push(`组从 ${oldPg} 变为 ${newPg}`);
          }
          oldIdx = prevState.findIndex((e) => {
            return e.id === id;
          });
          newIdx = currentState.findIndex((e) => {
            return e.id === id;
          });
          if (oldIdx !== newIdx) {
            changes.push(`层级 [${oldIdx}] -> [${newIdx}]`);
          }
          if (changes.length > 0) {
            modified.push(`      [*] 修改: ${el.type} (ID:${id}) | ${changes.join(' | ')}`);
          }
        }
      }
      for (id in prevMap) {
        el = prevMap[id];
        if (!currMap[id]) {
          removed.push(`      [-] 删除: ${el.type} (ID:${id})`);
        }
      }
      logLines.push(`\n[步骤 ${i}] 操作: ${step.name} | 元素总数: ${elCount}`);
      if (added.length > 0) {
        logLines.push(...added);
      }
      if (removed.length > 0) {
        logLines.push(...removed);
      }
      if (modified.length > 0) {
        logLines.push(...modified);
      }
      if (added.length === 0 && removed.length === 0 && modified.length === 0) {
        logLines.push("      (无明显数据变化)");
      }
      prevState = currentState;
    }
    res = logLines.join("\n");
    console.log(res);
    return res;
  },
  undo: function() {
    var newElements, presentGroupId, ref, step;
    if (this.historyCursor > -1) {
      step = this.historyDatas[this.historyCursor];
      this.historyCursor--;
      tools.jsonpatch.applyPatch(this.lastSnapshot, JSON.parse(JSON.stringify(step.reverse)));
      newElements = SvgSerializer.deserializeElements(this.lastSnapshot);
      presentGroupId = (ref = this.presentGroup) != null ? ref.id : void 0;
      this.elPaper.elements.splice(0, this.elPaper.elements.length, ...newElements);
      if (presentGroupId) {
        this.presentGroup = this.elPaper.elements.find(function(el) {
          return el.type === "group" && el.id === presentGroupId;
        }) || null;
      }
      return m.redraw();
    }
  },
  redo: function() {
    var newElements, presentGroupId, ref, step;
    if (this.historyCursor + 1 <= this.historyDatas.length - 1) {
      this.historyCursor++;
      step = this.historyDatas[this.historyCursor];
      tools.jsonpatch.applyPatch(this.lastSnapshot, JSON.parse(JSON.stringify(step.forward)));
      newElements = SvgSerializer.deserializeElements(this.lastSnapshot);
      presentGroupId = (ref = this.presentGroup) != null ? ref.id : void 0;
      this.elPaper.elements.splice(0, this.elPaper.elements.length, ...newElements);
      if (presentGroupId) {
        this.presentGroup = this.elPaper.elements.find(function(el) {
          return el.type === "group" && el.id === presentGroupId;
        }) || null;
      }
      return m.redraw();
    }
  },
  // 全局缩放平移属性
  globalZoom: 1,
  offsetX: 0,
  offsetY: 0,
  activePointers: 0,
  getLocalX: function(clientX, domSite) {
    return (clientX - domSite.x - this.offsetX) / this.globalZoom;
  },
  getLocalY: function(clientY, domSite) {
    return (clientY - domSite.y - this.offsetY) / this.globalZoom;
  },
  state: {},
  getPresentTool: function() {
    return this.tools[this.presentTool];
  },
  preFulls: [],
  debug: false,
  switchDebug: function(boolean) {
    if (boolean != null) {
      return this.debug = boolean;
    } else {
      return this.debug = !this.debug;
    }
  },
  splitPaper: true,
  switchSplitPaper: function(boolean) {
    if (boolean != null) {
      this.splitPaper = boolean;
    } else {
      this.splitPaper = !this.splitPaper;
    }
    return splitBezier.splitPaper();
  },
  consoleLogs: [],
  hackConsole: function() {
    var origError, origLog, origWarn;
    if (window.__owo_console_hacked) {
      return;
    }
    window.__owo_console_hacked = true;
    origLog = console.log;
    console.log = (...args) => {
      this.consoleLogs.push({
        type: "log",
        args: args
      });
      return origLog.apply(console, args);
    };
    origError = console.error;
    console.error = (...args) => {
      this.consoleLogs.push({
        type: "error",
        args: args
      });
      return origError.apply(console, args);
    };
    origWarn = console.warn;
    console.warn = (...args) => {
      this.consoleLogs.push({
        type: "warn",
        args: args
      });
      return origWarn.apply(console, args);
    };
    window.addEventListener('error', (e) => {
      var ref;
      this.consoleLogs.push({
        type: "error",
        args: ["[全局未捕获异常]", e.message, e.filename, e.lineno, e.colno, (ref = e.error) != null ? ref.stack : void 0]
      });
      if (typeof m !== "undefined") {
        return m.redraw();
      }
    });
    return window.addEventListener('unhandledrejection', (e) => {
      var ref, ref1;
      this.consoleLogs.push({
        type: "error",
        args: ["[Promise报错]", ((ref = e.reason) != null ? ref.message : void 0) || e.reason, (ref1 = e.reason) != null ? ref1.stack : void 0]
      });
      if (typeof m !== "undefined") {
        return m.redraw();
      }
    });
  }
};

data.hackConsole();

data._lastPresentTool = 0;

Object.defineProperty(data, "presentTool", {
  get: function() {
    return data._presentTool;
  },
  set: function(val) {
    var ref, ref1, ref2, ref3, ref4;
    if (((ref = data.tools) != null ? (ref1 = ref[val]) != null ? ref1.name : void 0 : void 0) !== "drip") {
      data._lastPresentTool = val;
    }
    data._presentTool = val;
    if (((ref2 = data.tools) != null ? (ref3 = ref2[val]) != null ? ref3.name : void 0 : void 0) === "drip") {
      return (ref4 = data.dripTool) != null ? typeof ref4.triggerDrip === "function" ? ref4.triggerDrip() : void 0 : void 0;
    }
  }
});
