// Generated by CoffeeScript 2.7.0
var svgElement;

import data from "./svgEditor_data.js";

import tools from "../tools.js";

import subdivideBezier from "./elementMethod/subdivideBezier.js";

import getBoundingBox from "./elementMethod/getBoundingBox.js";

import getBezierPoint from "./elementMethod/getBezierPoint.js";

import getProjectionT from "./elementMethod/getProjectionT.js";

import getBezierDerivative from "./elementMethod/getBezierDerivative.js";

import getBezier2Derivative from "./elementMethod/getBezier2Derivative.js";

import isIntersectLine from "./elementMethod/isIntersectLine.js";

import getIntersectionPoints from "./elementMethod/getIntersectionPoints.js";

import isIntersectBox from "./elementMethod/isIntersectBox.js";

export default svgElement = (function() {
  class svgElement {
    constructor(config) {
      var ref, ref1, ref2;
      this.type = config.type || "line";
      this.id = config.id || tools.uuid();
      this.prop = {
        note: "无备注",
        stroke: data.colorTool.fgColor,
        strokeWidth: data.colorTool.strokeWidth,
        points: [],
        strokeLinecap: "round",
        fill: "none",
        fillGroups: [],
        fillGroupInners: [], // 新增：记录作为内边线的填充组
        parentGroup: null, // 记录所属的逻辑编组
        ...config.prop
      };
      this.isClosed = (ref = config != null ? config.isClosed : void 0) != null ? ref : false;
      this.isChoised = (ref1 = config != null ? config.isChoised : void 0) != null ? ref1 : false;
      this.isActive = (ref2 = config != null ? config.isActive : void 0) != null ? ref2 : true;
      if (this.prop.parentGroup) {
        this.joinGroup(this.prop.parentGroup);
      }
    }

    update() { //更新填充组信息
      if (this.prop.fillGroups.length > 0) {
        this.prop.fillGroups.forEach((fillGroup) => {
          return fillGroup.update();
        });
      }
      
      // 同时更新作为内边线的填充组
      if (this.prop.fillGroupInners.length > 0) {
        this.prop.fillGroupInners.forEach((fillGroup) => {
          return fillGroup.update();
        });
      }
      // 向上冒泡更新父级逻辑编组信息（包围盒等）
      if (this.prop.parentGroup) {
        return this.prop.parentGroup.update();
      }
    }

    joinGroup(group, index = -1) {
      if (!group) {
        return;
      }
      if (this.prop.parentGroup && this.prop.parentGroup !== group) {
        this.exitGroup();
      }
      this.prop.parentGroup = group;
      if (group.prop.elements.indexOf(this) === -1) {
        if (index !== -1) {
          return group.prop.elements.splice(index, 0, this);
        } else {
          if (this.type === "pureFill" || this.type === "fillGroup") {
            return group.prop.elements.unshift(this);
          } else {
            return group.prop.elements.push(this);
          }
        }
      } else {
        return console.log("警告:组内已经有该元素,无法加入");
      }
    }

    exitGroup() {
      var group, idx;
      group = this.prop.parentGroup;
      if (group) {
        idx = group.prop.elements.indexOf(this);
        if (idx !== -1) {
          group.prop.elements.splice(idx, 1);
        }
        
        // 如果原来的组有父组，则自动加入父组（维持原有解散组时的向上冒泡逻辑）
        if (group.prop.parentGroup) {
          this.prop.parentGroup = null;
          return this.joinGroup(group.prop.parentGroup);
        } else {
          return this.prop.parentGroup = null;
        }
      }
    }

    joinFillGroup(fillGroup) {
      //双向引用
      if (this.prop.fillGroups.indexOf(fillGroup) === -1) {
        this.prop.fillGroups.push(fillGroup);
      } else {
        console.log("警告：元素已经在填充组,无法加入");
      }
      if (fillGroup.prop.elements.indexOf(this) === -1) {
        return fillGroup.prop.elements.push(this);
      } else {
        return console.log("警告:填充组内已经有元素,无法加入");
      }
    }

    exitFillGroup(fillGroup) {
      var elIndex, myIndex;
      elIndex = this.prop.fillGroups.indexOf(fillGroup);
      if (elIndex !== -1) {
        this.prop.fillGroups.splice(elIndex, 1);
      } else {
        console.log("警告：元素已经不在填充组，无法退出");
      }
      
      // 检查是否在主元素列表中
      myIndex = fillGroup.prop.elements.indexOf(this);
      if (myIndex !== -1) {
        return fillGroup.prop.elements.splice(myIndex, 1);
      } else {
        // 可能是子区域元素，不需要从elements中移除，只需要移除引用关系即可
        console.log("警告:填充组内以没有元素,无法退出");
        return console.log("子区域元素退出填充组引用");
      }
    }

    exitFillGroupInner(fillGroup) {
      var elIndex, preDel;
      elIndex = this.prop.fillGroupInners.indexOf(fillGroup);
      if (elIndex !== -1) {
        this.prop.fillGroupInners.splice(elIndex, 1);
      } else {
        console.log("警告：元素不是该填充组的内边线");
      }
      preDel = [];
      //删除整个区域
      fillGroup.prop.childRegions.forEach((childRegion, index) => {
        if ((childRegion.indexOf(this)) !== -1) {
          return preDel.push(index);
        }
      });
      return preDel.forEach((regionIndex) => {
        return fillGroup.prop.childRegions.splice(regionIndex, 1);
      });
    }

    s() {
      return this.prop.points[0];
    }

    e() {
      return this.prop.points[this.prop.points.length - 1];
    }

    setS(site) {
      return this.prop.points[0] = site;
    }

    setE(site) {
      return this.prop.points[this.prop.points.length - 1] = site;
    }

    setFill(fill) {
      return this.prop.fill = fill;
    }

    setStroke(stroke) {
      return this.prop.stroke = stroke;
    }

    getStroke() {
      return this.prop.stroke;
    }

    getPoints() {
      return this.prop.points;
    }

    getControlPoints() {
      return this.prop.points.slice(1, -1);
    }

    getControlPoint(index) {
      return this.prop.points[index];
    }

    addControlPoint(point) {
      return this.prop.points.splice(this.prop.points.length - 1, 0, {
        x: point.x,
        y: point.y
      });
    }

    addAutoControlPoint() {
      var end, lastIndex, lastPoint, midPoint, newControlPoint, points, prevPoint, start;
      points = this.getPoints();
      // 如果已经是三次贝塞尔曲线，则不添加控制点
      if (points.length >= 4) {
        return;
      }
      // 获取起点和终点
      start = points[0];
      end = points[points.length - 1];
      if (points.length === 2) {
        midPoint = {
          x: (start.x + end.x) / 2,
          y: (start.y + end.y) / 2
        };
        return this.addControlPoint(midPoint);
      } else if (points.length === 3) {
        
        // 在最后两点之间插入中点作为新的控制点
        lastIndex = points.length - 1;
        prevPoint = points[lastIndex - 1];
        lastPoint = points[lastIndex];
        newControlPoint = {
          x: (prevPoint.x + lastPoint.x) / 2,
          y: (prevPoint.y + lastPoint.y) / 2
        };
        
        // 在当前控制点之后添加新的控制点
        return this.addControlPoint(newControlPoint);
      }
    }

    removeControlPoint(point) {
      var findPoint;
      findPoint = this.prop.points.findIndex(function(point2) {
        return point2.x === point.x && point2.y === point.y;
      });
      return this.prop.points.splice(findPoint, 1);
    }

    setControlPoint(index, point) {
      return this.prop.points[index] = {
        x: point.x,
        y: point.y
      };
    }

    getStartEndDisSquare() {
      return (this.s().x - this.e().x) ** 2 + (this.s().y - this.e().y) ** 2;
    }

    getSvgPath() {
      if (this.getControlPoints().length === 0) {
        return `        M${this.s().x} ${this.s().y}
L${this.e().x} ${this.e().y}`;
      } else if (this.getControlPoints().length === 1) {
        return `M${this.s().x} ${this.s().y}
Q${this.getControlPoint(1).x} ${this.getControlPoint(1).y}
${this.e().x} ${this.e().y}`;
      } else if (this.getControlPoints().length === 2) {
        return `M${this.s().x} ${this.s().y}
C${this.getControlPoint(1).x} ${this.getControlPoint(1).y}
${this.getControlPoint(2).x} ${this.getControlPoint(2).y}
${this.e().x} ${this.e().y}`;
      }
    }

    getFillGroups() {
      return this.prop.fillGroups;
    }

    getFillGroupInners() {
      return this.prop.fillGroupInners;
    }

    // copy:->
    //   points = @prop.points.map (point)=>
    //     x:point.x + 40
    //     y:point.y + 40
    //   newElement = new svgElement
    //     type: @type
    //     id: tools.uuid()
    //     prop:{
    //       @prop...
    //       points:points
    //       fillGroups:[
    //         @prop.fillGroups...
    //       ]
    //       fillGroupInners:[
    //         @prop.fillGroupInners...
    //       ]
    //     }
    //     isChoised: @isChoised
    //     isActive: @isActive
    copy() {
      var snapshot, topLevelElements;
      snapshot = SvgSerializer.serializeElements([this]);
      ({topLevelElements} = SvgSerializer.deserializeElements(snapshot, {
        assignNewIds: true,
        returnStruct: true
      }));
      return topLevelElements[0];
    }

    translate({deltaX, deltaY}) {
      return this.prop.points.forEach((point) => {
        point.x += deltaX;
        return point.y += deltaY;
      });
    }

    remove() {
      var elIndex, gIndex;
      elIndex = data.elPaper.elements.indexOf(this);
      if (elIndex !== -1) {
        data.elPaper.elements.splice(elIndex, 1);
      }
      if (this.prop.parentGroup) {
        gIndex = this.prop.parentGroup.prop.elements.indexOf(this);
        if (gIndex !== -1) {
          return this.prop.parentGroup.prop.elements.splice(gIndex, 1);
        }
      }
    }

    getGlobalMatrix() {
      var cssTransform, current, matrix;
      matrix = new DOMMatrix();
      current = this.prop.parentGroup;
      while (current) {
        if (current.prop.transform) {
          // 在运行时将 SVG 特有的 rotate(a, x, y) 转换为等效的 CSS 标准
          cssTransform = current.prop.transform.replace(/rotate\s*\(\s*([^\s,]+)[\s,]+([^\s,]+)[\s,]+([^\s,\)]+)\s*\)/g, "translate($2px, $3px) rotate($1deg) translate(-$2px, -$3px)");
          matrix.preMultiplySelf(new DOMMatrix(cssTransform));
        }
        current = current.prop.parentGroup;
      }
      return matrix;
    }

    globalToLocal(site, matrix = this.getGlobalMatrix().inverse()) {
      var domPoint;
      domPoint = new DOMPoint(site.x, site.y).matrixTransform(matrix);
      return {
        x: domPoint.x,
        y: domPoint.y,
        t: site.t
      };
    }

    localToGlobal(site, matrix = this.getGlobalMatrix()) {
      var domPoint;
      domPoint = new DOMPoint(site.x, site.y).matrixTransform(matrix);
      return {
        x: domPoint.x,
        y: domPoint.y,
        t: site.t
      };
    }

    getGlobalPoints() {
      var matrix;
      matrix = this.getGlobalMatrix();
      return this.prop.points.map((p) => {
        return this.localToGlobal(p, matrix);
      });
    }

    getGlobalBoundingBox() {
      var box, matrix, p1, p2, p3, p4;
      box = this.getBoundingBox();
      matrix = this.getGlobalMatrix();
      p1 = this.localToGlobal({
        x: box.minX,
        y: box.minY
      }, matrix);
      p2 = this.localToGlobal({
        x: box.maxX,
        y: box.minY
      }, matrix);
      p3 = this.localToGlobal({
        x: box.minX,
        y: box.maxY
      }, matrix);
      p4 = this.localToGlobal({
        x: box.maxX,
        y: box.maxY
      }, matrix);
      return {
        minX: Math.min(p1.x, p2.x, p3.x, p4.x),
        maxX: Math.max(p1.x, p2.x, p3.x, p4.x),
        minY: Math.min(p1.y, p2.y, p3.y, p4.y),
        maxY: Math.max(p1.y, p2.y, p3.y, p4.y)
      };
    }

    
      // 检查与另一个元素的包围盒是否相交
    isIntersectBoundingBox(otherElement) {
      var box1, box2;
      box1 = this.getBoundingBox();
      box2 = otherElement.getBoundingBox();
      return !(box1.maxX < box2.minX || box2.maxX < box1.minX || box1.maxY < box2.minY || box2.maxY < box1.minY);
    }

    // 获取采样点数组
    getSamplePoints(sampleCount) {
      var i, j, ref, samplePoints, t;
      samplePoints = [];
      for (i = j = 0, ref = sampleCount; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
        t = i / sampleCount;
        samplePoints.push({
          ...this.getBezierPoint(t),
          sourceT: t
        });
      }
      return samplePoints;
    }

    estimateLength() {
      var dx, dy, i, j, point1, point2, ref, sampleCount, segmentLength, t1, t2, totalLength;
      // 使用简单的采样方法估算长度
      sampleCount = 50;
      totalLength = 0;
      for (i = j = 0, ref = sampleCount; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
        t1 = i / sampleCount;
        t2 = (i + 1) / sampleCount;
        point1 = this.getBezierPoint(t1);
        point2 = this.getBezierPoint(t2);
        
        // 计算两点间距离
        dx = point2.x - point1.x;
        dy = point2.y - point1.y;
        segmentLength = Math.sqrt(dx * dx + dy * dy);
        totalLength += segmentLength;
      }
      return totalLength;
    }

    // 智能获取采样点
    getSmartSamplePoints(ratio = 1) {
      var estimatedLength, sampleCount;
      // 估算曲线长度
      estimatedLength = this.estimateLength();
      // 根据长度和比例计算采样点数量
      // ratio = 1 表示 100px 对应 100 个采样点
      sampleCount = parseInt(estimatedLength * ratio);
      return this.getSamplePoints(sampleCount);
    }

    // 获取采样线数组
    getSampleLines(sampleCount) {
      var endPoint, i, j, lineElement, ref, sampleLines, samplePoints, startPoint;
      samplePoints = this.getSamplePoints(sampleCount);
      sampleLines = [];
      for (i = j = 0, ref = samplePoints.length - 1; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
        startPoint = samplePoints[i];
        endPoint = samplePoints[i + 1];
        
        // 创建新的element实例作为线段
        lineElement = new svgElement({
          prop: {
            points: [startPoint, endPoint]
          }
        });
        if (lineElement._tmp == null) {
          lineElement._tmp = {
            sourceT: startPoint.sourceT
          };
        }
        sampleLines.push(lineElement);
      }
      return sampleLines;
    }

    // 智能获取采样线
    getSmartSampleLines(ratio = 1) {
      var estimatedLength, sampleCount;
      estimatedLength = this.estimateLength();
      sampleCount = parseInt(estimatedLength * ratio);
      return this.getSampleLines(sampleCount);
    }

    
      // 计算曲线的平坦度（控制点偏离程度）
    getFlatness() {
      var a, b, c, distance, dx, dy, end, i, j, length, maxDistance, points, ref, start;
      points = this.getPoints();
      if (points.length <= 2) {
        return 0;
      }
      
      // 计算控制点到起点终点连线的最大距离
      start = points[0];
      end = points[points.length - 1];
      
      // 直线方程 ax + by + c = 0
      dx = end.x - start.x;
      dy = end.y - start.y;
      length = Math.sqrt(dx * dx + dy * dy);
      if (length < 1e-10) {
        return 0;
      }
      a = dy / length;
      b = -dx / length;
      c = (start.x * dy - start.y * dx) / length;
      maxDistance = 0;
      for (i = j = 1, ref = points.length - 1; (1 <= ref ? j < ref : j > ref); i = 1 <= ref ? ++j : --j) {
        distance = Math.abs(a * points[i].x + b * points[i].y + c);
        maxDistance = Math.max(maxDistance, distance);
      }
      return maxDistance;
    }

    isPointInLine(point, includeStartEnd = false, dis = 0.5) {
      var disSq, isSameSite, projPoint, projectionT;
      if (!includeStartEnd) {
        isSameSite = (site1, site2) => {
          return site1.x === site2.x && site1.y === site2.y;
        };
        if (isSameSite(point, this.s()) || isSameSite(point, this.e())) {
          return false;
        }
      }
      projectionT = this.getProjectionT(point);
      //testT = Math.round(projectionT*10000)
      projPoint = this.getBezierPoint(projectionT);
      disSq = (point.x - projPoint.x) ** 2 + (point.y - projPoint.y) ** 2;
      if (disSq < dis ** 2) {
        return {
          x: projPoint.x,
          y: projPoint.y,
          t: projectionT
        };
      } else {
        return false;
      }
    }

    isPointsCollinear() {
      var controlPoints, j, len, output, point, v0;
      v0 = {
        x: this.e().x - this.s().x,
        y: this.e().y - this.s().y
      };
      output = true;
      controlPoints = this.getControlPoints();
      for (j = 0, len = controlPoints.length; j < len; j++) {
        point = controlPoints[j];
        ((point) => {
          var crossProduct, denominator, sinA, v1;
          v1 = {
            x: point.x - this.s().x,
            y: point.y - this.s().y
          };
          crossProduct = v0.x * v1.y - v0.y * v1.x;
          denominator = Math.sqrt(v0.x ** 2 + v0.y ** 2) * Math.sqrt(v1.x ** 2 + v1.y ** 2);
          if (denominator > 0) {
            sinA = crossProduct / denominator;
            if (Math.abs(sinA) > 0.02) {
              return output = false;
            }
          }
        })(point);
      }
      return output;
    }

    curveTurnLine() {
      if (this.prop.points.length > 2) {
        console.log("调整控制点");
        return this.prop.points = [this.s(), this.e()];
      }
    }

    isLineInLine(line, dis = 1) {
      var samplePoints;
      if (this.getPoints().length === 2 && line.getPoints().length === 2) {
        if (this.isPointInLine(line.s(), true, dis) && this.isPointInLine(line.e(), true, dis)) {
          return true;
        } else {
          return false;
        }
      } else if (this.getPoints().length === 2 && line.getPoints().length === 3) {
        if (this.isPointInLine(line.s(), true, 5) && this.isPointInLine(line.e(), true, 5) && this.isPointInLine(line.getControlPoint(1), true, 5)) {
          return true;
        } else {
          return false;
        }
      } else if (this.getPoints().length === 3 && line.getPoints().length === 2) {
        samplePoints = line.getSmartSamplePoints(0.1);
        return samplePoints.every((samplePoint) => {
          var tmp;
          tmp = this.isPointInLine(samplePoint, true, 5);
          return tmp;
        });
      } else if (this.getPoints().length > 2 && line.getPoints().length > 2) {
        samplePoints = line.getSmartSamplePoints(0.5);
        return samplePoints.every((samplePoint) => {
          var tmp;
          tmp = this.isPointInLine(samplePoint, true, 5);
          return tmp;
        });
      }
    }

  };

  // 计算元素的精确包围盒
  svgElement.prototype.getBoundingBox = getBoundingBox;

  
  // 分割贝塞尔曲线，返回element实例数组
  svgElement.prototype.subdivideBezier = subdivideBezier;

  
  // 获取贝塞尔曲线上的点
  svgElement.prototype.getBezierPoint = getBezierPoint;

  
  // 计算点在曲线上的投影参数t值
  svgElement.prototype.getProjectionT = getProjectionT;

  
  // 计算贝塞尔曲线的一阶导数
  svgElement.prototype.getBezierDerivative = getBezierDerivative;

  
  // 计算贝塞尔曲线的二阶导数
  svgElement.prototype.getBezier2Derivative = getBezier2Derivative;

  // 判断当前元素是否与另一个元素相交
  svgElement.prototype.isIntersectLine = isIntersectLine;

  svgElement.prototype.getIntersectionPoints = getIntersectionPoints;

  svgElement.prototype.isIntersectBox = isIntersectBox;

  return svgElement;

}).call(this);
