// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import Paper from "./svgEditor_paper.js";

import ToolBar from "./svgEditor_toolBar.js";

import TopBar from "./svgEditor_topBar.js";

import GroupNav from "./svgEditor_groupNav.js";

import tools from "../tools.js";

import SvgSerializer from "./svgEditor_serialize.js";

export default function() {
  var Box, Notice, Tag, Tip;
  ({Notice, Box, Tag, Tip} = tools);
  return {
    oninit: function() {
      return data.initRightMenu();
    },
    view: function() {
      return m(".svg-editor-main-container", {
        style: {
          width: "100%",
          height: "100%",
          position: "relative",
          overflow: "hidden"
        }
      }, [
        m("style",
        `.svg-editor-main-container *{
  user-select:none;
  -webkit-user-select:none;
}`),
        m(TopBar),
        m(ToolBar),
        m(Paper),
        //右键菜单
        m(data.RightMenu,
        {
          atcreate: function(dom) {
            return data.RightMenu.dom = dom;
          },
          show: false,
          style: {
            position: "fixed",
            top: data.rightMenuTop - 20 + "px",
            left: data.rightMenuLeft - 20 + "px",
            zIndex: 99999,
            transition: "all 0.5s ease"
          }
        },
        [
          data.RightMenu.data.items.map((item) => {
            return m(Box,
          {
              isBtn: true,
              ext: {
                onclick: function(e) {
                  item.click(e);
                  return m.redraw();
                }
              }
            },
          item.name);
          })
        ])
      ]);
    }
  };
};
