// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import tools from "../tools.js";

export default function() {
  return {
    view: function() {
      var Box, Tag, chain, getGroupChain;
      ({Box, Tag} = tools);
      if (data.presentGroup) {
        // 递归获取当前组的父级链路
        getGroupChain = function(group) {
          var chain, curr;
          chain = [];
          curr = group;
          while (curr) {
            chain.unshift(curr);
            curr = curr.prop.parentGroup;
          }
          return chain;
        };
        chain = getGroupChain(data.presentGroup);
        return m("", {
          style: {
            display: "flex",
            alignItems: "center",
            padding: "0.5rem 1rem",
            width: "100%",
            boxSizing: "border-box",
            fontSize: "0.85rem",
            borderBottom: "1px solid rgba(0,0,0,0.05)"
          }
        }, [
          m(Box,
          {
            isBtn: true,
            style: {
              padding: "0.2rem 0.8rem",
              borderRadius: "1rem",
              boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
              color: "#555",
              fontWeight: "bold"
            },
            onclick: () => {
              data.presentGroup = null;
              data.elPaper.elements.forEach((el) => {
                el.isChoised = false;
                if (el.type === "group" && !el.prop.parentGroup) {
                  return el.update();
                }
              });
              return m.redraw();
            }
          },
          "根层级"),
          chain.map((group,
          index) => {
            var isLast,
          ref,
          ref1;
            isLast = index === chain.length - 1;
            return [
              m("span",
              {
                style: {
                  margin: "0 0.4rem",
                  color: "#ccc",
                  fontWeight: "bold"
                }
              },
              "/"),
              m(Box,
              {
                isBtn: !isLast,
                style: {
                  padding: "0.2rem 0.8rem",
                  background: isLast ? "var(--main-color, #4A90E2)" : "#fff",
                  color: isLast ? "#fff" : "#555",
                  borderRadius: "1rem",
                  boxShadow: isLast ? "0 2px 6px rgba(74, 144, 226, 0.3)" : "0 1px 3px rgba(0,0,0,0.08)",
                  cursor: isLast ? "default" : "pointer",
                  fontWeight: isLast ? "bold" : "normal"
                },
                onclick: () => {
                  if (!isLast) {
                    data.presentGroup = group;
                    data.elPaper.elements.forEach((el) => {
                      return el.isChoised = false;
                    });
                    group.update();
                    return m.redraw();
                  }
                }
              },
              (ref = (ref1 = group.id) != null ? ref1.slice(0, 6) : void 0) != null ? ref : "组")
            ];
          })
        ]);
      } else {
        return null;
      }
    }
  };
};
