// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import {
  backIcon,
  settingIcon
} from "./icons/icons.js";

import Rect from "./svgEditor_rect.js";

import Ellipse from "./svgEditor_ellipse.js";

import Setting from "./svgEditor_setting.js";

import GroupNav from "./svgEditor_groupNav.js";

import tools from "../tools.js";

export default function() {
  var Box, Notice, Tag, getColor;
  ({Box, Tag, Notice, getColor} = tools);
  return {
    view: function({attrs}) {
      return m("", {
        style: {
          position: "absolute",
          top: 0,
          left: 0
        }
      }, [
        m("",
        {
          style: {
            display: "flex",
            alignItems: "center",
            width: "100%"
          }
        },
        [
          m(Box,
          {
            isBtn: true,
            style: {
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            },
            onclick: function() {
              if (typeof ROUTE !== "undefined" && ROUTE.lastRoute) {
                return ROUTE.back();
              } else if (typeof ROUTE !== "undefined") {
                return ROUTE.set("/user");
              }
            }
          },
          m.trust(backIcon)),
          data.getPresentTool().name === "cursor" ? m.fragment([
            m(Box,
            {
              style: {
                padding: "0.5rem"
              }
            },
            [
              "椭圆选区",
              m(Box,
              {
                isSwitch: true,
                color: "main",
                onclick: () => {
                  return data.cBox.switchType();
                },
                value: data.cBox.isEllipse
              })
            ]),
            data.cBox.active && data.cBox.w > 0 && data.cBox.h > 0 ? m(Box,
            {
              isBtn: true,
              ext: {
                onpointerdown: function(e) {
                  return e.stopPropagation();
                }
              },
              onclick: () => {
                return data.cBox.createElements().forEach((el) => {
                  return data.elPaper.add(el);
                });
              }
            },
            "创建路径") : void 0
          ]) : void 0,
          m(Box,
          {
            isBtn: true,
            style: {
              marginLeft: "auto",
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            },
            onclick: function() {
              if (Notice) {
                return Notice.launch({
                  tip: "设置",
                  content: Setting,
                  contentAttrs: {Box,
          getColor}
                });
              }
            }
          },
          m.trust(settingIcon))
        ]),
        m("",
        {
          style: {
            width: "100%"
          }
        },
        [m(GroupNav)])
      ]);
    }
  };
};
