// Generated by CoffeeScript 2.7.0
var hexToRgb, hsvToRgb, rgbToHex, rgbToHsv, rgbToRgbaString;

import tools from "../tools.js";

// 工具函数：HSV转RGB
hsvToRgb = function(h, s, v) {
  var f, i, p, q, t;
  h = h / 360;
  i = Math.floor(h * 6);
  f = h * 6 - i;
  p = v * (1 - s);
  q = v * (1 - f * s);
  t = v * (1 - (1 - f) * s);
  switch (i % 6) {
    case 0:
      return [v, t, p];
    case 1:
      return [q, v, p];
    case 2:
      return [p, v, t];
    case 3:
      return [p, q, v];
    case 4:
      return [t, p, v];
    case 5:
      return [v, p, q];
  }
};

// 工具函数：RGB转HSV
rgbToHsv = function(r, g, b) {
  var d, h, max, min, s, v;
  max = Math.max(r, g, b);
  min = Math.min(r, g, b);
  h = s = v = max;
  d = max - min;
  s = max === 0 ? 0 : d / max;
  if (max === min) {
    h = 0;
  } else {
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
    }
    h /= 6;
  }
  return [h * 360, s, v];
};

// 工具函数：RGB转16进制
rgbToHex = function(r, g, b) {
  var toHex;
  toHex = function(n) {
    var hex;
    hex = Math.round(n * 255).toString(16);
    if (hex.length === 1) {
      return "0" + hex;
    } else {
      return hex;
    }
  };
  return "#" + toHex(r) + toHex(g) + toHex(b);
};

// 工具函数：16进制转RGB
hexToRgb = function(hex) {
  var b, g, r;
  r = parseInt(hex.slice(1, 3), 16) / 255;
  g = parseInt(hex.slice(3, 5), 16) / 255;
  b = parseInt(hex.slice(5, 7), 16) / 255;
  return [r, g, b];
};

// 工具函数：RGB转RGBA字符串
rgbToRgbaString = function(r, g, b, a) {
  return `rgba(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)},${a.toFixed(2)})`;
};

export default function() {
  var Box, getColor;
  ({Box, getColor} = tools);
  return {
    data: {
      h: 0, // 色相 0-360
      s: 1, // 饱和度 0-1
      v: 1, // 明度 0-1
      a: 1, // 透明度 0-1
      dragging: null,
      canvasSize: 200,
      sliderHeight: 20,
      padding: 10,
      hexColor: "#ff0000",
      rgbaColor: "rgba(255,0,0,1.00)"
    },
    
    // 初始化
    oncreate: function(v) {
      var b, fullHexColor, g, hex, matches, r, rgbValues;
      this.updateMainCanvas();
      this.updateHueSlider();
      this.updateAlphaSlider();
      if (v.attrs.color) {
        // 处理16进制颜色值
        if (v.attrs.color.startsWith('#')) {
          hex = v.attrs.color.substring(1);
          // 如果是3位十六进制颜色值，转换为6位
          if (hex.length === 3) {
            hex = hex.split('').map(function(char) {
              return char + char;
            }).join('');
          }
          // 使用转换后的完整hex字符串创建新的颜色值
          fullHexColor = '#' + hex;
          rgbValues = hexToRgb(fullHexColor);
          [this.data.h, this.data.s, this.data.v] = rgbToHsv(...rgbValues);
          this.data.hexColor = fullHexColor;
        } else if (v.attrs.color.startsWith('rgb')) {
          // 处理RGB或RGBA格式
          matches = v.attrs.color.match(/\d+/g);
          if (matches.length >= 3) {
            r = parseInt(matches[0]) / 255;
            g = parseInt(matches[1]) / 255;
            b = parseInt(matches[2]) / 255;
            [this.data.h, this.data.s, this.data.v] = rgbToHsv(r, g, b);
            if (matches.length >= 4) {
              this.data.a = parseInt(matches[3]) || 1;
            }
          }
          this.data.hexColor = rgbToHex(r, g, b);
        } else {
          // 原来的RGB格式处理逻辑
          [r, g, b] = v.attrs.color.match(/\d+/g).map(function(x) {
            return parseInt(x) / 255;
          });
          [this.data.h, this.data.s, this.data.v] = rgbToHsv(r, g, b);
          this.data.hexColor = rgbToHex(r, g, b);
        }
        
          // 更新RGBA颜色显示
        [r, g, b] = hsvToRgb(this.data.h, this.data.s, this.data.v);
        this.data.rgbaColor = rgbToRgbaString(r, g, b, this.data.a);
        // 更新所有画布以反映新的颜色
        this.updateMainCanvas();
        this.updateHueSlider();
        this.updateAlphaSlider();
        // 调用m.redraw()确保视图正确更新
        return m.redraw();
      } else {
        // 初始化默认颜色
        [r, g, b] = hsvToRgb(this.data.h, this.data.s, this.data.v);
        this.data.hexColor = rgbToHex(r, g, b);
        this.data.rgbaColor = rgbToRgbaString(r, g, b, this.data.a);
        return this.updateMainCanvas();
      }
    },
    
    // 更新主画布
    updateMainCanvas: function() {
      var b, canvas, ctx, g, j, r, ref, results, s, size, v, x, y;
      canvas = document.getElementById("colorPickerMain");
      if (!canvas) {
        return;
      }
      ctx = canvas.getContext("2d");
      size = this.data.canvasSize;

      // 创建渐变
      results = [];
      for (y = j = 0, ref = size; (0 <= ref ? j < ref : j > ref); y = 0 <= ref ? ++j : --j) {
        results.push((function() {
          var k, ref1, results1;
          results1 = [];
          for (x = k = 0, ref1 = size; (0 <= ref1 ? k < ref1 : k > ref1); x = 0 <= ref1 ? ++k : --k) {
            s = x / size;
            v = 1 - y / size;
            [r, g, b] = hsvToRgb(this.data.h, s, v);
            ctx.fillStyle = `rgb(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)})`;
            results1.push(ctx.fillRect(x, y, 1, 1));
          }
          return results1;
        }).call(this));
      }
      return results;
    },
    
    // 更新色相滑块
    updateHueSlider: function() {
      var b, canvas, ctx, g, h, height, j, r, ref, results, width, x;
      canvas = document.getElementById("hueSlider");
      if (!canvas) {
        return;
      }
      ctx = canvas.getContext("2d");
      width = this.data.canvasSize;
      height = this.data.sliderHeight;

      // 创建色相渐变
      results = [];
      for (x = j = 0, ref = width; (0 <= ref ? j < ref : j > ref); x = 0 <= ref ? ++j : --j) {
        h = x / width * 360;
        [r, g, b] = hsvToRgb(h, 1, 1);
        ctx.fillStyle = `rgb(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)})`;
        results.push(ctx.fillRect(x, 0, 1, height));
      }
      return results;
    },
    
    // 更新透明度滑块
    updateAlphaSlider: function() {
      var b, canvas, ctx, g, gradient, height, j, k, r, ref, ref1, ref2, ref3, squareSize, width, x, y;
      canvas = document.getElementById("alphaSlider");
      if (!canvas) {
        return;
      }
      ctx = canvas.getContext("2d");
      width = this.data.canvasSize;
      height = this.data.sliderHeight;
      
      // 创建透明度渐变（从透明到不透明）
      gradient = ctx.createLinearGradient(0, 0, width, 0);
      [r, g, b] = hsvToRgb(this.data.h, this.data.s, this.data.v);
      gradient.addColorStop(0, `rgba(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)}, 0)`);
      gradient.addColorStop(1, `rgba(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)}, 1)`);
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, width, height);
      
      // 绘制棋盘背景表示透明度
      ctx.fillStyle = "#fff";
      ctx.fillRect(0, 0, width, height);
      ctx.fillStyle = "#ccc";
      squareSize = 4;
      for (x = j = 0, ref = width, ref1 = squareSize * 2; ref1 !== 0 && (ref1 > 0 ? j <= ref : j >= ref); x = j += ref1) {
        for (y = k = 0, ref2 = height, ref3 = squareSize * 2; ref3 !== 0 && (ref3 > 0 ? k <= ref2 : k >= ref2); y = k += ref3) {
          ctx.fillRect(x, y, squareSize, squareSize);
          ctx.fillRect(x + squareSize, y + squareSize, squareSize, squareSize);
        }
      }
      
      // 重新绘制渐变
      ctx.fillStyle = gradient;
      return ctx.fillRect(0, 0, width, height);
    },
    view: function(v) {
      var _this, getCurrentColor, getCurrentHexColor, getCurrentRgbaColor, handleHexInput, handlePointerDown, handlePointerMove, handlePointerUp, handleRgbaInput, padding, size, sliderHeight;
      _this = this;
      size = this.data.canvasSize;
      sliderHeight = this.data.sliderHeight;
      padding = this.data.padding;
      getCurrentColor = function() {
        var b, g, r;
        [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
        return `rgb(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)})`;
      };
      getCurrentRgbaColor = function() {
        var b, g, r;
        [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
        return rgbToRgbaString(r, g, b, _this.data.a);
      };
      getCurrentHexColor = function() {
        var b, g, r;
        [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
        return rgbToHex(r, g, b);
      };
      
      // 处理指针移动事件
      handlePointerMove = function(e) {
        var b, element, g, r, rect, x, y;
        if (!_this.data.dragging) {
          return;
        }
        
            // 根据当前拖动类型获取正确的元素来计算坐标
        switch (_this.data.dragging) {
          case "main":
            element = document.getElementById("colorPickerMain");
            rect = element.getBoundingClientRect();
            x = e.clientX - rect.left;
            y = e.clientY - rect.top;
            _this.data.s = Math.max(0, Math.min(1, x / size));
            _this.data.v = Math.max(0, Math.min(1, 1 - y / size));
            break;
          case "hue":
            element = document.getElementById("hueSlider");
            rect = element.getBoundingClientRect();
            x = e.clientX - rect.left;
            _this.data.h = Math.max(0, Math.min(360, (x / size) * 360));
            _this.updateMainCanvas();
            _this.updateAlphaSlider();
            break;
          case "alpha":
            element = document.getElementById("alphaSlider");
            rect = element.getBoundingClientRect();
            x = e.clientX - rect.left;
            _this.data.a = Math.max(0, Math.min(1, x / size));
            _this.updateAlphaSlider();
        }
        
        // 更新颜色显示
        _this.data.hexColor = getCurrentHexColor();
        _this.data.rgbaColor = getCurrentRgbaColor();
        
        // 确保onColorChange回调存在且是函数
        if (typeof v.attrs.onColorChange === 'function') {
          [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
          v.attrs.onColorChange(rgbToRgbaString(r, g, b, _this.data.a));
        }
        return m.redraw();
      };
      // 处理指针抬起事件
      handlePointerUp = function(e) {
        var b, g, r;
        _this.data.dragging = null;
        document.removeEventListener('pointermove', handlePointerMove);
        document.removeEventListener('pointerup', handlePointerUp);
        // 确保onColorSelect回调存在且是函数
        if (typeof v.attrs.onColorSelect === 'function') {
          [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
          v.attrs.onColorSelect(rgbToRgbaString(r, g, b, _this.data.a));
        }
        // 同时也触发onColorChange，确保最终颜色被更新
        if (typeof v.attrs.onColorChange === 'function') {
          [r, g, b] = hsvToRgb(_this.data.h, _this.data.s, _this.data.v);
          v.attrs.onColorChange(rgbToRgbaString(r, g, b, _this.data.a));
        }
        // 调用m.redraw()更新UI
        return m.redraw();
      };
      // 处理指针按下事件
      handlePointerDown = function(type) {
        return function(e) {
          _this.data.dragging = type;
          handlePointerMove(e);
          // 将事件监听器添加到document上，这样即使鼠标移出区域也能继续操作
          document.addEventListener('pointermove', handlePointerMove);
          return document.addEventListener('pointerup', handlePointerUp);
        };
      };
      
      // 处理十六进制颜色输入
      handleHexInput = function(e) {
        var b, g, hex, r;
        hex = e.target.value;
        if (/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(hex)) {
          _this.data.hexColor = hex;
          [r, g, b] = hexToRgb(hex);
          [_this.data.h, _this.data.s, _this.data.v] = rgbToHsv(r, g, b);
          _this.updateMainCanvas();
          _this.updateHueSlider();
          _this.updateAlphaSlider();
          _this.data.rgbaColor = getCurrentRgbaColor();
          if (v.attrs.onColorChange) {
            v.attrs.onColorChange(rgbToRgbaString(r, g, b, _this.data.a));
          }
          return m.redraw();
        }
      };
      
      // 处理RGBA颜色输入
      handleRgbaInput = function(e) {
        var a, b, g, matches, r, rgba;
        rgba = e.target.value;
        matches = rgba.match(/\d+/g);
        if (matches && matches.length >= 3) {
          r = parseInt(matches[0]) / 255;
          g = parseInt(matches[1]) / 255;
          b = parseInt(matches[2]) / 255;
          a = matches.length >= 4 ? parseFloat(matches[3]) : 1;
          [_this.data.h, _this.data.s, _this.data.v] = rgbToHsv(r, g, b);
          _this.data.a = Math.max(0, Math.min(1, a));
          _this.data.hexColor = getCurrentHexColor();
          _this.updateMainCanvas();
          _this.updateHueSlider();
          _this.updateAlphaSlider();
          if (v.attrs.onColorChange) {
            v.attrs.onColorChange(rgbToRgbaString(r, g, b, _this.data.a));
          }
          return m.redraw();
        }
      };
      return m("", {
        style: {
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
          userSelect: "none",
          backgroundColor: "white",
          borderRadius: "5px",
          padding: "1rem"
        }
      }, [
        // 主色彩选择区域
        m("",
        {
          style: {
            position: "relative",
            width: size + "px",
            height: size + "px"
          }
        },
        [
          m("canvas#colorPickerMain",
          {
            width: size,
            height: size,
            style: {
              width: "100%",
              height: "100%",
              cursor: "crosshair"
            },
            onpointerdown: handlePointerDown("main")
          }),
          
          // 选择点指示器
          m("",
          {
            style: {
              position: "absolute",
              left: this.data.s * size + "px",
              top: (1 - this.data.v) * size + "px",
              width: "10px",
              height: "10px",
              border: "2px solid white",
              borderRadius: "50%",
              transform: "translate(-50%, -50%)",
              pointerEvents: "none",
              boxShadow: "0 0 0 1px black"
            }
          })
        ]),
        
        // 色相滑块
        m("",
        {
          style: {
            position: "relative",
            width: size + "px",
            height: sliderHeight + "px",
            marginTop: "10px"
          }
        },
        [
          m("canvas#hueSlider",
          {
            width: size,
            height: sliderHeight,
            style: {
              width: "100%",
              height: "100%",
              cursor: "ew-resize"
            },
            onpointerdown: handlePointerDown("hue")
          }),
          
          // 色相滑块指示器
          m("",
          {
            style: {
              position: "absolute",
              left: (this.data.h / 360) * size + "px",
              top: "0",
              width: "4px",
              height: "100%",
              backgroundColor: "white",
              border: "1px solid black",
              transform: "translateX(-50%)",
              pointerEvents: "none"
            }
          })
        ]),
        
        // 透明度滑块
        m("",
        {
          style: {
            position: "relative",
            width: size + "px",
            height: sliderHeight + "px",
            marginTop: "10px"
          }
        },
        [
          m("canvas#alphaSlider",
          {
            width: size,
            height: sliderHeight,
            style: {
              width: "100%",
              height: "100%",
              cursor: "ew-resize"
            },
            onpointerdown: handlePointerDown("alpha")
          }),
          
          // 透明度滑块指示器
          m("",
          {
            style: {
              position: "absolute",
              left: this.data.a * size + "px",
              top: "0",
              width: "4px",
              height: "100%",
              backgroundColor: "white",
              border: "1px solid black",
              transform: "translateX(-50%)",
              pointerEvents: "none"
            }
          })
        ]),
        
        // 颜色输入区域
        m("",
        {
          style: {
            marginTop: "1rem",
            display: "flex",
            flexDirection: "column",
            gap: "10px"
          }
        },
        [
          // 十六进制颜色输入
          m("",
          {
            style: {
              display: "flex",
              alignItems: "center",
              gap: "10px"
            }
          },
          [
            m("label",
            {
              style: {
                fontSize: "14px",
                color: "#666",
                minWidth: "60px"
              }
            },
            "HEX:"),
            m("input",
            {
              type: "text",
              value: this.data.hexColor,
              style: {
                flex: 1,
                padding: "5px",
                border: "1px solid #ccc",
                borderRadius: "3px",
                fontSize: "14px",
                backgroundColor: getCurrentRgbaColor()
              },
              oninput: handleHexInput
            })
          ]),
          
          // RGBA颜色输入
          m("",
          {
            style: {
              display: "flex",
              alignItems: "center",
              gap: "10px"
            }
          },
          [
            m("label",
            {
              style: {
                fontSize: "14px",
                color: "#666",
                minWidth: "60px"
              }
            },
            "RGBA:"),
            m("input",
            {
              type: "text",
              value: this.data.rgbaColor,
              style: {
                flex: 1,
                padding: "5px",
                border: "1px solid #ccc",
                borderRadius: "3px",
                fontSize: "14px",
                backgroundColor: getCurrentRgbaColor()
              },
              oninput: handleRgbaInput
            })
          ])
        ])
      ]);
    }
  };
};


// 当前颜色预览
/*         m "",
  style:
    display: "flex"
    alignItems: "center"
    gap: "10px"
,[
  m "",
    style:
      width: "50px"
      height: "30px"
      backgroundColor: getCurrentRgbaColor()
      border: "1px solid #ccc"
      borderRadius: "3px"
] */
