// Generated by CoffeeScript 2.7.0
var svgText;

import Element from "./svgEditor_element.js";

import data from "./svgEditor_data.js";

export default svgText = class svgText extends Element {
  constructor(config) {
    super(config);
    this.type = "text";
    this.prop = {
      text: "",
      mode: "svg", // "svg" 或 "markdown"
      x: 0,
      y: 0,
      w: 200,
      h: 50,
      fontSize: 24,
      fontFamily: "Arial",
      color: data.colorTool.fgColor,
      fill: "none",
      stroke: "none",
      strokeWidth: 0,
      ...config.prop
    };
    this.update();
  }

  translate({deltaX, deltaY}) {
    this.prop.x += deltaX;
    this.prop.y += deltaY;
    return this.update();
  }

  update() {
    var canvas, ctx, lines, maxWidth, minH, minW;
    canvas = document.createElement("canvas");
    ctx = canvas.getContext("2d");
    ctx.font = `${this.prop.fontSize}px ${this.prop.fontFamily}`;
    lines = this.prop.text.split("\n");
    maxWidth = 0;
    lines.forEach(function(line) {
      var metrics;
      metrics = ctx.measureText(line);
      return maxWidth = Math.max(maxWidth, metrics.width);
    });
    minW = maxWidth + 30;
    minH = lines.length * this.prop.fontSize * 1.2 + 20;
    if (this.prop.mode === "svg") {
      this.prop.w = minW;
      return this.prop.h = minH;
    } else {
      this.prop.w = Math.max(this.prop.w, minW);
      return this.prop.h = Math.max(this.prop.h, minH);
    }
  }

  getBoundingBox() {
    return {
      minX: this.prop.x - 5,
      minY: this.prop.y - 10,
      maxX: this.prop.x + this.prop.w + 5,
      maxY: this.prop.y + this.prop.h + 10
    };
  }

  isIntersectBox(boxInfo) {
    var box, boxBottom, boxLeft, boxRight, boxTop;
    box = this.getBoundingBox();
    boxLeft = Math.min(boxInfo.x, boxInfo.x + boxInfo.w);
    boxRight = Math.max(boxInfo.x, boxInfo.x + boxInfo.w);
    boxTop = Math.min(boxInfo.y, boxInfo.y + boxInfo.h);
    boxBottom = Math.max(boxInfo.y, boxInfo.y + boxInfo.h);
    return !(box.maxX < boxLeft || box.minX > boxRight || box.maxY < boxTop || box.minY > boxBottom);
  }

};
