// Generated by CoffeeScript 2.7.0
export default {
  view: function() {
    return m("defs", [
      m("pattern",
      {
        id: "preFill",
        patternUnits: "userSpaceOnUse",
        width: "8",
        height: "8",
        patternTransform: "rotate(45)"
      },
      [
        m("line",
        {
          x1: 0,
          y1: 4,
          x2: 8,
          y2: 4,
          stroke: "#ffdb66",
          "stroke-width": "2"
        }),
        m("line",
        {
          x1: 4,
          y1: 0,
          x2: 4,
          y2: 8,
          stroke: "#ffdb66",
          "stroke-width": "2"
        })
      ])
    ]);
  }
};
