// Generated by CoffeeScript 2.7.0
var DebugWindow, DetailWindow, ObjectViewer, TreeNode, safeStringify;

import data from "./svgEditor_data.js";

import tools from "../tools.js";

// 带有循环引用保护的完整序列化
safeStringify = function(obj) {
  var cache;
  cache = new Set();
  return JSON.stringify(obj, function(key, value) {
    if (typeof value === 'object' && value !== null) {
      if (cache.has(value)) {
        return '[Circular]';
      }
      cache.add(value);
    }
    return value;
  }, 2);
};

ObjectViewer = function() {
  var showChild;
  showChild = false;
  return {
    view: function({attrs}) {
      var Box, Tag, e, isArray, keys, label, obj, typeStr, valStr;
      ({Box, Tag} = tools);
      obj = attrs.obj;
      label = attrs.label;
      if (!obj || typeof obj !== "object") {
        valStr = String(obj);
        return m("", {
          style: {
            display: "flex",
            justifyContent: "space-between",
            borderBottom: "1px solid #eee",
            padding: "0.5rem"
          }
        }, [
          m("span",
          {
            style: {
              fontWeight: "bold"
            }
          },
          label + ": "),
          m("span",
          {
            style: {
              flex: 1,
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
              marginLeft: "1rem"
            }
          },
          valStr),
          m(Tag,
          {
            isBtn: true,
            onclick: function() {
              navigator.clipboard.writeText(valStr);
              return tools.Tip.launch(`已复制 ${label}`);
            }
          },
          "复制")
        ]);
      }
      
      // 如果是对象或数组
      isArray = Array.isArray(obj);
      typeStr = isArray ? `[Array(${obj.length})]` : "[Object]";
      keys = [];
      try {
        keys = Object.keys(obj);
      } catch (error) {
        e = error;
        keys = [];
      }
      return m("", {
        style: {
          borderBottom: "1px solid #eee",
          padding: "0.5rem"
        }
      }, [
        m("",
        {
          style: {
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between"
          }
        },
        [
          m("",
          {
            style: {
              display: "flex",
              alignItems: "center"
            }
          },
          [
            keys.length > 0 ? m(Tag,
            {
              isBtn: true,
              onclick: function() {
                return showChild = !showChild;
              }
            },
            showChild ? "-" : "+") : void 0,
            m("span",
            {
              style: {
                fontWeight: "bold",
                marginLeft: keys.length > 0 ? "0.5rem" : "0"
              }
            },
            label + ": "),
            m("span",
            {
              style: {
                color: "#888",
                marginLeft: "0.5rem"
              }
            },
            typeStr)
          ]),
          m(Tag,
          {
            isBtn: true,
            onclick: function() {
              navigator.clipboard.writeText(typeStr);
              return tools.Tip.launch("已复制类型描述");
            }
          },
          "复制")
        ]),
        showChild && keys.length > 0 ? m("",
        {
          style: {
            marginLeft: "1rem",
            borderLeft: "1px solid #ddd",
            paddingLeft: "1rem",
            marginTop: "0.5rem"
          }
        },
        [
          keys.map((k) => {
            return m(ObjectViewer,
          {
              key: k,
              label: k,
              obj: obj[k]
            });
          })
        ]) : void 0
      ]);
    }
  };
};

DetailWindow = function() {
  return {
    view: function({attrs}) {
      var Box, Tag, element, getProps;
      ({Box, Tag} = tools);
      element = attrs.element;
      if (!element) {
        return m(Box, "获取不到元件参数");
      }
      
      // 获取可读属性 (排除循环引用)
      getProps = function(obj) {
        var k, res, v;
        res = {};
        for (k in obj) {
          v = obj[k];
          if (k === "parentGroup" || k === "fillGroups" || k === "elements" || k === "pureFill" || k === "childRegions" || k === "fillGroupInners" || k === "points") {
            res[k] = v ? `[Object/Array(${v.length || ''})]` : "null";
          } else {
            res[k] = v;
          }
        }
        return res;
      };
      return m("", {
        style: {
          padding: "1rem",
          overflow: "auto"
        }
      }, [
        m("h3",
        `[${element.type}] 详情 (ID: ${element.id.slice(0, 7)})`),
        m(Box,
        {
          isBtn: true,
          color: "main",
          onclick: function() {
            var propStr;
            propStr = JSON.stringify(getProps(element.prop),
        null,
        2);
            navigator.clipboard.writeText(propStr);
            return tools.Tip.launch("已复制所有属性");
          }
        },
        "一键复制所有属性"),
        m("",
        {
          style: {
            marginTop: "1rem"
          }
        },
        [
          Object.keys(element).map((key) => {
            return m(ObjectViewer,
          {
              key: key,
              label: key,
              obj: element[key]
            });
          })
        ])
      ]);
    }
  };
};

TreeNode = function() {
  return {
    view: function({attrs}) {
      var Box, Notice, Tag, element;
      ({Box, Tag, Notice} = tools);
      element = attrs.element;
      return m("", {
        style: {
          padding: "0.5rem",
          margin: "0.2rem 0",
          border: element.isChoised ? "1px solid #ffcc00" : "1px solid #ccc",
          background: element.isChoised ? "#fff9e6" : data.presentGroup === element ? "#eef" : "transparent",
          cursor: "pointer"
        },
        onclick: function(e) {
          e.stopPropagation();
          if (!(e.metaKey || e.ctrlKey || e.shiftKey)) {
            data.elPaper.elements.forEach(function(el) {
              if (el !== element) {
                return el.isChoised = false;
              }
            });
          }
          element.isChoised = !element.isChoised;
          return m.redraw();
        }
      }, [
        m("",
        {
          style: {
            display: "flex",
            alignItems: "center"
          }
        },
        [
          m("span",
          {
            style: {
              fontWeight: element.type === "group" || element.type === "fillGroup" ? "bold" : "normal",
              color: element.isChoised ? "#b28900" : "inherit"
            }
          },
          `[${element.type}] ${element.id.slice(0, 7)}` + (element.isChoised ? " (已选中)" : "")),
          m(Tag,
          {
            isBtn: true,
            onclick: function() {
              return Notice.launch({
                tip: "属性详情",
                content: DetailWindow,
                contentAttrs: {
                  element: element
                }
              });
            }
          },
          "详情")
        ])
      ]);
    }
  };
};

export default DebugWindow = function() {
  var orderMode;
  orderMode = "canvas"; // "canvas" 或 "array"
  return {
    view: function() {
      var Box, elements, renderTree, rootElements, sortElements, treeDataStr;
      ({Box} = tools);
      
      // 获取所有的元素，和主画布保持扁平化一致
      elements = data.elPaper.getList();
      treeDataStr = safeStringify(elements);
      // 提取根节点
      rootElements = elements.filter(function(el) {
        return !el.prop.parentGroup;
      });
      
      // 定义排序函数
      sortElements = function(elList) {
        if (orderMode === "canvas") {
          return elList.slice().sort((a, b) => {
            var aIsGroup, bIsGroup;
            aIsGroup = a.type === "group";
            bIsGroup = b.type === "group";
            if (aIsGroup && !bIsGroup) {
              return 1;
            }
            if (!aIsGroup && bIsGroup) {
              return -1;
            }
            return elements.indexOf(a) - elements.indexOf(b);
          });
        } else {
          // 数组顺序：完全按 elements 的数组顺序渲染
          return elList.slice().sort((a, b) => {
            return elements.indexOf(a) - elements.indexOf(b);
          });
        }
      };
      // 定义递归渲染函数
      renderTree = function(elList, level = 0) {
        var sortedList;
        sortedList = sortElements(elList);
        return sortedList.map(function(el) {
          var children;
          // 从扁平数组中找出所有把当前元素认作父组的孩子
          children = elements.filter(function(child) {
            var ref;
            return ((ref = child.prop) != null ? ref.parentGroup : void 0) === el;
          });
          return m("", {
            key: el.id,
            style: {
              marginLeft: `${level * 1.5}rem`
            }
          }, [
            m(TreeNode,
            {
              element: el
            }),
            children.length > 0 ? renderTree(children,
            level + 1) : void 0
          ]);
        });
      };
      return m("", {
        style: {
          padding: "1rem",
          overflow: "auto"
        }
      }, [
        // 切换排序顺序的按钮组
        m(Box,
        {
          style: {
            display: "flex",
            gap: "10px",
            marginBottom: "1rem"
          }
        },
        [
          m(Box,
          {
            isBtn: true,
            color: (orderMode === "canvas" ? "main" : "unset"),
            style: {
              flex: 1,
              textAlign: "center",
              margin: 0
            },
            onclick: function() {
              orderMode = "canvas";
              return m.redraw();
            }
          },
          "画布顺序"),
          m(Box,
          {
            isBtn: true,
            color: (orderMode === "array" ? "main" : "unset"),
            style: {
              flex: 1,
              textAlign: "center",
              margin: 0
            },
            onclick: function() {
              orderMode = "array";
              return m.redraw();
            }
          },
          "数组顺序")
        ]),
        m(Box,
        {
          style: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "1rem"
          }
        },
        [
          "显示画布物理坐标与锚点",
          m(Box,
          {
            isSwitch: true,
            color: "main",
            onclick: () => {
              data.switchDebug();
              return m.redraw();
            },
            value: data.debug
          })
        ]),
        m(Box,
        {
          isBtn: true,
          color: "main",
          onclick: function() {
            navigator.clipboard.writeText(treeDataStr);
            return tools.Tip.launch("已复制树状数据");
          }
        },
        "一键复制当前扁平化画布Elements数据"),
        m("",
        {
          style: {
            marginTop: "1rem"
          }
        },
        [renderTree(rootElements)])
      ]);
    }
  };
};
