// Generated by CoffeeScript 2.7.0
var PureFill;

import data from "./svgEditor_data.js";

import Element from "./svgEditor_element.js";

import sortRegionElements from "./tools/sortRegionElements.js";

import pointInRegions from "./tools/pointInRegions.js";

import tools from "../tools.js";

export default PureFill = class PureFill extends Element {
  constructor(config) {
    var ref;
    if (!config.prop.elements) {
      throw new Error("PureFill类构造函数config.prop.elements不能为空");
    }
    config.type = "pureFill";
    super(config);
    this.type = "pureFill";
    this.prop.fill = (config != null ? (ref = config.prop) != null ? ref.fill : void 0 : void 0) || data.colorTool.bgColor;
    this.prop.stroke = "none";
    //克隆元素，避免引用
    this.recreateElements(config.prop.elements, config.prop.childRegions);
  }

  recreateElements(elements, childRegions) {
    this.prop.elements = elements.map((el) => {
      return new Element({
        ...el,
        id: tools.uuid(),
        prop: {
          ...el.prop,
          parentGroup: null,
          points: el.prop.points.map((point) => {
            return {
              x: point.x,
              y: point.y
            };
          })
        }
      });
    });
    
    // 处理子区域元素
    this.prop.childRegions = [];
    if (childRegions) {
      return this.prop.childRegions = childRegions.map((region) => {
        return region.map((el) => {
          return new Element({
            ...el,
            id: tools.uuid(),
            prop: {
              ...el.prop,
              parentGroup: null,
              points: el.prop.points.map((point) => {
                return {
                  x: point.x,
                  y: point.y
                };
              })
            }
          });
        });
      });
    }
  }

  getBoundingBox() {
    var maxX, maxY, minX, minY, ref;
    minX = 2e308;
    minY = 2e308;
    maxX = -2e308;
    maxY = -2e308;
    if ((ref = this.prop.elements) != null) {
      ref.forEach((el) => {
        var box;
        if (el.getBoundingBox) {
          box = el.getBoundingBox();
          if (box) {
            minX = Math.min(minX, box.minX);
            minY = Math.min(minY, box.minY);
            maxX = Math.max(maxX, box.maxX);
            return maxY = Math.max(maxY, box.maxY);
          }
        }
      });
    }
    if (minX === 2e308) {
      return null;
    }
    return {
      minX: minX,
      minY: minY,
      maxX: maxX,
      maxY: maxY,
      x: minX,
      y: minY,
      w: maxX - minX,
      h: maxY - minY
    };
  }

  getSvgPath() {
    var childRegion, err, i, len, ref, ref1, sortedChildRegions, sortedRegions, str;
    try {
      if (((ref = this.prop.elements) != null ? ref.length : void 0) < 1) {
        return "";
      }
      
      // 使用排序函数对元素进行排序
      sortedRegions = sortRegionElements(this.prop.elements);
      str = "";
      
      // 生成父区域路径
      sortedRegions.forEach((el, index) => {
        var points;
        if (index === 0) {
          str += `M ${el.s().x} ${el.s().y} `;
        }
        points = el.getControlPoints();
        switch (points.length) {
          case 0:
            return str += `L ${el.e().x} ${el.e().y} `;
          case 1:
            return str += `Q ${points[0].x} ${points[0].y} ${el.e().x} ${el.e().y} `;
          case 2:
            return str += `C ${points[0].x} ${points[0].y} ${points[1].x} ${points[1].y} ${el.e().x} ${el.e().y} `;
        }
      });
      
      // 闭合父区域路径
      str += "Z ";
      ref1 = this.prop.childRegions;
      
      // 添加子区域路径（用于挖空）
      for (i = 0, len = ref1.length; i < len; i++) {
        childRegion = ref1[i];
        if ((childRegion != null ? childRegion.length : void 0) > 0) {
          sortedChildRegions = sortRegionElements(childRegion);
          sortedChildRegions.forEach((el, index) => {
            var points;
            if (index === 0) {
              str += `M ${el.s().x} ${el.s().y} `;
            }
            points = el.getControlPoints();
            switch (points.length) {
              case 0:
                return str += `L ${el.e().x} ${el.e().y} `;
              case 1:
                return str += `Q ${points[0].x} ${points[0].y} ${el.e().x} ${el.e().y} `;
              case 2:
                return str += `C ${points[0].x} ${points[0].y} ${points[1].x} ${points[1].y} ${el.e().x} ${el.e().y} `;
            }
          });
          // 闭合子区域路径
          str += "Z ";
        }
      }
      return str;
    } catch (error) {
      err = error;
      console.log("svg路径获取错误，解散填充组");
      this.prop.fillGroup.break();
      this.remove();
      return "";
    }
  }

  translate({deltaX, deltaY}) {
    this.prop.elements.forEach((el) => {
      return el.translate({deltaX, deltaY});
    });
    
    // 同时平移子区域元素
    return this.prop.childRegions.forEach((childRegion) => {
      return childRegion.forEach((el) => {
        return el.translate({deltaX, deltaY});
      });
    });
  }

  joinFillGroup(fillGroup) {
    //双向引用
    if (this.prop.fillGroups.indexOf(fillGroup) === -1) {
      this.prop.fillGroups.push(fillGroup);
    } else {
      console.log("警告：纯填充已经在填充组,无法加入");
    }
    return fillGroup.prop.pureFill = this;
  }

  exitFillGroup(fillGroup) {
    var elIndex, myIndex;
    elIndex = this.prop.fillGroups.indexOf(fillGroup);
    if (elIndex !== -1) {
      this.prop.fillGroups.splice(elIndex, 1);
    } else {
      console.log("警告：纯填充已经不在填充组，无法退出");
    }
    myIndex = fillGroup.prop.elements.indexOf(this);
    return fillGroup.prop.pureFill = null;
  }

  isPointInRegion(site) {
    var childRegions, pointInChildren, pointInElements;
    pointInElements = pointInRegions(site, [
      {
        elements: this.prop.elements,
        children: []
      }
    ]);
    childRegions = this.prop.childRegions.map((region) => {
      return {
        elements: region,
        children: []
      };
    });
    pointInChildren = pointInRegions(site, childRegions);
    return pointInElements.length > 0 && pointInChildren.length === 0;
  }

};
