// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

import ColorPanel from "./svgEditor_colorPanel.js";

import tools from "../tools.js";

export default function() {
  var Box, getColor;
  ({Box, getColor} = tools);
  return {
    oncreate: function() {
      return console.log(data.colorTool.presentColor);
    },
    view: function() {
      var recentUseColor;
      recentUseColor = data.colorTool.recentUseColor;
      return m("", [
        m("",
        {
          style: {
            display: "flex"
          }
        },
        [
          m(Box,
          {
            isBtn: true,
            style: {
              flex: 1,
              margin: 0,
              borderRadius: "unset",
              borderBottom: data.colorTool.presentColor === "full" ? `0.2rem solid ${getColor("main").back}` : "none",
              background: data.colorTool.presentColor === "full" ? "unset" : "#eee"
            },
            onclick: () => {
              return data.colorTool.presentColor = "full";
            }
          },
          "填充色"),
          m(Box,
          {
            isBtn: true,
            style: {
              flex: 1,
              margin: 0,
              borderRadius: "unset",
              borderBottom: data.colorTool.presentColor === "stroke" ? `0.2rem solid ${getColor("main").back}` : "none",
              background: data.colorTool.presentColor === "stroke" ? "unset" : "#eee"
            },
            onclick: () => {
              return data.colorTool.presentColor = "stroke";
            }
          },
          "线条色")
        ]),
        m("",
        {
          style: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            margin: "1rem 0",
            padding: "0 1rem"
          }
        },
        [
          recentUseColor.map((color) => {
            return m("",
          {
              style: {
                width: "2rem",
                height: "2rem",
                margin: "0.2rem",
                borderRadius: "50%",
                border: "0.1rem solid #aaa",
                background: color,
                cursor: "pointer"
              },
              onclick: () => {
                if (data.colorTool.presentColor === "full") {
                  data.colorTool.bgColor = color;
                } else if (data.colorTool.presentColor === "stroke") {
                  data.colorTool.fgColor = color;
                }
                return data.colorTool.setRecentUseColor(color);
              }
            });
          })
        ]),
        data.colorTool.presentColor === "full" ? m(ColorPanel,
        {
          color: data.colorTool.bgColor, // 可选的初始颜色
          onColorChange: function(color) { // 颜色变化时的回调
            return data.colorTool.bgColor = color;
          },
          onColorSelect: function(color) { // 用户完成选择时的回调
            data.colorTool.bgColor = color;
            return data.colorTool.setRecentUseColor(color);
          }
        }) : data.colorTool.presentColor === "stroke" ? m(ColorPanel,
        {
          color: data.colorTool.fgColor, // 可选的初始颜色
          onColorChange: function(color) { // 颜色变化时的回调
            return data.colorTool.fgColor = color;
          },
          onColorSelect: function(color) { // 用户完成选择时的回调
            data.colorTool.fgColor = color;
            return data.colorTool.setRecentUseColor(color);
          }
        }) : void 0,
        m(Box,
        [
          m("span",
          "线条宽度"),
          m("input",
          {
            type: "range",
            min: 1,
            max: 100,
            value: data.colorTool.strokeWidth,
            oninput: (e) => {
              data.colorTool.strokeWidth = e.target.value;
              return data.elPaper.elements.forEach((line) => {
                if (line.type === "line" && line.isChoised) {
                  return line.prop.strokeWidth = data.colorTool.strokeWidth;
                }
              });
            }
          }),
          //输入框
          m("input",
          {
            type: "number",
            min: 1,
            max: 100,
            value: data.colorTool.strokeWidth,
            oninput: (e) => {
              data.colorTool.strokeWidth = e.target.value;
              return data.elPaper.elements.forEach((line) => {
                if (line.type === "line" && line.isChoised) {
                  return line.prop.strokeWidth = data.colorTool.strokeWidth;
                }
              });
            }
          })
        ])
      ]);
    }
  };
};
