// Generated by CoffeeScript 2.7.0
import data from "./svgEditor_data.js";

export default {
  view: function() {
    return m("defs", [
      m("pattern",
      {
        id: "choisedFill",
        patternUnits: "userSpaceOnUse",
        patternTransform: `scale(${1 / data.globalZoom})`,
        width: "6",
        height: "6"
      },
      [
        m("circle",
        {
          cx: 1.5,
          cy: 1.5,
          r: 1,
          fill: "#000000"
        }),
        m("circle",
        {
          cx: 4.5,
          cy: 1.5,
          r: 1,
          fill: "#ffffff"
        }),
        m("circle",
        {
          cx: 1.5,
          cy: 4.5,
          r: 1,
          fill: "#ffffff"
        }),
        m("circle",
        {
          cx: 4.5,
          cy: 4.5,
          r: 1,
          fill: "#000000"
        })
      ])
    ]);
  }
};
