// Generated by CoffeeScript 2.7.0
var indexOf = [].indexOf;

import data from "./svgEditor_data.js";

import Element from "./svgEditor_element.js";

import Ellipse from "./svgEditor_ellipse.js";

import Rect from "./svgEditor_rect.js";

import Group from "./svgEditor_group.js";

import FillGroup from "./svgEditor_fillGroup.js";

import PureFill from "./svgEditor_pureFill.js";

import Text from "./svgEditor_text.js";

import tools from "../tools.js";

export default {
  // ==========================================
  // 核心：将选中的 SVG 图元及其所属关系扁平化、脱水为 JSON
  // 并且完全依照画布全局数组的顺序进行抽取以保证层级顺序
  // ==========================================
  serializeElements: function(elements) {
    var el, i, innerEl, isTargetOrDescendant, j, k, l, len, len1, len2, len3, len4, len5, m, node, o, p, ref, ref1, ref2, ref3, region, serializedList, targetEls, v;
    serializedList = [];
    
    // 辅助判断：元素是否属于目标集合，或者它的祖先属于目标集合
    isTargetOrDescendant = function(el) {
      var cur, ref;
      cur = el;
      while (cur) {
        if (elements.includes(cur)) {
          return true;
        }
        cur = (ref = cur.prop) != null ? ref.parentGroup : void 0;
      }
      return false;
    };
    targetEls = [];
    ref = data.elPaper.elements;
    
    // 1. 按照画布全局数组顺序扫描（严格保证相对层级顺序）
    for (i = 0, len = ref.length; i < len; i++) {
      el = ref[i];
      if (el.type === "fillGroup") {
        continue; // 遵循业务逻辑：永不复制由切割生成的逻辑填充组
      }
      if (isTargetOrDescendant(el)) {
        targetEls.push(el);
      }
    }

    // 2. 纯填充内部的边线因属于私有逻辑资产不在主画布中，手工追加至尾部
    for (j = 0, len1 = targetEls.length; j < len1; j++) {
      el = targetEls[j];
      if (el.type === "pureFill") {
        if (el.prop.elements) {
          ref1 = el.prop.elements;
          for (l = 0, len2 = ref1.length; l < len2; l++) {
            innerEl = ref1[l];
            if (indexOf.call(targetEls, innerEl) < 0) {
              targetEls.push(innerEl);
            }
          }
        }
        if (el.prop.childRegions) {
          ref2 = el.prop.childRegions;
          for (m = 0, len3 = ref2.length; m < len3; m++) {
            region = ref2[m];
            for (o = 0, len4 = region.length; o < len4; o++) {
              innerEl = region[o];
              if (indexOf.call(targetEls, innerEl) < 0) {
                targetEls.push(innerEl);
              }
            }
          }
        }
      }
    }
// 3. 转化为脱水节点
    for (p = 0, len5 = targetEls.length; p < len5; p++) {
      el = targetEls[p];
      node = {
        id: el.id,
        type: el.type,
        isClosed: el.isClosed,
        isChoised: false,
        isActive: el.isActive,
        prop: {}
      };
      ref3 = el.prop;
      
      // 复制基础 prop
      for (k in ref3) {
        v = ref3[k];
        if (k !== 'fillGroups' && k !== 'fillGroupInners' && k !== 'parentGroup' && k !== 'elements' && k !== 'childRegions' && k !== 'pureFill') {
          if (Array.isArray(v)) {
            node.prop[k] = JSON.parse(JSON.stringify(v));
          } else if (typeof v === 'object' && v !== null) {
            node.prop[k] = JSON.parse(JSON.stringify(v));
          } else {
            node.prop[k] = v;
          }
        }
      }
      
      // 转换关系引用为 ID，并且严格只保留在 targetEls (即将被复制集合) 内部的兄弟
      if (el.prop.parentGroup && targetEls.includes(el.prop.parentGroup)) {
        node.prop.parentGroup = el.prop.parentGroup.id;
      }
      if (el.prop.elements) {
        node.prop.elements = el.prop.elements.filter(function(child) {
          return targetEls.includes(child);
        }).map(function(child) {
          return child.id;
        });
      }
      if (el.prop.fillGroups) {
        node.prop.fillGroups = el.prop.fillGroups.filter(function(fg) {
          return targetEls.includes(fg);
        }).map(function(fg) {
          return fg.id;
        });
      }
      if (el.prop.fillGroupInners) {
        node.prop.fillGroupInners = el.prop.fillGroupInners.filter(function(fg) {
          return targetEls.includes(fg);
        }).map(function(fg) {
          return fg.id;
        });
      }
      if (el.prop.pureFill && targetEls.includes(el.prop.pureFill)) {
        node.prop.pureFill = el.prop.pureFill.id;
      }
      if (el.prop.childRegions) {
        node.prop.childRegions = el.prop.childRegions.map(function(region) {
          return region.filter(function(child) {
            return targetEls.includes(child);
          }).map(function(child) {
            return child.id;
          });
        });
      }
      serializedList.push(node);
    }
    return serializedList;
  },
  // ==========================================
  // 核心：根据一维的 JSON 快照数据，瞬间重建完整的双向图拓扑
  // 支持 assignNewIds: 分配新 UUID 并重缝合拓扑关系
  // 支持 returnStruct: 同时返回全量元素 elements 与 顶层元素 topLevelElements
  // ==========================================
  deserializeElements: function(snapshotList, options = {}) {
    var allElements, config, i, id, idMap, inst, instances, j, k, l, len, len1, len2, len3, len4, m, node, o, ref, ref1, ref2, safeProp, snapshotIds, topLevelElements, v;
    // 场景需要时为快照重新分发独立的 UUID
    if (options.assignNewIds) {
      snapshotList = JSON.parse(JSON.stringify(snapshotList));
      idMap = {};
      for (i = 0, len = snapshotList.length; i < len; i++) {
        node = snapshotList[i];
        idMap[node.id] = tools.uuid();
        node.id = idMap[node.id];
      }
      for (j = 0, len1 = snapshotList.length; j < len1; j++) {
        node = snapshotList[j];
        if (node.prop.elements) {
          node.prop.elements = node.prop.elements.map(function(old) {
            return idMap[old] || old;
          });
        }
        if (node.prop.parentGroup) {
          node.prop.parentGroup = idMap[node.prop.parentGroup] || node.prop.parentGroup;
        }
        if (node.prop.fillGroups) {
          node.prop.fillGroups = node.prop.fillGroups.map(function(old) {
            return idMap[old] || old;
          });
        }
        if (node.prop.fillGroupInners) {
          node.prop.fillGroupInners = node.prop.fillGroupInners.map(function(old) {
            return idMap[old] || old;
          });
        }
        if (node.prop.pureFill) {
          node.prop.pureFill = idMap[node.prop.pureFill] || node.prop.pureFill;
        }
        if (node.prop.childRegions) {
          node.prop.childRegions = node.prop.childRegions.map(function(arr) {
            return arr.map(function(old) {
              return idMap[old] || old;
            });
          });
        }
      }
    }
    // 1. 实例化字典：根据 type new 出对应的空实例
    instances = {};
    for (l = 0, len2 = snapshotList.length; l < len2; l++) {
      node = snapshotList[l];
      // 忽略 fillGroup 类型（填充组依靠画布动态重建，不反序列化）
      if (node.type === "fillGroup") {
        continue;
      }
      safeProp = {};
      ref = node.prop;
      for (k in ref) {
        v = ref[k];
        if (k !== 'fillGroups' && k !== 'fillGroupInners' && k !== 'parentGroup' && k !== 'elements' && k !== 'childRegions' && k !== 'pureFill') {
          safeProp[k] = JSON.parse(JSON.stringify(v));
        } else {
          if (k === 'elements' || k === 'fillGroups' || k === 'fillGroupInners' || k === 'childRegions') {
            safeProp[k] = [];
          } else {
            safeProp[k] = null;
          }
        }
      }
      config = {
        id: node.id,
        type: node.type,
        isClosed: node.isClosed,
        isActive: node.isActive,
        prop: safeProp
      };
      
      // 根据类型实例化
      inst = (function() {
        switch (node.type) {
          case "line":
            return new Element(config);
          case "pureFill":
            return new PureFill(config);
          case "group":
            return new Group(config);
          case "ellipse":
            return new Ellipse(config);
          case "rect":
            return new Rect(config);
          case "text":
            return new Text(config);
          default:
            return new Element(config);
        }
      })();
      instances[node.id] = inst;
    }
// 2. 第二遍扫描：缝合所有的 ID 指针为实际的内存引用
    for (m = 0, len3 = snapshotList.length; m < len3; m++) {
      node = snapshotList[m];
      inst = instances[node.id];
      if (!inst) {
        continue;
      }
      if (node.prop.parentGroup) {
        inst.prop.parentGroup = instances[node.prop.parentGroup] || null;
      }
      if (node.prop.elements) {
        inst.prop.elements = node.prop.elements.map(function(id) {
          return instances[id];
        }).filter(function(x) {
          return x;
        });
      }
      if (node.prop.fillGroups) {
        inst.prop.fillGroups = node.prop.fillGroups.map(function(id) {
          return instances[id];
        }).filter(function(x) {
          return x;
        });
      }
      if (node.prop.fillGroupInners) {
        inst.prop.fillGroupInners = node.prop.fillGroupInners.map(function(id) {
          return instances[id];
        }).filter(function(x) {
          return x;
        });
      }
      if (node.prop.pureFill) {
        inst.prop.pureFill = instances[node.prop.pureFill] || null;
      }
      if (node.prop.childRegions) {
        inst.prop.childRegions = node.prop.childRegions.map(function(region) {
          return region.map(function(id) {
            return instances[id];
          }).filter(function(x) {
            return x;
          });
        });
      }
    }
// 2.5 修正状态并防止虚拟节点外溢
    for (id in instances) {
      inst = instances[id];
      if (inst.type === "pureFill") {
        if ((ref1 = inst.prop.elements) != null) {
          ref1.forEach(function(el) {
            return el.isPureFillInner = true;
          });
        }
        if ((ref2 = inst.prop.childRegions) != null) {
          ref2.forEach(function(region) {
            return region.forEach(function(el) {
              return el.isPureFillInner = true;
            });
          });
        }
      }
      if (typeof inst.update === "function") {
        inst.update();
      }
    }
    // 3. 找出所有合法的实例 (过滤掉 pureFill 内部辅助线) 以及顶级图元
    snapshotIds = new Set(snapshotList.map(function(n) {
      return n.id;
    }));
    allElements = [];
    topLevelElements = [];
    for (o = 0, len4 = snapshotList.length; o < len4; o++) {
      node = snapshotList[o];
      inst = instances[node.id];
      if (inst && !inst.isPureFillInner) {
        allElements.push(inst);
        if (!inst.prop.parentGroup || !snapshotIds.has(inst.prop.parentGroup.id)) {
          topLevelElements.push(inst);
        }
      }
    }
    if (options.returnStruct) {
      return {
        elements: allElements,
        topLevelElements: topLevelElements
      };
    } else {
      return allElements;
    }
  },
  // ==========================================
  // 生成完整的带数据存档的 SVG 字符串（待完善展示部分的 DOM 组装）
  // ==========================================
  exportSvg: function(elements) {
    var jsonString, pureData, svgHtml;
    pureData = this.serializeElements(elements);
    jsonString = JSON.stringify(pureData);
    
    // 构建包含数据的完整 SVG 结构
    svgHtml = `<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1000 1000">
  <!-- 此处可以加入可见的渲染节点（如 <path>）以供外部预览 -->
  
  <!-- Owo Editor 隐写快照数据 -->
  <script type="application/json" id="owo-meta">
    ${jsonString}
  </script>
</svg>`;
    return svgHtml;
  }
};
