// Generated by CoffeeScript 2.7.0
var hasProp = {}.hasOwnProperty;

import data from "../../svgEditor_data.js";

import searchAngle from "./searchAngle.js";

export default (elements) => {
  var count, key, maxChild, minChild, nextVertex, plan, plans, prevVertex, startVertex, vertex, vertices, verticesArr;
  console.clear();
  vertices = data.elPaper.getVertices();
  console.log("顶点列表", vertices);
  plans = [];
  verticesArr = (function() {
    var results;
    results = [];
    for (key in vertices) {
      if (!hasProp.call(vertices, key)) continue;
      vertex = vertices[key];
      results.push(vertex);
    }
    return results;
  })();
  count = 0;
  while (verticesArr.length > 0) {
    count++;
    if (count > 20) {
      console.log("循环异常终止" + count);
      break;
    }
    vertex = (() => {
      var index, item, minVertex;
      //查找site位于最下左的vertex,顺便移除悬挂边
      index = verticesArr.length - 1;
      minVertex = verticesArr[index];
      while (index >= 0) {
        item = verticesArr[index];
        if (item.children.length <= 1) { //移除悬挂边
          verticesArr.splice(index, 1);
          verticesArr.forEach((v) => {
            return v.removeChild(item);
          });
          index = verticesArr.length - 1;
          console.log("移除悬挂边");
          continue;
        }
        if (item.site.y > minVertex.site.y || (item.site.y === minVertex.site.y && item.site.x < minVertex.site.x)) {
          minVertex = item;
        }
        index--;
      }
      return minVertex;
    })();
    if (verticesArr.length === 0) { //如果移除边后已经没有元素了
      break;
    }
    ({minChild} = searchAngle(vertex));
    startVertex = prevVertex = vertex;
    nextVertex = minChild != null ? minChild.linkVertex : void 0;
    console.log("startVertex", startVertex.site);
    plan = [startVertex];
    while ((nextVertex != null) && (nextVertex !== startVertex)) {
      if (plan.indexOf(nextVertex) === -1) {
        plan.push(nextVertex);
        //删除连接关系，防止循环查找
        if (nextVertex.children.length === 2) {
          nextVertex.removeChild(prevVertex);
          prevVertex.removeChild(nextVertex);
        }
        ({maxChild} = searchAngle(prevVertex, nextVertex));
        console.log({
          "输入向量": prevVertex.site
        }, nextVertex.site);
        console.log("顺时针最大向量夹角", maxChild);
        prevVertex = nextVertex;
        nextVertex = maxChild != null ? maxChild.linkVertex : void 0;
      } else {
        //删除连接关系，防止循环查找
        if (nextVertex.children.length === 2) {
          nextVertex.removeChild(prevVertex);
          prevVertex.removeChild(nextVertex);
        }
        console.log("清除前plan");
        plan.forEach((item) => {
          return console.log(item.site);
        });
        console.log("next", nextVertex.site);
        console.log("清除了");
        plan = [];
        break;
      }
    }
    //if plan.length > 0 
    //  plan.unshift startVertex
    console.log("plan");
    plan.forEach((item) => {
      return console.log(item.site);
    });
    console.log("===");
    console.log(verticesArr);
  }
  return [];
};
