// Generated by CoffeeScript 2.7.0
var searchAngle;

export default searchAngle = (vertex, vertex2) => {
  var child, children, i, len, maxAngle, maxAngleChild, minAngle, minAngleChild, vector;
  if (!vertex) {
    console.log({vertex});
    throw new Error("vertex错误 searchAngle");
  }
  
  // 逆时针角度
  maxAngleChild = null;
  minAngleChild = null;
  maxAngle = 0;
  minAngle = 2e308;
  if (vertex2) {
    vector = {
      x: vertex.site.x - vertex2.site.x,
      y: vertex.site.y - vertex2.site.y
    };
  }
  children = vertex2 ? vertex2.children : vertex.children;
  for (i = 0, len = children.length; i < len; i++) {
    child = children[i];
    ((child) => {
      var angle, angle2, childVertex, cross, deltaX, deltaY, dot, vector2;
      childVertex = child.linkVertex;
      deltaX = childVertex.site.x - vertex.site.x;
      deltaY = childVertex.site.y - vertex.site.y;
      angle = Math.atan2(deltaY, deltaX);
      if (vertex2) { //如果是2个顶点，计算向量夹角
        if (childVertex === vertex) { //跳过起点
          return;
        }
        vector2 = {
          x: childVertex.site.x - vertex2.site.x,
          y: childVertex.site.y - vertex2.site.y
        };
        dot = vector.x * vector2.x + vector.y * vector2.y;
        cross = vector.x * vector2.y - vector.y * vector2.x;
        angle = Math.atan2(cross, dot);
      }
      // 将角度标准化到 [0, 2π] 范围
      if (angle < 0) {
        angle += 2 * Math.PI;
      }
      angle2 = angle * 180 / Math.PI;
      /* console.log
             p1: JSON.stringify vertex.site
             p2: JSON.stringify childVertex.site
             angle: angle
             angle2: angle2 */

      // 初始化或比较角度
      if (angle > maxAngle) {
        maxAngle = angle;
        maxAngleChild = child;
      }
      if (angle < minAngle) {
        minAngle = angle;
        return minAngleChild = child;
      }
    })(child);
  }
  return {
    /* console.log "当前元素", JSON.stringify vertex.site
     console.log "顺时针最大角", maxAngleChild, "角度:", maxAngle * 180 / Math.PI
     console.log "顺时针最小角", minAngleChild, "角度:", minAngle * 180 / Math.PI */
    minAngle: minAngle,
    maxAngle: maxAngle,
    minChild: minAngleChild,
    maxChild: maxAngleChild
  };
};
