// Generated by CoffeeScript 2.7.0
export default function(dom) {
  var logPanel, logs;
  // 创建悬浮日志面板
  logPanel = document.createElement("div");
  Object.assign(logPanel.style, {
    position: "fixed",
    top: "10px",
    left: "10px",
    width: "280px",
    height: "400px",
    background: "rgba(0,0,0,0.8)",
    color: "#0f0",
    zIndex: "999999",
    pointerEvents: "none",
    fontSize: "12px",
    padding: "10px",
    overflow: "hidden",
    borderRadius: "8px",
    fontFamily: "monospace",
    lineHeight: "1.2"
  });
  document.body.appendChild(logPanel);
  logs = [];
  window.mobileLog = function(...msg) {
    var str;
    str = msg.join(" ");
    logs.push(str);
    if (logs.length > 25) {
      logs.shift();
    }
    logPanel.innerHTML = logs.join("<br>");
    return console.log(str);
  };
  return window.mobileLog("=== Touch Debugger Init ===");
};
