// Generated by CoffeeScript 2.7.0
import data from "../svgEditor_data.js";

import DebugWindow from "../svgEditor_debugWindow.js";

import PropertyPanel from "../svgEditor_propPanel.js";

import tools from "../../tools.js";

export default function(e, preDiv) {
  var fallbackHeight, itemsCount, left, menuHeight, menuWidth, mouseX, mouseY, rect, ref, ref1, top;
  if (e) {
    e.preventDefault();
  }
  console.log(e);
  data.RightMenu.data.show = true;
  data.RightMenu.data.items = [
    {
      name: "撤销",
      click: function() {
        return data.undo();
      }
    },
    {
      name: "重做",
      click: function() {
        return data.redo();
      }
    },
    {
      name: "添加控制点",
      click: function() {
        var ref,
    ref1;
        return (ref = data.elPaper.getChoisedElements()) != null ? (ref1 = ref[0]) != null ? ref1.addAutoControlPoint() : void 0 : void 0;
      }
    },
    {
      name: "删除控制点",
      click: function() {
        var ctrP,
    el,
    ref;
        el = (ref = data.elPaper.getChoisedElements()) != null ? ref[0] : void 0;
        ctrP = el.getControlPoints()[0];
        if (ctrP) {
          return el != null ? el.removeControlPoint(ctrP) : void 0;
        }
      }
    },
    {
      name: "复制",
      click: function() {
        data.elPaper.copyChoisedElements();
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "粘贴",
      click: function() {
        data.elPaper.pasteChoisedElements();
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "剪切",
      click: function() {
        data.elPaper.cutChoisedElements();
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "删除",
      click: function() {
        data.elPaper.removeChosiedElements();
        data.record("菜单:删除");
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "上移一层",
      click: function() {
        data.elPaper.layerUpChoisedElements();
        return data.record("菜单:上移一层");
      }
    },
    {
      name: "下移一层",
      click: function() {
        data.elPaper.layerDownChoisedElements();
        return data.record("菜单:下移一层");
      }
    },
    {
      name: "编组",
      click: function() {
        data.elPaper.becomeGroup();
        data.record("菜单:编组");
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "全拆散",
      click: function() {
        data.elPaper.exitGroup();
        data.record("菜单:全拆散");
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "拆散一层",
      click: function() {
        data.elPaper.exitPresentGroup();
        data.record("菜单:拆散一层");
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "隐藏/显示",
      click: function() {
        return data.divList.hideOrShow();
      }
    },
    {
      name: "锁定/解锁",
      click: function() {
        return data.divList.lockOrUnlock();
      }
    },
    {
      name: "进入组",
      click: function() {
        var selectedGroups;
        selectedGroups = data.elPaper.getChoisedElements().filter((el) => {
          return el.type === "group";
        });
        if (selectedGroups.length > 0) {
          data.presentGroup = selectedGroups[0];
          data.elPaper.elements.forEach((el) => {
            return el.isChoised = false;
          });
          m.redraw();
        }
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "属性",
      click: function() {
        tools.Notice.launch({
          content: PropertyPanel,
          tip: "元件属性调节"
        });
        return data.RightMenu.data.show = false;
      }
    },
    {
      name: "调试",
      click: function() {
        /*  window.debugElements = data.elPaper.getChoisedElements()
              if window.debugElements.length is 0
                window.debugElements = data.elPaper.getLines()
              console.log "调试获取到的线段:", window.debugElements
              console.log JSON.stringify(window.debugElements.map((e) => e.getPoints())) */

        // 仅打开调试窗口，不改变全局 debug 模式开关
        tools.Notice.launch({
          content: DebugWindow,
          tip: "Elements 调试窗口"
        });
        return data.RightMenu.data.show = false;
      }
    }
  ];
  rect = document.getElementById("svg-paper") ? document.getElementById("svg-paper").getBoundingClientRect() : {
    left: 0,
    top: 0,
    width: window.innerWidth,
    height: window.innerHeight
  };
  mouseX = e.clientX - rect.left;
  mouseY = e.clientY - rect.top;
  itemsCount = data.RightMenu.data.items.length;
  fallbackHeight = 24 + Math.ceil(itemsCount / 2) * 48;
  menuHeight = ((ref = data.RightMenu.dom) != null ? ref.offsetHeight : void 0) || fallbackHeight;
  menuWidth = ((ref1 = data.RightMenu.dom) != null ? ref1.offsetWidth : void 0) || 250;
  top = mouseY + 20;
  left = mouseX + 20;
  if (left + menuWidth > rect.width) {
    left = rect.width - menuWidth - 20;
  }
  if (top + menuHeight > rect.height) {
    top = rect.height - menuHeight - 20;
  }
  if (top < 20) {
    top = 20;
  }
  if (left < 20) {
    left = 20;
  }
  data.rightMenuTop = top;
  data.rightMenuLeft = left;
  /*   if data.cBox.active
   if not data.RightMenu.data.items.find (item)=>item.name is "从选区创建路径"
     data.RightMenu.data.items.push
       name:"从选区创建路径"
       click:-> */
  return m.redraw();
};
