// Generated by CoffeeScript 2.7.0
var initState, mouseM;

import data from "../svgEditor_data.js";

import Element from "../svgEditor_element.js";

import Paper from "../svgEditor_paper.js";

import StateMachine from "../tools/stateMachine.js";

initState = false;

mouseM = null;

export default function({dom}) {
  var defaultM, downS, moveS, upS;
  if (!initState) {
    mouseM = new StateMachine();
    defaultM = mouseM.addState({
      name: "default"
    });
    downS = mouseM.addState({
      name: "down",
      actions: [
        {
          name: "setDownPos",
          do: function() {}
        }
      ]
    });
    moveS = mouseM.addState({
      name: "move",
      actions: [
        {
          name: "setMovePos",
          do: function() {}
        }
      ]
    });
    upS = mouseM.addState({
      name: "up",
      actions: [
        {
          name: "setUpPos",
          do: function() {}
        },
        {
          name: "returnDefault",
          do: function(self) {
            self.chState("default");
            return console.log("恢复初始状态",
        self.presentState);
          }
        }
      ]
    });
    defaultM.addNexts([downS, moveS]);
    moveS.addNexts([upS]);
    downS.addNexts([upS, moveS]);
    upS.addNexts([defaultM]);
    mouseM.chState("default");
    document.onpointerdown = function() {
      mouseM.chState("down");
      return console.log("按下事件", mouseM.presentState.name);
    };
    document.onpointermove = function() {
      mouseM.chState("move");
      return console.log("移动事件", mouseM.presentState.name);
    };
    return document.onpointerup = function() {
      mouseM.chState("up");
      return console.log("抬起事件", mouseM.presentState.name);
    };
  }
};
