// Generated by CoffeeScript 2.7.0
var fnCloseMenuDown, fnContextMenu, fnKeyDownBase, fnKeyDownBuz, fnKeyUpBase, fnLongPressDown;

import data from "../svgEditor_data.js";

import Element from "../svgEditor_element.js";

import Paper from "../svgEditor_paper.js";

import menuDown from "./menuDown.js";

import touchInit from "./touchInit.js";

import tools from "../../tools.js";

fnKeyDownBase = fnKeyUpBase = fnKeyDownBuz = fnContextMenu = fnLongPressDown = fnCloseMenuDown = null;

export default function({dom}) {
  var checkActiveApp, checkPressTimer;
  data.initCursorTool();
  data.initLineTool();
  data.initBucketTool();
  data.initInkBottleTool();
  data.initEllipseTool();
  data.initRectTool();
  data.initTextTool();
  data.initEraserTool();
  data.initDripTool();
  data.cursorTool.addListener(dom);
  data.lineTool.addListener(dom);
  data.bucketTool.addListener(dom);
  data.inkBottleTool.addListener(dom);
  data.ellipseTool.addListener(dom);
  data.rectTool.addListener(dom);
  data.textTool.addListener(dom);
  data.eraserTool.addListener(dom);
  data.dripTool.addListener(dom);
  touchInit(dom);
  checkActiveApp = function() {
    var Notice, activeItem, appId, appIdInWindow, ref, ref1;
    ({Notice, appId} = tools);
    if (Notice) {
      if (!((ref = Notice.data) != null ? ref.activeWindowId : void 0)) {
        return false;
      }
      activeItem = Notice.data.dataArr.find(function(i) {
        var ref1;
        return ((ref1 = i._winConfig) != null ? ref1.id : void 0) === Notice.data.activeWindowId;
      });
      if (activeItem) {
        appIdInWindow = activeItem.sign || ((ref1 = activeItem.contentAttrs) != null ? ref1.appId : void 0);
        if (appIdInWindow && !appIdInWindow.startsWith(appId)) {
          return false;
        }
      }
    }
    return true;
  };
  // ==========================================
  // 1. 专门维护全局按键状态 (pressKeys) 的基础事件组
  // ==========================================
  checkPressTimer = null;
  if (!fnKeyDownBase) {
    document.addEventListener("keydown", fnKeyDownBase = function(e) {
      if (!checkActiveApp()) {
        return;
      }
      checkPressTimer = clearTimeout(checkPressTimer);
      if (data.pressKeys.indexOf(e.key) === -1) {
        data.pressKeys.push(e.key);
      }
      return console.log("【按键】", data.pressKeys);
    });
  }
  if (!fnKeyUpBase) {
    document.addEventListener("keyup", fnKeyUpBase = function(e) {
      var index;
      if (!checkActiveApp()) {
        return;
      }
      index = data.pressKeys.indexOf(e.key);
      if (index !== -1) {
        data.pressKeys.splice(index, 1);
      }
      if (!checkPressTimer) {
        return checkPressTimer = setTimeout(function() {
          var activeKeys;
          activeKeys = [];
          if (e.metaKey && data.pressKeys.indexOf("Meta") !== -1) {
            activeKeys.push("Meta");
          }
          if (e.ctrlKey && data.pressKeys.indexOf("Control") !== -1) {
            activeKeys.push("Control");
          }
          if (e.shiftKey && data.pressKeys.indexOf("Shift") !== -1) {
            activeKeys.push("Shift");
          }
          if (e.altKey && data.pressKeys.indexOf("Alt") !== -1) {
            activeKeys.push("Alt");
          }
          data.pressKeys = activeKeys;
          return console.log("【按键】延迟清理后保留：", data.pressKeys);
        }, 100);
      }
    });
  }
  // ==========================================
  // 2. 专门负责具体快捷键业务逻辑的触发事件
  // ==========================================
  if (!fnKeyDownBuz) {
    window.addEventListener("keydown", fnKeyDownBuz = (e) => {
      var keys, keysStr, ref, ref1;
      if ((ref = (ref1 = e.target.tagName) != null ? ref1.toLowerCase() : void 0) === "textarea" || ref === "input") {
        return;
      }
      if (!checkActiveApp()) {
        return;
      }
      keys = data.pressKeys.map(function(k) {
        return k.toLowerCase();
      }).sort();
      keysStr = JSON.stringify(keys);
      // (1) 撤销重做: Cmd+Z (Mac) / Ctrl+Z (Win)
      if (keysStr === JSON.stringify(["meta", "z"]) || keysStr === JSON.stringify(["control", "z"])) {
        e.preventDefault();
        data.pressKeys = data.pressKeys.filter(function(k) {
          return k.toLowerCase() !== "z";
        });
        data.undo();
        return;
      }
      // (2) 重做: Cmd+Shift+Z (Mac) / Ctrl+Shift+Z (Win)
      if (keysStr === JSON.stringify(["meta", "shift", "z"]) || keysStr === JSON.stringify(["control", "shift", "z"])) {
        e.preventDefault();
        data.pressKeys = data.pressKeys.filter(function(k) {
          return k.toLowerCase() !== "z";
        });
        data.redo();
        return;
      }
      // (3) 删除元素: Backspace / Delete
      if (keysStr === JSON.stringify(["backspace"]) || keysStr === JSON.stringify(["delete"])) {
        data.elPaper.removeChosiedElements();
        data.record("删除元素");
        m.redraw();
        return;
      }
      // (4) 热键切换画笔工具
      return data.tools.forEach((tool, index) => {
        var ref2, tmp;
        tmp = (ref2 = tool.hotKeys) != null ? ref2.every((key, index) => {
          return key.toLowerCase() === keys[index];
        }) : void 0;
        if (tmp) {
          data.presentTool = index;
          m.redraw();
        }
      });
    });
  }
  // ==========================================
  // 3. 专门负责原生右键与长按模拟 (菜单)
  // ==========================================
  if (!fnContextMenu) {
    dom.addEventListener("contextmenu", fnContextMenu = function(e) {
      e.preventDefault();
      return menuDown(e);
    });
  }
  if (!fnLongPressDown) {
    return dom.addEventListener("pointerdown", fnLongPressDown = (e) => {
      var fnLongPressMove, fnLongPressUp, x0, y0;
      x0 = e.clientX;
      y0 = e.clientY;
      clearTimeout(data.rightMenuTimer);
      if (data.RightMenu.data.show === false) {
        data.rightMenuTimer = setTimeout(() => {
          return menuDown(e);
        }, 500);
      }
      fnLongPressMove = fnLongPressUp = null;
      document.addEventListener("pointermove", fnLongPressMove = (e2) => {
        var x2, y2;
        x2 = e2.clientX;
        y2 = e2.clientY;
        if (Math.abs(x2 - x0) >= 5 || Math.abs(y2 - y0) >= 5) {
          return clearTimeout(data.rightMenuTimer);
        }
      });
      return document.addEventListener("pointerup", fnLongPressUp = () => {
        clearTimeout(data.rightMenuTimer);
        if (fnLongPressMove) {
          document.removeEventListener("pointermove", fnLongPressMove);
          fnLongPressMove = null;
        }
        if (fnLongPressUp) {
          document.removeEventListener("pointerup", fnLongPressUp);
          fnLongPressUp = null;
        }
        // 挂载一个全局点击关闭菜单的监听 (仅在菜单显示时需要)
        if (data.RightMenu.data.show) {
          if (!fnCloseMenuDown) {
            return document.addEventListener("pointerdown", fnCloseMenuDown = (e3) => {
              data.RightMenu.data.show = false;
              if (fnCloseMenuDown) {
                document.removeEventListener("pointerdown", fnCloseMenuDown);
                return fnCloseMenuDown = null;
              }
            });
          }
        }
      });
    });
  }
};
