// Generated by CoffeeScript 2.7.0
var fnKeydown, fnMouseDownMid, fnMouseMoveMid, fnMouseUpMid, fnTouchCancel, fnTouchEnd, fnTouchMove, fnTouchStart, fnWheel;

import data from "../svgEditor_data.js";

import tools from "../../tools.js";

fnKeydown = fnWheel = fnTouchStart = fnTouchMove = fnTouchEnd = fnTouchCancel = fnMouseDownMid = fnMouseMoveMid = fnMouseUpMid = null;

export default function(dom) {
  var Notice, appId, lastMiddleX, lastMiddleY, lastPinchCenter, lastPinchDist, limitOffset;
  ({Notice, appId} = tools);
  limitOffset = function() {
    var maxX, maxY, minX, minY, padding, ph, pw, rect;
    rect = dom.getBoundingClientRect();
    pw = data.svgPaper.width * data.globalZoom;
    ph = data.svgPaper.height * data.globalZoom;
    padding = 100;
    minX = padding - pw;
    maxX = rect.width - padding;
    minY = padding - ph;
    maxY = rect.height - padding;
    data.offsetX = Math.max(minX, Math.min(maxX, data.offsetX));
    return data.offsetY = Math.max(minY, Math.min(maxY, data.offsetY));
  };
  // --- 2. 视口缩放与平移 (Wheel) ---
  if (!fnWheel) {
    dom.addEventListener("wheel", fnWheel = (e) => {
      var localX, localY, pointerX, pointerY, rect, scaleFactor;
      e.preventDefault();
      if (e.ctrlKey || e.metaKey) { // 缩放
        scaleFactor = e.deltaY > 0 ? 0.95 : 1.05;
        rect = dom.getBoundingClientRect();
        pointerX = e.clientX - rect.left;
        pointerY = e.clientY - rect.top;
        localX = (pointerX - data.offsetX) / data.globalZoom;
        localY = (pointerY - data.offsetY) / data.globalZoom;
        data.globalZoom *= scaleFactor;
        data.offsetX = pointerX - localX * data.globalZoom;
        data.offsetY = pointerY - localY * data.globalZoom;
        limitOffset();
        return m.redraw();
      }
    });
  }
  // --- 3. 多指触摸与中断支持 (TouchEvent 嵌套模型) ---
  lastPinchDist = 0;
  lastPinchCenter = null;
  if (!fnTouchStart) {
    dom.addEventListener("touchstart", fnTouchStart = (e) => {
      var activeTool, cleanUpTouch, pts, rect, toolInstance, touches;
      touches = Array.from(e.touches);
      data.activePointers = touches.length;
      
      // 多指时中断正在进行的绘图工具
      if (data.activePointers > 1) {
        activeTool = data.getPresentTool();
        if (activeTool) {
          toolInstance = data[activeTool.name + "Tool"];
          if (toolInstance && typeof toolInstance.abort === "function") {
            toolInstance.abort();
          }
        }
      }
      if (data.activePointers === 2) {
        pts = touches;
        lastPinchDist = Math.hypot(pts[0].clientX - pts[1].clientX, pts[0].clientY - pts[1].clientY);
        rect = dom.getBoundingClientRect();
        lastPinchCenter = {
          x: (pts[0].clientX + pts[1].clientX) / 2 - rect.left,
          y: (pts[0].clientY + pts[1].clientY) / 2 - rect.top
        };
      }
      if (!fnTouchMove) {
        document.addEventListener("touchmove", fnTouchMove = (e2) => {
          var currentCenter, currentDist, deltaX, deltaY, localX, localY, scaleFactor, touches2;
          touches2 = Array.from(e2.touches);
          if (touches2.length === 2) {
            e2.preventDefault(); // 拦截浏览器原生双指缩放/滚动
            pts = touches2;
            currentDist = Math.hypot(pts[0].clientX - pts[1].clientX, pts[0].clientY - pts[1].clientY);
            rect = dom.getBoundingClientRect();
            currentCenter = {
              x: (pts[0].clientX + pts[1].clientX) / 2 - rect.left,
              y: (pts[0].clientY + pts[1].clientY) / 2 - rect.top
            };
            if (lastPinchCenter) {
              deltaX = currentCenter.x - lastPinchCenter.x;
              deltaY = currentCenter.y - lastPinchCenter.y;
              data.offsetX += deltaX;
              data.offsetY += deltaY;
              if (lastPinchDist > 0) {
                scaleFactor = currentDist / lastPinchDist;
                localX = (currentCenter.x - data.offsetX) / data.globalZoom;
                localY = (currentCenter.y - data.offsetY) / data.globalZoom;
                data.globalZoom *= scaleFactor;
                data.offsetX = currentCenter.x - localX * data.globalZoom;
                data.offsetY = currentCenter.y - localY * data.globalZoom;
              }
            }
            lastPinchDist = currentDist;
            lastPinchCenter = currentCenter;
            limitOffset();
            return m.redraw();
          }
        }, {
          passive: false
        });
      }
      if (!fnTouchEnd) {
        cleanUpTouch = (e3) => {
          data.activePointers = e3.touches.length;
          if (e3.touches.length === 0) {
            if (fnTouchMove) {
              document.removeEventListener("touchmove", fnTouchMove);
              fnTouchMove = null;
            }
            if (fnTouchEnd) {
              document.removeEventListener("touchend", fnTouchEnd);
            }
            if (fnTouchCancel) {
              document.removeEventListener("touchcancel", fnTouchCancel);
              fnTouchCancel = null;
            }
            return fnTouchEnd = null;
          }
        };
        document.addEventListener("touchend", fnTouchEnd = cleanUpTouch);
        return document.addEventListener("touchcancel", fnTouchCancel = cleanUpTouch);
      }
    });
  }
  // --- 4. 鼠标中键拖拽平移支持 (MouseEvent 嵌套模型) ---
  lastMiddleX = 0;
  lastMiddleY = 0;
  if (!fnMouseDownMid) {
    return dom.addEventListener("mousedown", fnMouseDownMid = (e) => {
      if (e.button === 1) { // 鼠标中键
        e.preventDefault();
        lastMiddleX = e.clientX;
        lastMiddleY = e.clientY;
        if (!fnMouseMoveMid) {
          document.addEventListener("mousemove", fnMouseMoveMid = (e2) => {
            var deltaX, deltaY;
            e2.preventDefault();
            deltaX = e2.clientX - lastMiddleX;
            deltaY = e2.clientY - lastMiddleY;
            data.offsetX += deltaX;
            data.offsetY += deltaY;
            limitOffset();
            lastMiddleX = e2.clientX;
            lastMiddleY = e2.clientY;
            return m.redraw();
          });
        }
        if (!fnMouseUpMid) {
          return document.addEventListener("mouseup", fnMouseUpMid = (e3) => {
            if (e3.button === 1) {
              if (fnMouseMoveMid) {
                document.removeEventListener("mousemove", fnMouseMoveMid);
                fnMouseMoveMid = null;
              }
              if (fnMouseUpMid) {
                document.removeEventListener("mouseup", fnMouseUpMid);
                return fnMouseUpMid = null;
              }
            }
          });
        }
      }
    });
  }
};
