// Generated by CoffeeScript 2.7.0
var closedSite, computeElementSides, mixColors;

import data from "../../svgEditor_data.js";

import findRegions from "../../tools/findRegions/main.js";

import PureFill from "../../svgEditor_pureFill.js";

import FillGroup from "../../svgEditor_fillGroup.js";

// ====== 工具函数 ======
closedSite = function(site1, site2, r = 1) {
  return (site1.x - site2.x) ** 2 + (site1.y - site2.y) ** 2 <= r ** 2;
};

// 混色：将多个颜色混合（RGB 平均）
mixColors = function(colorArray) {
  var b, bSum, c, g, gSum, k, len, n, parseRgb, r, rSum;
  if (!colorArray || colorArray.length === 0) {
    return null;
  }
  if (colorArray.length === 1) {
    return colorArray[0];
  }
  parseRgb = function(colorStr) {
    var elem, m, rgb;
    elem = document.createElement("div");
    elem.style.color = colorStr;
    document.body.appendChild(elem);
    rgb = window.getComputedStyle(elem).color;
    document.body.removeChild(elem);
    m = rgb.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
    if (m) {
      return [parseInt(m[1]), parseInt(m[2]), parseInt(m[3])];
    } else {
      return [0, 0, 0];
    }
  };
  rSum = gSum = bSum = 0;
  for (k = 0, len = colorArray.length; k < len; k++) {
    c = colorArray[k];
    [r, g, b] = parseRgb(c);
    rSum += r;
    gSum += g;
    bSum += b;
  }
  n = colorArray.length;
  return `rgb(${Math.round(rSum / n)}, ${Math.round(gSum / n)}, ${Math.round(bSum / n)})`;
};

// ====== Shoelace 绕向计算 ======
computeElementSides = function(elements) {
  var area, cand, closePt, el, elementSides, found, i, idx, isCCW, isRev, j, k, l, last, lastEndPt, len, len1, n, o, origEl, p, polygon, q, ref, ref1, remaining, reversed, sorted, sortedIdx, t;
  if (!elements || elements.length === 0) {
    return [];
  }
  closePt = function(a, b) {
    return Math.abs(a.x - b.x) < 2 && Math.abs(a.y - b.y) < 2;
  };
  remaining = elements.slice();
  sorted = [];
  reversed = [];
  sorted.push(remaining.shift());
  reversed.push(false);
  while (remaining.length > 0) {
    last = sorted[sorted.length - 1];
    lastEndPt = reversed[reversed.length - 1] ? last.s() : last.e();
    found = false;
    for (i = k = 0, ref = remaining.length; (0 <= ref ? k < ref : k > ref); i = 0 <= ref ? ++k : --k) {
      cand = remaining[i];
      if (closePt(lastEndPt, cand.s())) {
        sorted.push(cand);
        reversed.push(false);
        remaining.splice(i, 1);
        found = true;
        break;
      } else if (closePt(lastEndPt, cand.e())) {
        sorted.push(cand);
        reversed.push(true);
        remaining.splice(i, 1);
        found = true;
        break;
      }
    }
    if (!found) {
      sorted.push(remaining.shift());
      reversed.push(false);
    }
  }
  polygon = [];
  for (idx = l = 0, len = sorted.length; l < len; idx = ++l) {
    el = sorted[idx];
    isRev = reversed[idx];
    for (i = o = 0; o <= 10; i = ++o) {
      t = isRev ? (10 - i) / 10 : i / 10;
      polygon.push(el.getBezierPoint(t));
    }
  }
  area = 0;
  n = polygon.length;
  for (i = p = 0, ref1 = n; (0 <= ref1 ? p < ref1 : p > ref1); i = 0 <= ref1 ? ++p : --p) {
    j = (i + 1) % n;
    area += polygon[i].x * polygon[j].y;
    area -= polygon[j].x * polygon[i].y;
  }
  area /= 2;
  isCCW = area > 0;
  elementSides = [];
  for (q = 0, len1 = elements.length; q < len1; q++) {
    origEl = elements[q];
    sortedIdx = sorted.indexOf(origEl);
    if (sortedIdx === -1) {
      elementSides.push(0);
      continue;
    }
    isRev = reversed[sortedIdx];
    if (isCCW) {
      elementSides.push(isRev ? 1 : 0);
    } else {
      elementSides.push(isRev ? 0 : 1);
    }
  }
  return elementSides;
};

export default {
  // ====== 对齐工具 ======
  alignPoints: function(eles1, eles2, element, element2) {
    var alignNum, alignPoint, ele1, ele2, k, len, results;
    alignNum = 1;
    if (eles1.length > 0 && eles2.length > 0) {
      results = [];
      for (k = 0, len = eles1.length; k < len; k++) {
        ele1 = eles1[k];
        results.push((function() {
          var l, len1, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, results1;
          results1 = [];
          for (l = 0, len1 = eles2.length; l < len1; l++) {
            ele2 = eles2[l];
            if (((0 <= (ref = Math.abs(ele1.s().x - ele2.s().x)) && ref <= alignNum)) && ((0 <= (ref1 = Math.abs(ele1.s().y - ele2.s().y)) && ref1 <= alignNum))) {
              results1.push(ele2.setS({
                x: ele1.s().x,
                y: ele1.s().y
              }));
            } else if (((0 <= (ref2 = Math.abs(ele1.s().x - ele2.e().x)) && ref2 <= alignNum)) && ((0 <= (ref3 = Math.abs(ele1.s().y - ele2.e().y)) && ref3 <= alignNum))) {
              results1.push(ele2.setE({
                x: ele1.s().x,
                y: ele1.s().y
              }));
            } else if (((0 <= (ref4 = Math.abs(ele1.e().x - ele2.s().x)) && ref4 <= alignNum)) && ((0 <= (ref5 = Math.abs(ele1.e().y - ele2.s().y)) && ref5 <= alignNum))) {
              results1.push(ele2.setS({
                x: ele1.e().x,
                y: ele1.e().y
              }));
            } else if (((0 <= (ref6 = Math.abs(ele1.e().x - ele2.e().x)) && ref6 <= alignNum)) && ((0 <= (ref7 = Math.abs(ele1.e().y - ele2.e().y)) && ref7 <= alignNum))) {
              results1.push(ele2.setE({
                x: ele1.e().x,
                y: ele1.e().y
              }));
            } else {
              results1.push(void 0);
            }
          }
          return results1;
        })());
      }
      return results;
    } else if (eles1.length > 0 && eles2.length === 0) {
      alignPoint = eles1[0].e();
      if (closedSite(element2.s(), alignPoint)) {
        element2.setS({
          x: alignPoint.x,
          y: alignPoint.y
        });
      }
      if (closedSite(element2.e(), alignPoint)) {
        return element2.setE({
          x: alignPoint.x,
          y: alignPoint.y
        });
      }
    } else if (eles1.length === 0 && eles2.length > 0) {
      alignPoint = eles2[0].e();
      if (closedSite(element.s(), alignPoint)) {
        element.setS({
          x: alignPoint.x,
          y: alignPoint.y
        });
      }
      if (closedSite(element.e(), alignPoint)) {
        return element.setE({
          x: alignPoint.x,
          y: alignPoint.y
        });
      }
    }
  },
  // ====== 合并重叠线 ======
  combineElements: function(element, element2, elementsArray) {
    var idx;
    if (!element.isIntersectBoundingBox(element2)) {
      return false;
    }
    if (element.isLineInLine(element2)) {
      [...element2.prop.fillGroups].forEach((fg) => {
        return fg.replaceElement(element2, [element]);
      });
      data.elPaper.remove(element2);
      element.isActive = true;
      if (elementsArray) {
        idx = elementsArray.indexOf(element2);
        if (idx !== -1) {
          elementsArray.splice(idx, 1);
        }
      }
      return true;
    }
    if (element2.isLineInLine(element)) {
      [...element.prop.fillGroups].forEach((fg) => {
        return fg.replaceElement(element, [element2]);
      });
      data.elPaper.remove(element);
      if (elementsArray) {
        idx = elementsArray.indexOf(element);
        if (idx !== -1) {
          elementsArray.splice(idx, 1);
        }
      }
      element2.isActive = true;
      return true;
    }
    return false;
  },
  // ====== 两线切割 ======
  subdivideLinePair: function(lineA, lineB, elements) {
    var iPoints, idxA, idxB, idxE, k, l, len, len1, len2, len3, newA, newB, o, p, sl, t1, t2, vT1, vT2;
    if (!lineA.isIntersectBoundingBox(lineB)) {
      return false;
    }
    if (!lineA.isIntersectLine(lineB)) {
      return false;
    }
    iPoints = lineA.getIntersectionPoints(lineB);
    if (iPoints.length === 0) {
      return false;
    }
    t1 = iPoints[0].t1;
    t2 = iPoints[0].t2;
    vT1 = t1 > 0.001 && t1 < 0.999;
    vT2 = t2 > 0.001 && t2 < 0.999;
    if (!vT1 && !vT2) {
      return false;
    }
    [...lineA.prop.fillGroupInners].forEach((fg) => {
      return lineA.exitFillGroupInner(fg);
    });
    [...lineB.prop.fillGroupInners].forEach((fg) => {
      return lineB.exitFillGroupInner(fg);
    });
    if (vT1 && vT2) {
      newA = lineA.subdivideBezier(t1);
      newB = lineB.subdivideBezier(t2);
      this.alignPoints(newA, newB, lineA, lineB);
      for (k = 0, len = newA.length; k < len; k++) {
        sl = newA[k];
        if (lineA._leftColor) {
          sl._leftColor = lineA._leftColor;
        }
        if (lineA._rightColor) {
          sl._rightColor = lineA._rightColor;
        }
      }
      [...lineA.prop.fillGroups].forEach(function(fg) {
        return fg.replaceElement(lineA, newA);
      });
      idxA = data.elPaper.elements.indexOf(lineA);
      if (idxA !== -1) {
        data.elPaper.elements.splice(idxA, 1, ...newA);
      }
      if (elements) {
        idxE = elements.indexOf(lineA);
        if (idxE !== -1) {
          elements.splice(idxE, 1, ...newA);
        }
      }
      for (l = 0, len1 = newB.length; l < len1; l++) {
        sl = newB[l];
        if (lineB._leftColor) {
          sl._leftColor = lineB._leftColor;
        }
        if (lineB._rightColor) {
          sl._rightColor = lineB._rightColor;
        }
      }
      [...lineB.prop.fillGroups].forEach(function(fg) {
        return fg.replaceElement(lineB, newB);
      });
      idxB = data.elPaper.elements.indexOf(lineB);
      if (idxB !== -1) {
        data.elPaper.elements.splice(idxB, 1, ...newB);
      }
      if (elements) {
        idxE = elements.indexOf(lineB);
        if (idxE !== -1) {
          elements.splice(idxE, 1, ...newB);
        }
      }
    } else if (vT1) {
      newA = lineA.subdivideBezier(t1);
      this.alignPoints(newA, [], lineA, lineB);
      for (o = 0, len2 = newA.length; o < len2; o++) {
        sl = newA[o];
        if (lineA._leftColor) {
          sl._leftColor = lineA._leftColor;
        }
        if (lineA._rightColor) {
          sl._rightColor = lineA._rightColor;
        }
      }
      [...lineA.prop.fillGroups].forEach(function(fg) {
        return fg.replaceElement(lineA, newA);
      });
      idxA = data.elPaper.elements.indexOf(lineA);
      if (idxA !== -1) {
        data.elPaper.elements.splice(idxA, 1, ...newA);
      }
      if (elements) {
        idxE = elements.indexOf(lineA);
        if (idxE !== -1) {
          elements.splice(idxE, 1, ...newA);
        }
      }
    } else if (vT2) {
      newB = lineB.subdivideBezier(t2);
      this.alignPoints([], newB, lineA, lineB);
      for (p = 0, len3 = newB.length; p < len3; p++) {
        sl = newB[p];
        if (lineB._leftColor) {
          sl._leftColor = lineB._leftColor;
        }
        if (lineB._rightColor) {
          sl._rightColor = lineB._rightColor;
        }
      }
      [...lineB.prop.fillGroups].forEach(function(fg) {
        return fg.replaceElement(lineB, newB);
      });
      idxB = data.elPaper.elements.indexOf(lineB);
      if (idxB !== -1) {
        data.elPaper.elements.splice(idxB, 1, ...newB);
      }
      if (elements) {
        idxE = elements.indexOf(lineB);
        if (idxE !== -1) {
          elements.splice(idxE, 1, ...newB);
        }
      }
    }
    return true;
  },
  // ====== 包围盒工具 ======
  _getGroupBBox: function(group) {
    var maxX, maxY, minX, minY;
    minX = 2e308;
    minY = 2e308;
    maxX = -2e308;
    maxY = -2e308;
    if (group.prop.elements.length === 0) {
      return {
        minX: 0,
        maxX: 0,
        minY: 0,
        maxY: 0
      };
    }
    group.prop.elements.forEach((el) => {
      var box;
      box = el.getBoundingBox();
      minX = Math.min(minX, box.minX);
      minY = Math.min(minY, box.minY);
      maxX = Math.max(maxX, box.maxX);
      return maxY = Math.max(maxY, box.maxY);
    });
    return {minX, maxX, minY, maxY};
  },
  // =================================================================
  //  主函数：splitPaper
  // =================================================================
  splitPaper: function(elements) {
    var allLines, child, color, colorSet, delIndex, edge, element, element2, fg, fgEdge, fillGroups, finalColor, globalChanged, globalSafe, i1, idx, index, innerSide, j1, k, l, len, len1, len10, len11, len12, len13, len2, len3, len4, len5, len6, len7, len8, len9, line, lineA, lineB, needRebuild, o, orphanPureFills, outerBreak, p, pf, phase3Safety, q, ref, ref1, ref2, ref3, ref4, ref5, ref6, region, regions, s, safeElements, sides, splitCount, u, uniqueColors, v, w, x, y, z;
    elements = elements || data.elPaper.getList();
    index = elements.length - 1;
    splitCount = 0;
    // ==========================================================
    //  STEP 0: 守卫检测（在任何修改之前！）
    // ==========================================================
    fillGroups = data.elPaper.getFillGroups();
    orphanPureFills = data.elPaper.getPureFill().filter(function(pf) {
      return pf.prop.fillGroups.length === 0;
    });
    needRebuild = false;
    ref = data.elPaper.getLines();
    // 唯一触发条件：自由线与 FillGroup 边线存在交叉（说明有碰撞发生）
    for (k = 0, len = ref.length; k < len; k++) {
      line = ref[k];
      if (needRebuild) {
        break;
      }
      if (line.prop.fillGroups.length === 0) {
        for (l = 0, len1 = fillGroups.length; l < len1; l++) {
          fg = fillGroups[l];
          if (needRebuild) {
            break;
          }
          ref1 = fg.prop.elements;
          for (o = 0, len2 = ref1.length; o < len2; o++) {
            fgEdge = ref1[o];
            if (line.isIntersectBoundingBox(fgEdge) && line.isIntersectLine(fgEdge)) {
              needRebuild = true;
              break;
            }
          }
        }
      }
    }
// ==========================================================
//  STEP 1: 颜色同步（始终执行，非破坏性）
// ==========================================================
    for (p = 0, len3 = fillGroups.length; p < len3; p++) {
      fg = fillGroups[p];
      color = fg.prop.fill;
      sides = computeElementSides(fg.prop.elements);
      ref2 = fg.prop.elements;
      for (idx = q = 0, len4 = ref2.length; q < len4; idx = ++q) {
        edge = ref2[idx];
        if (sides[idx] === 0) {
          edge._leftColor = color;
        } else {
          edge._rightColor = color;
        }
      }
    }
    // ==========================================================
    //  不需要重建时：只做普通线条维护，然后返回
    // ==========================================================
    if (!needRebuild) {
      // 普通线条生命周期维护
      while (index >= 0) {
        element = elements[index];
        if (!element) {
          index--;
          continue;
        }
        if (element.type === "pureFill") {
          if (element.prop.fillGroups.length <= 0) {
            data.inkBottleTool.fill(element);
            index = elements.length - 1;
            continue;
          }
        }
        if (element.type === "line") {
          if (element.isActive === false) {
            if (element.prop.fillGroups.length === 0) {
              element.remove();
              index = elements.length - 1;
              continue;
            }
          }
          if (element.s().x === element.e().x && element.s().y === element.e().y) {
            if (element.getPoints().length <= 3) {
              [...element.prop.fillGroups].forEach(function(fg) {
                return element.exitFillGroup(fg);
              });
              [...element.prop.fillGroupInners].forEach(function(fg) {
                return element.exitFillGroupInner(fg);
              });
              element.remove();
              index = elements.length - 1;
              continue;
            }
          }
          if (element.isPointsCollinear()) {
            element.curveTurnLine();
          }
          if (data.splitPaper) {
            for (s = 0, len5 = elements.length; s < len5; s++) {
              element2 = elements[s];
              if (element === element2) {
                continue;
              }
              if (element.prop.fillGroups.length > 0 || element2.prop.fillGroups.length > 0) {
                continue;
              }
              if (element2.type !== "line") {
                continue;
              }
              if (splitCount > 50) {
                splitCount = 0;
                delIndex = data.elPaper.getLines().length - 1;
                while (delIndex >= 0) {
                  line = data.elPaper.getLines()[delIndex];
                  if (line.estimateLength() <= 5) {
                    line.prop.fillGroups.forEach((fg) => {
                      data.elPaper.remove(fg.prop.pureFill);
                      return fg.break();
                    });
                    data.elPaper.remove(line);
                    delIndex = data.elPaper.getLines().length;
                  }
                  delIndex--;
                }
                index = -1;
                break;
              }
              if (this.combineElements(element, element2, elements)) {
                index = elements.length;
                break;
              }
              if (element.estimateLength() < 4 && element2.estimateLength() < 4) {
                continue;
              }
              if (element.isChoised || element2.isChoised) {
                continue;
              }
              if (this.subdivideLinePair(element, element2, elements)) {
                index = elements.length;
                splitCount++;
                break;
              }
            }
          }
        }
        index--;
      }
      return;
    }
    ref3 = [...fillGroups];
    // ==========================================================
    //  ===== 以下是重建路径（needRebuild = true）=====
    // ==========================================================

    // STEP 2: 拆散所有 FillGroup + 移除孤儿 pureFill
    for (u = 0, len6 = ref3.length; u < len6; u++) {
      fg = ref3[u];
      if (fg.prop.pureFill) {
        data.elPaper.remove(fg.prop.pureFill);
      }
      fg.break();
    }
    ref4 = [...orphanPureFills];
    for (v = 0, len7 = ref4.length; v < len7; v++) {
      pf = ref4[v];
      data.elPaper.remove(pf);
    }
    // STEP 3: 线条生命周期（跳过孤儿 pureFill 处理）
    elements = data.elPaper.getList();
    index = elements.length - 1;
    splitCount = 0;
    phase3Safety = 0;
    while (index >= 0) {
      phase3Safety++;
      if (phase3Safety > 5000) {
        console.error("线条处理: 超出5000次迭代上限");
        break;
      }
      element = elements[index];
      if (!element) {
        index--;
        continue;
      }
      // 跳过 pureFill - 在重建路径中不用 inkBottleTool 修复
      // （后续 Step 5 会通过 findRegions 统一重建）
      if (element.type === "line") {
        if (element.isActive === false) {
          if (element.prop.fillGroups.length === 0) {
            element.remove();
            index = elements.length - 1;
            continue;
          }
        }
        if (element.s().x === element.e().x && element.s().y === element.e().y) {
          if (element.getPoints().length <= 3) {
            [...element.prop.fillGroups].forEach(function(fg) {
              return element.exitFillGroup(fg);
            });
            [...element.prop.fillGroupInners].forEach(function(fg) {
              return element.exitFillGroupInner(fg);
            });
            element.remove();
            index = elements.length - 1;
            continue;
          }
        }
        if (element.isPointsCollinear()) {
          element.curveTurnLine();
        }
        if (data.splitPaper) {
          for (w = 0, len8 = elements.length; w < len8; w++) {
            element2 = elements[w];
            if (element === element2) {
              continue;
            }
            if (element.prop.fillGroups.length > 0 || element2.prop.fillGroups.length > 0) {
              continue;
            }
            if (element2.type !== "line") {
              continue;
            }
            if (splitCount > 50) {
              splitCount = 0;
              delIndex = data.elPaper.getLines().length - 1;
              while (delIndex >= 0) {
                line = data.elPaper.getLines()[delIndex];
                if (line.estimateLength() <= 5) {
                  line.prop.fillGroups.forEach((fg) => {
                    data.elPaper.remove(fg.prop.pureFill);
                    return fg.break();
                  });
                  data.elPaper.remove(line);
                  delIndex = data.elPaper.getLines().length;
                }
                delIndex--;
              }
              index = -1;
              break;
            }
            if (this.combineElements(element, element2, elements)) {
              index = elements.length;
              break;
            }
            if (element.estimateLength() < 4 && element2.estimateLength() < 4) {
              continue;
            }
            if (element.isChoised || element2.isChoised) {
              continue;
            }
            if (this.subdivideLinePair(element, element2, elements)) {
              index = elements.length;
              splitCount++;
              break;
            }
          }
        }
      }
      index--;
    }
    // STEP 4: 全局切割（所有线都是自由线了，两两切割）
    globalChanged = true;
    globalSafe = 0;
    while (globalChanged) {
      globalChanged = false;
      globalSafe++;
      if (globalSafe > 200) {
        console.error("全局切割: 超出200次迭代上限");
        break;
      }
      allLines = data.elPaper.getLines();
      outerBreak = false;
      for (x = 0, len9 = allLines.length; x < len9; x++) {
        lineA = allLines[x];
        if (outerBreak) {
          break;
        }
        for (y = 0, len10 = allLines.length; y < len10; y++) {
          lineB = allLines[y];
          if (lineA === lineB) {
            continue;
          }
          if (this.subdivideLinePair(lineA, lineB, null)) {
            globalChanged = true;
            outerBreak = true;
            break;
          }
        }
      }
    }
    // STEP 5: 查找全图区域 + 计算颜色 + 重建填充
    allLines = data.elPaper.getLines();
    if (allLines.length > 0) {
      regions = findRegions(allLines);
      for (z = 0, len11 = regions.length; z < len11; z++) {
        region = regions[z];
        sides = computeElementSides(region.elements);
        colorSet = {};
        ref5 = region.elements;
        for (idx = i1 = 0, len12 = ref5.length; i1 < len12; idx = ++i1) {
          edge = ref5[idx];
          innerSide = sides[idx];
          color = innerSide === 0 ? edge._leftColor : edge._rightColor;
          if (color) {
            colorSet[color] = true;
          }
        }
        uniqueColors = Object.keys(colorSet);
        if (uniqueColors.length === 0) {
          continue;
        }
        finalColor = uniqueColors.length === 1 ? uniqueColors[0] : mixColors(uniqueColors);
        if (finalColor) {
          safeElements = region.elements.slice();
          if (region.children) {
            ref6 = region.children;
            for (j1 = 0, len13 = ref6.length; j1 < len13; j1++) {
              child = ref6[j1];
              safeElements = safeElements.concat(child.elements);
            }
          }
          data.bucketTool.fill(null, finalColor, safeElements, false);
        }
      }
    }
  }
};
