// Generated by CoffeeScript 2.7.0
var autoBridgeGaps;

import Element from "../../svgEditor_element.js";

import data from "../../svgEditor_data.js";

// 自动缝隙闭合检测与补线模块
export default autoBridgeGaps = function(elements, options = {}) {
  var bestPtB, debugShowVirtualLines, disSq, dx, dy, ePt, el, elIdx, endpoints, gapTolerance, hangingEndpoints, hasNeighbor, i, j, k, l, len, len1, len2, len3, len4, m, minDisSq, n, o, otherInfo, pairKey, presentGroup, ptA, ptB, ptInfo, ref, ref1, ref2, sPt, usedPairs, virtualLine, virtualLines;
  if (!elements || elements.length === 0) {
    return elements;
  }
  gapTolerance = (ref = options.gapTolerance) != null ? ref : 0;
  debugShowVirtualLines = (ref1 = options.debugShowVirtualLines) != null ? ref1 : false;
  presentGroup = ((ref2 = elements[0]) != null ? ref2.prop.parentGroup : void 0) || null;
  // 1. 提取所有线条的端点
  endpoints = [];
  for (elIdx = k = 0, len = elements.length; k < len; elIdx = ++k) {
    el = elements[elIdx];
    sPt = el.s();
    ePt = el.e();
    if (sPt) {
      endpoints.push({
        point: sPt,
        element: el,
        isStart: true,
        elIdx
      });
    }
    if (ePt) {
      endpoints.push({
        point: ePt,
        element: el,
        isStart: false,
        elIdx
      });
    }
  }
  // 2. 识别开放/悬挂端点 (Hanging Endpoints)
  // 如果一个端点与其他端点距离非常小 (<= 0.5px)，视作已相连
  hangingEndpoints = [];
  for (i = l = 0, len1 = endpoints.length; l < len1; i = ++l) {
    ptInfo = endpoints[i];
    hasNeighbor = false;
    for (j = m = 0, len2 = endpoints.length; m < len2; j = ++m) {
      otherInfo = endpoints[j];
      if (i !== j) {
        dx = ptInfo.point.x - otherInfo.point.x;
        dy = ptInfo.point.y - otherInfo.point.y;
        if ((dx * dx + dy * dy) <= 0.25) {
          hasNeighbor = true;
          break;
        }
      }
    }
    if (!hasNeighbor) {
      hangingEndpoints.push(ptInfo);
    }
  }
  // 3. 在悬挂端点之间寻找符合容差 gapTolerance 的极小缝隙并生成补线
  virtualLines = [];
  usedPairs = new Set();
  for (i = n = 0, len3 = hangingEndpoints.length; n < len3; i = ++n) {
    ptA = hangingEndpoints[i];
    minDisSq = gapTolerance * gapTolerance;
    bestPtB = null;
    for (j = o = 0, len4 = hangingEndpoints.length; o < len4; j = ++o) {
      ptB = hangingEndpoints[j];
      if (i < j && ptA.elIdx !== ptB.elIdx) {
        pairKey = `${Math.min(i, j)}-${Math.max(i, j)}`;
        if (!usedPairs.has(pairKey)) {
          dx = ptA.point.x - ptB.point.x;
          dy = ptA.point.y - ptB.point.y;
          disSq = dx * dx + dy * dy;
          if (disSq <= minDisSq) {
            minDisSq = disSq;
            bestPtB = {ptB, pairKey};
          }
        }
      }
    }
    if (bestPtB) {
      usedPairs.add(bestPtB.pairKey);
      ptB = bestPtB.ptB;
      // 创建虚拟补线条 (active: false)
      virtualLine = new Element({
        type: "line",
        isActive: false,
        prop: {
          stroke: "#ff0044",
          strokeWidth: 1,
          strokeDasharray: "3,3",
          points: [
            {
              x: ptA.point.x,
              y: ptA.point.y
            },
            {
              x: ptB.point.x,
              y: ptB.point.y
            }
          ],
          parentGroup: presentGroup
        }
      });
      virtualLines.push(virtualLine);
      // 如果开启了调试模式，直接 push 进入物理画布 elements 并绑定所属组
      if (debugShowVirtualLines) {
        data.elPaper.elements.push(virtualLine);
        if (presentGroup) {
          virtualLine.joinGroup(presentGroup);
        }
      }
    }
  }
  // 返回融合了真实线条与虚拟补线条的数组
  return elements.concat(virtualLines);
};
