// Generated by CoffeeScript 2.7.0
// 构建图
var buildGraph;

export default buildGraph = function(elements) {
  var controlPoints, edges, element, elementIndex, end, endIndex, endKey, i, j, len, len1, nodeIndex, positionMap, positions, sampleIndex, sampleLine, sampleLines, sampleRatio, sampledElementsMap, start, startIndex, startKey;
  positions = [];
  edges = [];
  positionMap = new Map();
  nodeIndex = 0;
  sampledElementsMap = new Map(); // 存储采样后的元素映射

  // 收集所有唯一的点
  for (elementIndex = i = 0, len = elements.length; i < len; elementIndex = ++i) {
    element = elements[elementIndex];
    controlPoints = element.getControlPoints();
    
    // 判断是否为非直线贝塞尔曲线
    if (controlPoints.length > 0) {
      // 对贝塞尔曲线进行智能采样
      // 根据曲线复杂度调整采样密度 - 大幅降低采样密度以提升性能
      sampleRatio = controlPoints.length === 1 ? 0.5 : 0.8; // 二次曲线采样密度0.05，三次曲线0.1
      sampleLines = element.getSmartSampleLines(sampleRatio);
      
      // 存储采样信息用于后续还原
      sampledElementsMap.set(elementIndex, {
        originalElement: element,
        sampleLines: sampleLines,
        sampleCount: sampleLines.length
      });

      // 处理采样后的线段
      for (sampleIndex = j = 0, len1 = sampleLines.length; j < len1; sampleIndex = ++j) {
        sampleLine = sampleLines[sampleIndex];
        start = sampleLine.s();
        end = sampleLine.e();
        startKey = `${start.x},${start.y}`;
        endKey = `${end.x},${end.y}`;
        if (!positionMap.has(startKey)) {
          positionMap.set(startKey, nodeIndex++);
          positions.push([start.x, start.y]);
        }
        if (!positionMap.has(endKey)) {
          positionMap.set(endKey, nodeIndex++);
          positions.push([end.x, end.y]);
        }
        startIndex = positionMap.get(startKey);
        endIndex = positionMap.get(endKey);
        
        // 避免自环
        if (startIndex !== endIndex) {
          edges.push([startIndex, endIndex]);
        }
      }
    } else {
      // 直线处理（原有逻辑）
      start = element.s();
      end = element.e();
      startKey = `${start.x},${start.y}`;
      endKey = `${end.x},${end.y}`;
      if (!positionMap.has(startKey)) {
        positionMap.set(startKey, nodeIndex++);
        positions.push([start.x, start.y]);
      }
      if (!positionMap.has(endKey)) {
        positionMap.set(endKey, nodeIndex++);
        positions.push([end.x, end.y]);
      }
      startIndex = positionMap.get(startKey);
      endIndex = positionMap.get(endKey);
      
      // 避免自环
      if (startIndex !== endIndex) {
        edges.push([startIndex, endIndex]);
      }
    }
  }
  return {positions, edges, sampledElementsMap};
};
