// Generated by CoffeeScript 2.7.0
var calculateRegionArea, getRegionSamplePoints, isPointInPoints, isRegionInRegion;

import pointInRegions from "../pointInRegions.js";

calculateRegionArea = function(elements) {
  var allPoints, area, element, i, j, k, l, len, n, ref;
  if (!elements || elements.length === 0) {
    return 0;
  }
  
  // 将贝塞尔曲线转换为多边形点
  allPoints = [];
  for (k = 0, len = elements.length; k < len; k++) {
    element = elements[k];
    if (element.prop.points.length === 2) {
      allPoints.push({...element.s()});
      allPoints.push({...element.e()});
    } else if (element.prop.points.length > 2) {
      element.getSmartSamplePoints(0.3).forEach((point) => {
        return allPoints.push(point);
      });
    }
  }
  if (allPoints.length < 3) {
    return 0;
  }
  
  // 使用Shoelace公式计算面积
  area = 0;
  n = allPoints.length;
  for (i = l = 0, ref = n; (0 <= ref ? l < ref : l > ref); i = 0 <= ref ? ++l : --l) {
    j = (i + 1) % n;
    area += allPoints[i].x * allPoints[j].y;
    area -= allPoints[j].x * allPoints[i].y;
  }
  return Math.abs(area) / 2;
};

isPointInPoints = (point, points) => {
  return points.find((point2) => {
    return point.x === point2.x && point.y === point2.y;
  });
};

getRegionSamplePoints = (region) => {
  var element, k, len, ref, samplePoints;
  samplePoints = [];
  ref = region.elements;
  for (k = 0, len = ref.length; k < len; k++) {
    element = ref[k];
    if (element.prop.points.length === 2) {
      if (!isPointInPoints(element.s(), samplePoints)) {
        samplePoints.push({...element.s()});
      }
      if (!isPointInPoints(element.e(), samplePoints)) {
        samplePoints.push({...element.e()});
      }
    } else if (element.prop.points.length > 2) {
      element.getSmartSamplePoints(0.3).forEach((point) => {
        if (!isPointInPoints(point, samplePoints)) {
          return samplePoints.push(point);
        }
      });
    } else {
      throw new Error("线段points控制点个数异常，无法区分曲线类型");
    }
  }
  return samplePoints;
};

isRegionInRegion = (region1, region2) => {
  var output, samplePoints1;
  samplePoints1 = getRegionSamplePoints(region1);
  output = null;
  if (samplePoints1.length > 0) {
    output = samplePoints1.every((samplePoint) => {
      var tmp;
      tmp = pointInRegions(samplePoint, [region2]);
      return tmp.length > 0;
    });
  } else {
    output = false;
  }
  return output;
};

export default function(regionElements) {
  var index, index2, k, ref, region, region2, regions;
  regions = regionElements.map((elements) => {
    return {
      elements: elements,
      area: calculateRegionArea(elements),
      children: [],
      parent: null
    };
  }).sort((a, b) => {
    return b.area - a.area;
  });
  index = regions.length - 1;
  while (index >= 0) {
    region = regions[index];
    for (index2 = k = ref = regions.length - 1; (ref <= 0 ? k <= 0 : k >= 0); index2 = ref <= 0 ? ++k : --k) {
      region2 = regions[index2];
      if (region2 === region) {
        continue;
      }
      if (region.area <= region2.area) {
        if (isRegionInRegion(region, region2)) {
          if (region2.children.indexOf(region) === -1) {
            region2.children.push(region);
          }
          region.parent = region2;
          regions.splice(index, 1);
          index = regions.length;
          console.log("子 start");
          region2.children.forEach((c) => {
            return console.log(c);
          });
          console.log("子 end");
          break;
        }
      }
    }
    index--;
    console.log("搜索区域xxx", regions[0].children[0], regions[0].children[1]);
  }
  return regions;
};
