// Generated by CoffeeScript 2.7.0
// 计算区域面积（使用Shoelace公式）
// elements是svgElement类的实例
var buildNestedRegions, calculateRegionArea, getBezierPoint, isRegionInside, pointInPolygon, regionsShareEdge;

calculateRegionArea = function(elements) {
  var allPoints, area, element, i, j, k, l, len, m, n, point, ref, t;
  if (!elements || elements.length === 0) {
    return 0;
  }
  
  // 将贝塞尔曲线转换为多边形点
  allPoints = [];
  for (k = 0, len = elements.length; k < len; k++) {
    element = elements[k];
// 每条曲线采样20个点
// 获取贝塞尔曲线上的采样点
    for (i = l = 0; l <= 20; i = ++l) {
      t = i / 20;
      point = getBezierPoint(element, t);
      allPoints.push(point);
    }
  }
  if (allPoints.length < 3) {
    return 0;
  }
  
  // 使用Shoelace公式计算面积
  area = 0;
  n = allPoints.length;
  for (i = m = 0, ref = n; (0 <= ref ? m < ref : m > ref); i = 0 <= ref ? ++m : --m) {
    j = (i + 1) % n;
    area += allPoints[i].x * allPoints[j].y;
    area -= allPoints[j].x * allPoints[i].y;
  }
  return Math.abs(area) / 2;
};

// 获取贝塞尔曲线上的点
getBezierPoint = function(element, t) {
  var controlPoints, end, endPoint, p0, p1, p2, p3, points, start, startPoint, t1;
  startPoint = element.s();
  endPoint = element.e();
  controlPoints = element.getControlPoints();
  points = [startPoint].concat(controlPoints).concat([endPoint]);
  switch (points.length) {
    case 2:
      // 直线
      start = points[0];
      end = points[1];
      return {
        x: start.x + t * (end.x - start.x),
        y: start.y + t * (end.y - start.y)
      };
    case 3:
      // 二次贝塞尔曲线
      p0 = points[0];
      p1 = points[1];
      p2 = points[2];
      t1 = 1 - t;
      return {
        x: t1 * t1 * p0.x + 2 * t1 * t * p1.x + t * t * p2.x,
        y: t1 * t1 * p0.y + 2 * t1 * t * p1.y + t * t * p2.y
      };
    case 4:
      // 三次贝塞尔曲线
      p0 = points[0];
      p1 = points[1];
      p2 = points[2];
      p3 = points[3];
      t1 = 1 - t;
      return {
        x: t1 * t1 * t1 * p0.x + 3 * t1 * t1 * t * p1.x + 3 * t1 * t * t * p2.x + t * t * t * p3.x,
        y: t1 * t1 * t1 * p0.y + 3 * t1 * t1 * t * p1.y + 3 * t1 * t * t * p2.y + t * t * t * p3.y
      };
    default:
      // 默认处理为直线
      start = points[0];
      end = points[points.length - 1];
      return {
        x: start.x + t * (end.x - start.x),
        y: start.y + t * (end.y - start.y)
      };
  }
};

// 改进的区域包含检测 - 提高准确性
isRegionInside = function(innerRegion, outerRegion) {
  var element, existingPoint, i, innerArea, innerSamplePoints, insideCount, isDuplicate, k, l, len, len1, len2, len3, len4, m, o, outerArea, outerPolygon, outerSamplesPerEdge, p, point, q, r, ref, ref1, samplesPerEdge, successRate, t, testPoint, tolerance, uniquePoints;
  if (!innerRegion || !outerRegion || innerRegion.length === 0 || outerRegion.length === 0) {
    return false;
  }
  
  // 计算两个区域的面积
  innerArea = calculateRegionArea(innerRegion);
  outerArea = calculateRegionArea(outerRegion);
  
  // 充要条件第一部分：内部区域面积必须小于外部区域面积
  if (innerArea >= outerArea) {
    return false;
  }
  
  // 使用适中的采样密度，平衡性能和准确性
  samplesPerEdge = Math.min(15, Math.max(5, Math.floor(innerRegion.length * 3)));
  
  // 对内部区域进行全面采样
  innerSamplePoints = [];
  for (k = 0, len = innerRegion.length; k < len; k++) {
    element = innerRegion[k];
    for (i = l = 0, ref = samplesPerEdge; (0 <= ref ? l <= ref : l >= ref); i = 0 <= ref ? ++l : --l) {
      t = i / samplesPerEdge;
      point = getBezierPoint(element, t);
      innerSamplePoints.push(point);
    }
  }
  
  // 去除重复点
  uniquePoints = [];
  tolerance = 0.5; // 适中的容差
  for (m = 0, len1 = innerSamplePoints.length; m < len1; m++) {
    point = innerSamplePoints[m];
    isDuplicate = false;
    for (o = 0, len2 = uniquePoints.length; o < len2; o++) {
      existingPoint = uniquePoints[o];
      if (Math.abs(point.x - existingPoint.x) < tolerance && Math.abs(point.y - existingPoint.y) < tolerance) {
        isDuplicate = true;
        break;
      }
    }
    if (!isDuplicate) {
      uniquePoints.push(point);
    }
  }
  if (uniquePoints.length < 3) {
    
    // 如果测试点太少，可能是退化情况
    return false;
  }
  
  // 将外部区域转换为多边形
  outerPolygon = [];
  outerSamplesPerEdge = Math.min(20, Math.max(8, Math.floor(outerRegion.length * 4)));
  for (p = 0, len3 = outerRegion.length; p < len3; p++) {
    element = outerRegion[p];
    for (i = q = 0, ref1 = outerSamplesPerEdge; (0 <= ref1 ? q <= ref1 : q >= ref1); i = 0 <= ref1 ? ++q : --q) {
      t = i / outerSamplesPerEdge;
      point = getBezierPoint(element, t);
      outerPolygon.push(point);
    }
  }
  
  // 检查所有内部区域的采样点是否都在外部区域内
  insideCount = 0;
  for (r = 0, len4 = uniquePoints.length; r < len4; r++) {
    testPoint = uniquePoints[r];
    if (pointInPolygon(testPoint, outerPolygon)) {
      insideCount++;
    }
  }
  
  // 要求至少95%的点在内部（允许少量边界误差）
  successRate = insideCount / uniquePoints.length;
  return successRate >= 0.95;
};

// 射线投射算法
pointInPolygon = function(point, polygon) {
  var i, inside, j, k, ref, x, xi, xj, y, yi, yj;
  if (polygon.length < 3) {
    return false;
  }
  x = point.x;
  y = point.y;
  inside = false;
  j = polygon.length - 1;
  for (i = k = 0, ref = polygon.length; (0 <= ref ? k < ref : k > ref); i = 0 <= ref ? ++k : --k) {
    xi = polygon[i].x;
    yi = polygon[i].y;
    xj = polygon[j].x;
    yj = polygon[j].y;
    if (((yi > y) !== (yj > y)) && (x < (xj - xi) * (y - yi) / (yj - yi) + xi)) {
      inside = !inside;
    }
    j = i;
  }
  return inside;
};

// 精确的边共享检测 - 区分共享点和共享边
regionsShareEdge = function(region1, region2) {
  var distance, element1, element2, i, k, l, len, len1, len2, len3, len4, len5, m, o, overlapCount, p, point, point1, point2, q, r, ref, ref1, s, samples1, samples2, samplesPerEdge, t, tolerance;
  if (!region1 || !region2) {
    return false;
  }

  // 检查是否有相同的元素（共享整条边）
  for (k = 0, len = region1.length; k < len; k++) {
    element1 = region1[k];
    for (l = 0, len1 = region2.length; l < len1; l++) {
      element2 = region2[l];
      if (element1 === element2) {
        return true;
      }
    }
  }
  
  // 检查是否有实际的边重叠（不仅仅是端点相同）
  samplesPerEdge = 5; // 减少采样但保持准确性
  tolerance = 1.0;
  for (m = 0, len2 = region1.length; m < len2; m++) {
    element1 = region1[m];
    // 对第一个区域的边进行采样（排除端点，只检查中间部分）
    samples1 = [];
// 跳过端点 i=0 和 i=samplesPerEdge
    for (i = o = 1, ref = samplesPerEdge; (1 <= ref ? o < ref : o > ref); i = 1 <= ref ? ++o : --o) {
      t = i / samplesPerEdge;
      point = getBezierPoint(element1, t);
      samples1.push(point);
    }
    for (p = 0, len3 = region2.length; p < len3; p++) {
      element2 = region2[p];
      // 对第二个区域的边进行采样（排除端点）
      samples2 = [];
// 跳过端点
      for (i = q = 1, ref1 = samplesPerEdge; (1 <= ref1 ? q < ref1 : q > ref1); i = 1 <= ref1 ? ++q : --q) {
        t = i / samplesPerEdge;
        point = getBezierPoint(element2, t);
        samples2.push(point);
      }
      
      // 检查中间部分是否有重叠
      overlapCount = 0;
      for (r = 0, len4 = samples1.length; r < len4; r++) {
        point1 = samples1[r];
        for (s = 0, len5 = samples2.length; s < len5; s++) {
          point2 = samples2[s];
          distance = Math.sqrt((point1.x - point2.x) * (point1.x - point2.x) + (point1.y - point2.y) * (point1.y - point2.y));
          if (distance <= tolerance) {
            overlapCount++;
            break;
          }
        }
      }
      
      // 如果中间部分有重叠，说明是共享边而不仅仅是共享点
      if (overlapCount > 0) {
        return true;
      }
    }
  }
  return false;
};

// 构建嵌套区域结构 - 修复版本
buildNestedRegions = function(regionElements) {
  var areaRatio, directParent, elements, i, innerRegion, j, k, l, len, m, outerRegion, ref, ref1, region, regions, smallestParentArea, topLevelRegions;
  // 首先创建基础区域对象
  regions = [];
  for (k = 0, len = regionElements.length; k < len; k++) {
    elements = regionElements[k];
    if (elements.length === 0) {
      continue;
    }
    region = {
      elements: elements,
      area: calculateRegionArea(elements),
      children: [],
      parent: null
    };
    regions.push(region);
  }
  
  // 性能警告但不跳过检测
  if (regions.length > 20) {
    console.warn(`区域数量较多(${regions.length})，可能影响性能`);
  }
  
  // 按面积排序（大的在前）
  regions.sort(function(a, b) {
    return b.area - a.area;
  });

  // 建立正确的父子关系 - 每个区域只与其直接的父区域建立关系
  for (i = l = 0, ref = regions.length; (0 <= ref ? l < ref : l > ref); i = 0 <= ref ? ++l : --l) {
    innerRegion = regions[i];
    if (innerRegion.parent) {
      
      // 跳过已经有父区域的区域
      continue;
    }
    
    // 寻找最小的包含当前区域的区域作为其直接父区域
    directParent = null;
    smallestParentArea = 2e308;
    for (j = m = 0, ref1 = regions.length; (0 <= ref1 ? m < ref1 : m > ref1); j = 0 <= ref1 ? ++m : --m) {
      if (i === j) { // 跳过自己
        continue;
      }
      outerRegion = regions[j];
      if (outerRegion.area <= innerRegion.area) {
        
        // 只考虑面积更大的区域作为潜在父区域
        continue;
      }
      
      // 面积差异检查 - 但放宽条件，允许更小的差异
      areaRatio = outerRegion.area / innerRegion.area;
      if (areaRatio < 1.05) { // 面积差异小于5%才跳过
        continue;
      }
      
      // 检查是否共享边（如果共享边，则不是嵌套关系）
      // 注意：现在regionsShareEdge能正确区分共享点和共享边
      if (regionsShareEdge(outerRegion.elements, innerRegion.elements)) {
        continue;
      }
      
      // 检查内部区域是否在外部区域内
      if (isRegionInside(innerRegion.elements, outerRegion.elements)) {
        // 找到面积最小的包含区域作为直接父区域
        if (outerRegion.area < smallestParentArea) {
          directParent = outerRegion;
          smallestParentArea = outerRegion.area;
        }
      }
    }
    
    // 建立父子关系
    if (directParent) {
      innerRegion.parent = directParent;
      directParent.children.push(innerRegion);
    }
  }
  
  // 返回顶级区域（没有父区域的区域）
  topLevelRegions = regions.filter(function(region) {
    return !region.parent;
  });
  return topLevelRegions;
};

export default function(regionElements) {
  return buildNestedRegions(regionElements);
};
