// Generated by CoffeeScript 2.7.0
// 环树类
var CycleTree;

export default CycleTree = class CycleTree {
  constructor(cycle = [], children = []) {
    this.cycle = cycle;
    this.children = children;
  }

  isEmpty() {
    return this.cycle.length === 0 && this.children.length === 0;
  }

};
