// Generated by CoffeeScript 2.7.0
// 深度优先搜索
var depthFirstSearch;

export default depthFirstSearch = function(vInitial, component) {
  var adjacent, adjacents, found, i, len, results, vStack, vertex;
  vStack = [vInitial];
  results = [];
  while (vStack.length > 0) {
    vertex = vStack[vStack.length - 1];
    vertex.visited = 1;
    adjacents = vertex.adjacent;
    found = false;
    for (i = 0, len = adjacents.length; i < len; i++) {
      adjacent = adjacents[i];
      if (adjacent.visited === 0) {
        vStack.push(adjacent);
        found = true;
        break;
      }
    }
    if (!found) {
      vertex.visited = 2;
      component.push(vertex);
      results.push(vStack.pop());
    } else {
      results.push(void 0);
    }
  }
  return results;
};
