// Generated by CoffeeScript 2.7.0
var discoverFaces;

import depthFirstSearch from "./depthFirstSearch.js";

import extractBasis from "./extractBasis.js";

import Vertex from "./vertex.js";

// 发现所有面
export default discoverFaces = function(positions, edges) {
  var allCycles, collectCycles, component, components, end, i, j, k, l, len, len1, len2, len3, m, n, ref, start, tree, v0, v1, vertex, vertices;
  // 创建顶点对象
  vertices = [];
  for (i = j = 0, ref = positions.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
    vertex = new Vertex(i, positions[i]);
    vertices.push(vertex);
  }

  // 构建邻接关系
  for (k = 0, len = edges.length; k < len; k++) {
    [start, end] = edges[k];
    v0 = vertices[start];
    v1 = vertices[end];
    v0.adjacent.push(v1);
    v1.adjacent.push(v0);
  }
  
  // 找到连通分量
  components = [];
  for (l = 0, len1 = vertices.length; l < len1; l++) {
    vertex = vertices[l];
    if (vertex.visited === 0) {
      component = [];
      depthFirstSearch(vertex, component);
      components.push(component);
    }
  }

  // 重置访问状态
  for (m = 0, len2 = vertices.length; m < len2; m++) {
    vertex = vertices[m];
    vertex.visited = 0;
  }
  
  // 从每个连通分量提取面
  allCycles = [];
  for (n = 0, len3 = components.length; n < len3; n++) {
    component = components[n];
    tree = extractBasis(component);
    collectCycles = function(tree) {
      var child, len4, o, ref1, results;
      // 修改：允许2条边构成的区域（如两条曲线形成的封闭区域）
      if (tree.cycle.length >= 2) {
        allCycles.push(tree.cycle);
      }
      ref1 = tree.children;
      results = [];
      for (o = 0, len4 = ref1.length; o < len4; o++) {
        child = ref1[o];
        results.push(collectCycles(child));
      }
      return results;
    };
    collectCycles(tree);
  }
  return allCycles;
};
