// Generated by CoffeeScript 2.7.0
var extractBasis;

import removeFilaments from "./removeFilaments.js";

import extractCycleFromComponent from "./extractCycleFromComponent.js";

import CycleTree from "./cycleTree.js";

// 提取基础（主函数）
export default extractBasis = function(component) {
  var child, childTree, tree;
  tree = new CycleTree();
  while (component.length > 0) {
    component = removeFilaments(component);
    if (component.length > 0) {
      childTree = extractCycleFromComponent(component); //从连通分量提取环
      tree.children.push(childTree);
    }
  }
  
  // 如果只有一个子树且没有环，则提升子树
  if (tree.cycle.length === 0 && tree.children.length === 1) {
    child = tree.children[tree.children.length - 1];
    tree.cycle = child.cycle;
    tree.children = child.children;
  }
  return tree;
};
