// Generated by CoffeeScript 2.7.0
// 提取环（严格按照参考算法）
var extractCycle;

export default extractCycle = function(closedWalk) {
  var adj, adjIndex, cycle, i, j, numVertices, ref, v0, v0Index, v1, v1Index, vBranch;
  numVertices = closedWalk.length;
  cycle = [];
  for (i = j = 0, ref = numVertices; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
    cycle[i] = closedWalk[i].name;
  }
  v0 = closedWalk[0];
  v1 = closedWalk[1];
  vBranch = v0.adjacent.length > 2 ? v0 : null;
  
  // 从邻接列表中移除边
  v0Index = v0.adjacent.indexOf(v1);
  if (v0Index >= 0) {
    v0.adjacent.splice(v0Index, 1);
  }
  v1Index = v1.adjacent.indexOf(v0);
  if (v1Index >= 0) {
    v1.adjacent.splice(v1Index, 1);
  }
  while (v1 !== vBranch && v1.adjacent.length === 1) {
    adj = v1.adjacent[0];
    // 移除边
    v1Index = v1.adjacent.indexOf(adj);
    if (v1Index >= 0) {
      v1.adjacent.splice(v1Index, 1);
    }
    adjIndex = adj.adjacent.indexOf(v1);
    if (adjIndex >= 0) {
      adj.adjacent.splice(adjIndex, 1);
    }
    v1 = adj;
  }
  if (v1 !== v0) {
    vBranch = v1;
    while (v0 !== vBranch && v0.adjacent.length === 1) {
      v1 = v0.adjacent[0];
      // 移除边
      v0Index = v0.adjacent.indexOf(v1);
      if (v0Index >= 0) {
        v0.adjacent.splice(v0Index, 1);
      }
      v1Index = v1.adjacent.indexOf(v0);
      if (v1Index >= 0) {
        v1.adjacent.splice(v1Index, 1);
      }
      v0 = v1;
    }
  }
  return cycle;
};
