// Generated by CoffeeScript 2.7.0
var extractCycleFromClosedWalk;

import extractCycle from "./extractCycle.js";

import CycleTree from "./cycleTree.js";

// 从闭合路径提取环（处理复杂的嵌套情况）
export default extractCycleFromClosedWalk = function(closedWalk) {
  var deleteCount, detachments, diter, duplicates, endDeletionAt, i, iMax, iMin, j, k, l, numClosedWalk, ref, ref1, ref2, startDeletionAt, tree, vertex;
  tree = new CycleTree();
  duplicates = new Map();
  detachments = new Set();
  numClosedWalk = closedWalk.length;

  // 检测重复顶点
  for (i = k = 1, ref = numClosedWalk - 1; (1 <= ref ? k < ref : k > ref); i = 1 <= ref ? ++k : --k) {
    diter = duplicates.get(closedWalk[i]);
    if (diter != null) {
      iMin = diter;
      iMax = i;
      detachments.add(iMin);
      for (j = l = ref1 = iMin + 1, ref2 = iMax; (ref1 <= ref2 ? l < ref2 : l > ref2); j = ref1 <= ref2 ? ++l : --l) {
        vertex = closedWalk[j];
        duplicates.delete(vertex);
        detachments.delete(j);
      }
      startDeletionAt = iMin + 1;
      endDeletionAt = iMax + 1;
      deleteCount = endDeletionAt - startDeletionAt;
      closedWalk.splice(startDeletionAt, deleteCount);
      numClosedWalk = closedWalk.length;
      i = iMin;
    } else {
      duplicates.set(closedWalk[i], i);
    }
  }
  
  // 修改：正确处理两条边的情况
  // 对于两条边的情况，numClosedWalk 应该是 3（起点 + 中间点 + 终点）
  if (numClosedWalk >= 3) {
    if (numClosedWalk > 3) {
      detachments.add(0);
    }
    // 这里应该处理复杂的分离逻辑，但为了简化，我们直接提取主环
    tree.cycle = extractCycle(closedWalk);
  }
  return tree;
};
