// Generated by CoffeeScript 2.7.0
var findFaces;

import {
  PlanarFaceTree,
  DiscoveryResultType
} from "./planar-face-tree.js";

// 使用PlanarFaceTree算法发现面
export default findFaces = function(positions, edges) {
  var collectCycles, error, faces, i, len, planarFaceTree, ref, result, tree;
  try {
    // 使用PlanarFaceTree发现面
    planarFaceTree = new PlanarFaceTree();
    result = planarFaceTree.discover(positions, edges);
    if (result.type === DiscoveryResultType.ERROR) {
      console.error('PlanarFaceTree error:', result.reason);
      return [];
    }
    
    // 从森林中收集所有循环
    faces = [];
    collectCycles = function(tree) {
      var child, i, len, ref, results;
      if (tree.cycle.length > 0) {
        faces.push(tree.cycle);
      }
      ref = tree.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        child = ref[i];
        results.push(collectCycles(child));
      }
      return results;
    };
    ref = result.forest;
    for (i = 0, len = ref.length; i < len; i++) {
      tree = ref[i];
      collectCycles(tree);
    }
    return faces;
  } catch (error1) {
    error = error1;
    console.error('findFaces error:', error);
    return [];
  }
};
