// Generated by CoffeeScript 2.7.0
// 获取顺时针最远的邻居
var getClockwiseMost;

export default getClockwiseMost = function(vPrev, vCurr) {
  var dAdj, dCurr, dNext, i, len, ref, vAdj, vCurrConvex, vNext;
  vNext = null;
  vCurrConvex = false;
  dCurr = [0, 0];
  dNext = [0, 0];
  if (vPrev) {
    dCurr[0] = vCurr.position[0] - vPrev.position[0];
    dCurr[1] = vCurr.position[1] - vPrev.position[1];
  } else {
    dCurr[0] = 0;
    dCurr[1] = -1;
  }
  ref = vCurr.adjacent;
  for (i = 0, len = ref.length; i < len; i++) {
    vAdj = ref[i];
    if (vAdj === vPrev) {
      continue;
    }
    dAdj = [vAdj.position[0] - vCurr.position[0], vAdj.position[1] - vCurr.position[1]];
    if (!vNext) {
      vNext = vAdj;
      dNext = dAdj;
      vCurrConvex = dNext[0] * dCurr[1] <= dNext[1] * dCurr[0];
      continue;
    }
    if (vCurrConvex) {
      if ((dCurr[0] * dAdj[1] < dCurr[1] * dAdj[0]) || (dNext[0] * dAdj[1] < dNext[1] * dAdj[0])) {
        vNext = vAdj;
        dNext = dAdj;
        vCurrConvex = dNext[0] * dCurr[1] <= dNext[1] * dCurr[0];
      }
    } else {
      if ((dCurr[0] * dAdj[1] < dCurr[1] * dAdj[0]) && (dNext[0] * dAdj[1] < dNext[1] * dAdj[0])) {
        vNext = vAdj;
        dNext = dAdj;
        vCurrConvex = dNext[0] * dCurr[1] < dNext[1] * dCurr[0];
      }
    }
  }
  return vNext;
};
