// Generated by CoffeeScript 2.7.0
var findRegions;

import buildGraph from "./buildGraph.js";

import findFaces from "./findFaces.js";

import buildNestedRegions from "./buildNestedRegions.js";

import discoverFaces from "./discoverFaces.js";

import restoreBezierCurveFromIndex from "./restoreBezierCurveFromIndex.js";

import autoBridgeGaps from "./autoBridgeGaps.js";

export default findRegions = function(elements, options = {}) {
  var edges, error, faces, output, positions, regions, sampledElementsMap;
  try {
    // 严格按照planar-face-tree算法实现

    // 主函数逻辑
    if (!elements || elements.length === 0) {
      return [];
    }
    
    // 缝隙自动补线预处理
    elements = autoBridgeGaps(elements, options);
    
      // 构建图
    ({positions, edges, sampledElementsMap} = buildGraph(elements));
    if (positions.length === 0 || edges.length === 0) {
      return [];
    }
    
    // 发现面
    faces = findFaces(positions, edges);
    //faces = discoverFaces(positions, edges)
    regions = restoreBezierCurveFromIndex(faces, positions, elements, sampledElementsMap);
    // 转换为元素数组并返回（不进行排序）
    output = buildNestedRegions(regions);
    return output;
  } catch (error1) {
    error = error1;
    console.error('findRegions error:', error);
    return [];
  }
};
