// Generated by CoffeeScript 2.7.0
// 移除悬挂边（filaments）
var removeFilaments;

export default removeFilaments = function(component) {
  var adjacent, adjacentIndex, endpoints, i, j, len, len1, v, vertex;
  endpoints = [];
  for (i = 0, len = component.length; i < len; i++) {
    vertex = component[i];
    if (vertex.adjacent.length === 1) {
      endpoints.push(vertex);
    }
  }
  if (endpoints.length > 0) {
    for (j = 0, len1 = endpoints.length; j < len1; j++) {
      v = endpoints[j];
      if (v.adjacent.length === 1) {
        vertex = v;
        while (vertex.adjacent.length === 1) {
          adjacent = vertex.adjacent[0];
          // 从邻居的邻接列表中移除当前顶点
          adjacentIndex = adjacent.adjacent.indexOf(vertex);
          if (adjacentIndex >= 0) {
            adjacent.adjacent.splice(adjacentIndex, 1);
          }
          // 清空当前顶点的邻接列表
          vertex.adjacent = [];
          vertex = adjacent;
        }
      }
    }
    
    // 过滤掉没有邻居的顶点
    return component.filter(function(vertex) {
      return vertex.adjacent.length > 0;
    });
  } else {
    return component;
  }
};
