// Generated by CoffeeScript 2.7.0
export default function(faces, positions, elements, sampledElementsMap = new Map()) {
  var element, elementEnd, elementIndex, elementStart, endPos, face, faceElements, forwardKey, foundElement, foundInSampled, i, j, k, l, len, len1, m, n, pointsEqual, ref, ref1, ref2, regionElements, reverseKey, sampleEnd, sampleIndex, sampleLine, sampleStart, sampledInfo, sampledSegmentIndex, searchKey, segmentInfo, segmentKey, startPos, usedElementsInThisFace, usedSampledSegments, x;
  // 判断两个点是否相等
  pointsEqual = function(p1, p2) {
    return Math.abs(p1[0] - p2[0]) < 1e-10 && Math.abs(p1[1] - p2[1]) < 1e-10;
  };
  regionElements = [];
  
  // 预建立采样线段索引以提升性能
  sampledSegmentIndex = new Map(); // key: "x1,y1,x2,y2", value: {elementIndex, sampleIndex, originalElement}
  for (x of sampledElementsMap) {
    [elementIndex, sampledInfo] = x;
    ref = sampledInfo.sampleLines;
    for (sampleIndex = k = 0, len = ref.length; k < len; sampleIndex = ++k) {
      sampleLine = ref[sampleIndex];
      sampleStart = sampleLine.s();
      sampleEnd = sampleLine.e();
      // 创建正向和反向索引键
      forwardKey = `${sampleStart.x.toFixed(6)},${sampleStart.y.toFixed(6)},${sampleEnd.x.toFixed(6)},${sampleEnd.y.toFixed(6)}`;
      reverseKey = `${sampleEnd.x.toFixed(6)},${sampleEnd.y.toFixed(6)},${sampleStart.x.toFixed(6)},${sampleStart.y.toFixed(6)}`;
      segmentInfo = {
        elementIndex,
        sampleIndex,
        originalElement: sampledInfo.originalElement
      };
      sampledSegmentIndex.set(forwardKey, segmentInfo);
      sampledSegmentIndex.set(reverseKey, segmentInfo);
    }
  }
  for (l = 0, len1 = faces.length; l < len1; l++) {
    face = faces[l];
    faceElements = [];
    usedElementsInThisFace = new Set(); // 跟踪在当前面中已使用的元素
    usedSampledSegments = new Set(); // 跟踪已使用的采样线段
    for (i = m = 0, ref1 = face.length - 1; (0 <= ref1 ? m < ref1 : m > ref1); i = 0 <= ref1 ? ++m : --m) {
      startPos = positions[face[i]];
      endPos = positions[face[i + 1]];
      
      // 找到匹配的元素
      foundElement = null;
      
      // 使用索引快速查找采样线段
      foundInSampled = false;
      searchKey = `${startPos[0].toFixed(6)},${startPos[1].toFixed(6)},${endPos[0].toFixed(6)},${endPos[1].toFixed(6)}`;
      segmentInfo = sampledSegmentIndex.get(searchKey);
      if (segmentInfo && !usedElementsInThisFace.has(segmentInfo.elementIndex)) {
        segmentKey = `${segmentInfo.elementIndex}-${segmentInfo.sampleIndex}`;
        if (!usedSampledSegments.has(segmentKey)) {
          foundElement = segmentInfo.originalElement;
          usedElementsInThisFace.add(segmentInfo.elementIndex);
          usedSampledSegments.add(segmentKey);
          foundInSampled = true;
        }
      }
      
      // 如果在采样线段中没找到，检查原始直线元素
      if (!foundInSampled) {
        for (j = n = 0, ref2 = elements.length; (0 <= ref2 ? n < ref2 : n > ref2); j = 0 <= ref2 ? ++n : --n) {
          if (usedElementsInThisFace.has(j)) {
            // 跳过在当前面中已使用的元素
            continue;
          }
          if (sampledElementsMap.has(j)) {
            // 跳过已被采样的元素
            continue;
          }
          element = elements[j];
          elementStart = element.s();
          elementEnd = element.e();
          if ((pointsEqual(startPos, [elementStart.x, elementStart.y]) && pointsEqual(endPos, [elementEnd.x, elementEnd.y])) || (pointsEqual(startPos, [elementEnd.x, elementEnd.y]) && pointsEqual(endPos, [elementStart.x, elementStart.y]))) {
            foundElement = element;
            usedElementsInThisFace.add(j); // 标记为在当前面中已使用
            break;
          }
        }
      }
      if (foundElement) {
        // 检查是否已经添加过这个元素（避免重复）
        if (!faceElements.includes(foundElement)) {
          faceElements.push(foundElement);
        }
      }
    }
    if (faceElements.length > 0) {
      regionElements.push(faceElements);
    }
  }
  return regionElements;
};
