// Generated by CoffeeScript 2.7.0
var Vertex;

export default Vertex = class Vertex {
  constructor(name, position) {
    this.name = name;
    this.position = position;
    this.visited = 0; // 0: unvisited, 1: discovered, 2: finished
    this.adjacent = []; // 改为数组以允许重复邻居
  }

};
